"use strict";

/* Life RPG 11.1.0 — Calibration & Learning Loop
   Learns only from observable plan/fact data. It never treats estimates as measured time.
   Capacity tuning is conservative, bounded and reversible. */

const CALIBRATION_VERSION=1;
const CALIBRATION_MAX_EVENTS=1200;
const CALIBRATION_MAX_DAYS=120;
let calibrationExposurePersistScheduled=false;

function calibrationState(){
  let c=S.settings.calibration;
  if(!c||typeof c!=="object"||Array.isArray(c))c={};
  if(!Array.isArray(c.taskEvents))c.taskEvents=[];
  if(!Array.isArray(c.decisionEvents))c.decisionEvents=[];
  if(!c.days||typeof c.days!=="object"||Array.isArray(c.days))c.days={};
  c.version=CALIBRATION_VERSION;
  c.autoTuneEnabled=c.autoTuneEnabled!==false;
  c.capacityFactor=clamp(Number.isFinite(+c.capacityFactor)?+c.capacityFactor:1,.65,1.15);
  c.lastAutoTuneWeek=String(c.lastAutoTuneWeek||"");
  c.lastAdjustment=c.lastAdjustment&&typeof c.lastAdjustment==="object"?c.lastAdjustment:null;
  S.settings.calibration=c;
  return c
}
function calibrationTrim(){const c=calibrationState();if(c.taskEvents.length>CALIBRATION_MAX_EVENTS)c.taskEvents.splice(0,c.taskEvents.length-CALIBRATION_MAX_EVENTS);if(c.decisionEvents.length>CALIBRATION_MAX_EVENTS)c.decisionEvents.splice(0,c.decisionEvents.length-CALIBRATION_MAX_EVENTS);const keys=Object.keys(c.days).sort();for(const k of keys.slice(0,Math.max(0,keys.length-CALIBRATION_MAX_DAYS)))delete c.days[k]}
function calibrationEvent(arr,event){arr.push({ts:new Date().toISOString(),...event});calibrationTrim()}
function calibrationTaskEvent(type,t,extra={}){if(!t)return;const c=calibrationState();calibrationEvent(c.taskEvents,{type,taskId:String(t.id||""),area:String(t.area||""),priority:+t.priority||2,estimateMinutes:Math.max(0,+t.minutes||0),plannedDate:String(t.plannedDate||""),dueDate:String(t.dueDate||""),...extra})}
function calibrationDecisionEvent(type,id,extra={}){const c=calibrationState();calibrationEvent(c.decisionEvents,{type,id:String(id||""),dateKey:localDateKey(),...extra})}
function calibrationDay(dateKey=localDateKey()){const c=calibrationState();if(!c.days[dateKey]||typeof c.days[dateKey]!=="object")c.days[dateKey]={dateKey,firstSeenAt:new Date().toISOString(),firstPlan:null,latestPlan:null};return c.days[dateKey]}
function calibrationPlannedTasksOn(dateKey){return typeof taskAll==="function"?taskAll().filter(t=>t.status!=="cancelled"&&t.plannedDate===dateKey).map(t=>({id:t.id,minutes:Math.max(0,+t.minutes||0),priority:+t.priority||2,area:t.area||""})):[]}
function calibrationCaptureDay(dateKey=localDateKey()){
  const d=calibrationDay(dateKey),rows=calibrationPlannedTasksOn(dateKey),snap={capturedAt:new Date().toISOString(),taskIds:rows.map(x=>x.id),tasks:rows.map(x=>({id:x.id,minutes:x.minutes})),plannedMinutes:rows.reduce((s,x)=>s+x.minutes,0),taskCount:rows.length};
  if(!d.firstPlan||(!(d.firstPlan.plannedMinutes>0)&&snap.plannedMinutes>0))d.firstPlan=deepClone(snap);d.latestPlan=deepClone(snap);return d
}
function calibrationCompletionDate(t){return String(t?.completedAt||"").slice(0,10)}
function calibrationDayFact(dateKey){
  const d=calibrationState().days[dateKey]||{},ids=new Set(d.firstPlan?.taskIds||[]),plannedRows=Array.isArray(d.firstPlan?.tasks)?d.firstPlan.tasks:[],plannedById=new Map(plannedRows.map(x=>[String(x.id),Math.max(0,+x.minutes||0)])),tasks=typeof taskAll==="function"?taskAll():[],planned=Math.max(0,+d.firstPlan?.plannedMinutes||0),completed=tasks.filter(t=>ids.has(t.id)&&t.status==="done"&&calibrationCompletionDate(t)===dateKey),completedMinutes=completed.reduce((sum,t)=>sum+(plannedById.has(t.id)?plannedById.get(t.id):Math.max(0,+t.minutes||0)),0),timed=completed.filter(t=>+t.actualMinutes>0&&!t.timerCapped),actual=timed.reduce((sum,t)=>sum+(+t.actualMinutes||0),0);
  return {dateKey,plannedMinutes:planned,plannedTasks:ids.size,completedTasks:completed.length,completedMinutes,completionRatio:planned?clamp(completedMinutes/planned,0,1.5):null,timedTasks:timed.length,actualMinutes:actual}
}
function calibrationRecentDays(days=28){const today=localDateKey(),start=localDateKey(addDays(new Date(),-days));return Object.keys(calibrationState().days).filter(k=>validDateKey(k)&&k>=start&&k<today).sort().map(calibrationDayFact)}
function calibrationMedian(xs){const a=xs.filter(Number.isFinite).slice().sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function calibrationQuantile(xs,q){const a=xs.filter(Number.isFinite).slice().sort((x,y)=>x-y);if(!a.length)return null;const pos=(a.length-1)*q,lo=Math.floor(pos),hi=Math.ceil(pos);return lo===hi?a[lo]:a[lo]+(a[hi]-a[lo])*(pos-lo)}
function calibrationTimedCompletions(days=56){const cutoff=Date.now()-days*86400000;return (typeof taskAll==="function"?taskAll():[]).filter(t=>t.status==="done"&&Date.parse(t.completedAt||0)>=cutoff&&+t.actualMinutes>0&&+t.minutes>0&&!t.timerCapped)}
function calibrationEstimateStats(){const rows=calibrationTimedCompletions();if(rows.length<5)return {ready:false,n:rows.length,need:5};const ratios=rows.map(t=>+t.actualMinutes/(+t.minutes||1)),ape=rows.map(t=>Math.abs(+t.actualMinutes-(+t.minutes||1))/(+t.minutes||1));return {ready:true,n:rows.length,medianRatio:calibrationMedian(ratios),mape:calibrationMedian(ape),under:rows.filter(t=>+t.actualMinutes>+t.minutes*1.2).length,over:rows.filter(t=>+t.actualMinutes<+t.minutes*.8).length}}
function calibrationPlanStats(days=28){const rows=calibrationRecentDays(days).filter(x=>x.plannedMinutes>=60);if(!rows.length)return {ready:false,n:0,rows,adherence:null,successRate:null};const ratios=rows.map(x=>Math.min(1,x.completionRatio||0)),success=rows.filter(x=>(x.completionRatio||0)>=.8);return {ready:rows.length>=8,n:rows.length,rows,adherence:ratios.reduce((s,x)=>s+x,0)/ratios.length,successRate:success.length/rows.length,sustainableMinutes:success.length>=3?Math.round(calibrationMedian(success.map(x=>x.plannedMinutes))):null}}
function calibrationRescheduleStats(days=28){const cutoff=Date.now()-days*86400000,events=calibrationState().taskEvents.filter(x=>Date.parse(x.ts||0)>=cutoff),manual=events.filter(x=>x.type==="reschedule").length,auto=events.filter(x=>x.type==="reschedule-auto").length,assigned=events.filter(x=>x.type==="plan-assigned").length;return {manual,auto,assigned,total:manual+auto}}
function calibrationDecisionStats(days=28){const cutoff=Date.now()-days*86400000,events=calibrationState().decisionEvents.filter(x=>Date.parse(x.ts||0)>=cutoff),shown=events.filter(x=>x.type==="shown"),actions=events.filter(x=>["execute","execute-observed","boost","snooze","hide","never"].includes(x.type)),shownKeys=new Set(shown.map(x=>`${x.dateKey}|${x.id}`)),actionKeys=new Set(actions.map(x=>`${x.dateKey}|${x.id}`)),acceptedKeys=new Set(actions.filter(x=>["execute","execute-observed","boost"].includes(x.type)).map(x=>`${x.dateKey}|${x.id}`)),deferredKeys=new Set(actions.filter(x=>["snooze","hide"].includes(x.type)).map(x=>`${x.dateKey}|${x.id}`)),rejectedKeys=new Set(actions.filter(x=>x.type==="never").map(x=>`${x.dateKey}|${x.id}`));return {shown:shownKeys.size,actions:actionKeys.size,accepted:acceptedKeys.size,deferred:deferredKeys.size,rejected:rejectedKeys.size,ignored:Math.max(0,shownKeys.size-actionKeys.size),actionRate:shownKeys.size?actionKeys.size/shownKeys.size:null}}
function calibrationCapacityFactor(){return calibrationState().capacityFactor}
function calibrationCapacityFor(baseCapacity,baseLoad=0){const factor=calibrationCapacityFactor(),free=Math.max(0,baseCapacity-baseLoad);return Math.max(baseLoad,Math.round(baseLoad+free*factor))}
function calibrationRecommendation(){const p=calibrationPlanStats(42),c=calibrationState();if(!p.ready)return {ready:false,n:p.n,factor:c.capacityFactor,reason:`Нужно минимум 8 загруженных дней (≥60 мин задач); сейчас ${p.n}.`};let delta=0,reason="Фактическое выполнение соответствует текущей ёмкости.";if(p.adherence<.6){delta=-.05;reason=`Среднее выполнение плана ${Math.round(p.adherence*100)}% — task-бюджет завышен.`}else if(p.adherence<.75){delta=-.03;reason=`Среднее выполнение плана ${Math.round(p.adherence*100)}% — нужна небольшая коррекция вниз.`}else if(p.adherence>=.9&&p.successRate>=.75){delta=.03;reason=`Выполнение ${Math.round(p.adherence*100)}%, успешных загруженных дней ${Math.round(p.successRate*100)}% — есть запас для небольшой коррекции вверх.`}return {ready:true,n:p.n,factor:c.capacityFactor,delta,target:clamp(c.capacityFactor+delta,.65,1.15),reason,adherence:p.adherence,successRate:p.successRate,sustainableMinutes:p.sustainableMinutes}}
function calibrationWeekKey(){return isoWeekKey(new Date())}
async function calibrationMaybeAutoTune(force=false){const c=calibrationState(),rec=calibrationRecommendation(),week=calibrationWeekKey();if(!c.autoTuneEnabled||!rec.ready||(!force&&c.lastAutoTuneWeek===week)||!rec.delta)return {changed:false,...rec};const before=c.capacityFactor,after=clamp(before+clamp(rec.delta,-.05,.05),.65,1.15);if(Math.abs(after-before)<.005){c.lastAutoTuneWeek=week;return {changed:false,...rec}}c.capacityFactor=after;c.lastAutoTuneWeek=week;c.lastAdjustment={at:new Date().toISOString(),week,before,after,reason:rec.reason,sample:rec.n};calibrationDecisionEvent("capacity-tune","execution:capacity",{before,after,sample:rec.n,reason:rec.reason});if(typeof audit==="function")audit("Calibration capacity tune","system",`${Math.round(before*100)}% → ${Math.round(after*100)}% • ${rec.reason}`);if(typeof persist==="function")await persist();return {changed:true,...rec,before,after}}
async function calibrationOnBoot(){if(typeof storageLoadBlocked!=="undefined"&&storageLoadBlocked)return {skipped:true};const c=calibrationState(),today=localDateKey(),had=!!c.days[today]?.firstPlan;calibrationCaptureDay();const tuned=await calibrationMaybeAutoTune(false);if(!had&&!tuned.changed&&typeof persist==="function")await persist();return tuned}
function calibrationRecordReschedule(t,from,to,source="manual"){if(!t||from===to)return;const type=!from?"plan-assigned":source==="auto"?"reschedule-auto":"reschedule";calibrationTaskEvent(type,t,{from:String(from||""),to:String(to||"")})}
function calibrationRecordCompletion(t){if(!t)return;const completedDate=calibrationCompletionDate(t);calibrationTaskEvent("completed",t,{completedDate,actualMinutes:+t.actualMinutes||0,rescheduleCount:+t.rescheduleCount||0});const id=`task:${t.id}`,shown=calibrationState().decisionEvents.some(x=>x.type==="shown"&&x.dateKey===completedDate&&x.id===id);if(shown)calibrationDecisionEvent("execute-observed",id,{source:"Tasks OS",kind:"task-completed"})}
function calibrationRecordDecisionExposure(rows){const c=calibrationState(),today=localDateKey(),seen=new Set(c.decisionEvents.filter(x=>x.type==="shown"&&x.dateKey===today).map(x=>x.id));let changed=false;for(const x of rows||[]){if(!x?.id||seen.has(x.id))continue;calibrationDecisionEvent("shown",x.id,{source:typeof decisionSource==="function"?decisionSource(x):String(x.source||x.area||"Life OS"),score:+x.score||0,kind:String(x.kind||"")});seen.add(x.id);changed=true}if(changed&&!calibrationExposurePersistScheduled&&typeof persist==="function"&&!(typeof storageLoadBlocked!=="undefined"&&storageLoadBlocked)){calibrationExposurePersistScheduled=true;Promise.resolve().then(()=>persist()).catch(()=>{}).finally(()=>{calibrationExposurePersistScheduled=false})}}
function calibrationRecordDecisionAction(type,id,extra={}){calibrationDecisionEvent(type,id,extra)}
function calibrationStartTaskTimer(id){const t=typeof taskAll==="function"?taskAll().find(x=>x.id===id):null;if(!t||t.status!=="active"||t.timerStartedAt)return false;t.timerStartedAt=new Date().toISOString();t.updatedAt=t.timerStartedAt;calibrationTaskEvent("timer-start",t);return true}
function calibrationStopTaskTimerCore(t){if(!t?.timerStartedAt)return 0;const start=Date.parse(t.timerStartedAt),now=Date.now(),raw=Number.isFinite(start)?Math.round((now-start)/60000):0,mins=clamp(raw||1,1,480);t.actualMinutes=Math.max(0,+t.actualMinutes||0)+mins;if(raw>480)t.timerCapped=true;t.timerStartedAt="";t.updatedAt=new Date().toISOString();calibrationTaskEvent("timer-stop",t,{segmentMinutes:mins,capped:raw>480});return mins}
async function startTaskTimer(id){if(!calibrationStartTaskTimer(id)){toast("Таймер уже запущен или задача закрыта");return}await save("Таймер задачи запущен")}
async function stopTaskTimer(id){const t=taskAll().find(x=>x.id===id);const mins=calibrationStopTaskTimerCore(t);if(!mins){toast("Таймер не запущен");return}await save(`Записано ${mins} мин по задаче`)}
function calibrationSummary(){const p=calibrationPlanStats(42),e=calibrationEstimateStats(),r=calibrationRescheduleStats(),d=calibrationDecisionStats(),c=calibrationState(),rec=calibrationRecommendation();return {plan:p,estimate:e,reschedule:r,decision:d,factor:c.capacityFactor,lastAdjustment:c.lastAdjustment,recommendation:rec}}
async function saveCalibrationSettings(){const c=calibrationState(),toggle=document.getElementById("calibrationAutoTune");if(toggle)c.autoTuneEnabled=!!toggle.checked;await save("Настройки калибровки сохранены")}
async function resetCalibrationCapacity(){const c=calibrationState();c.capacityFactor=1;c.lastAutoTuneWeek=calibrationWeekKey();c.lastAdjustment={at:new Date().toISOString(),before:null,after:1,reason:"Ручной сброс коэффициента",sample:0};await save("Коэффициент Execution Capacity сброшен")}
function ensureCalibrationOsUi(){if(document.getElementById("calibrationOsCommand"))return;const grid=document.querySelector?.("#more .grid");if(!grid||typeof grid.insertAdjacentHTML!=="function")return;grid.insertAdjacentHTML("beforeend",`<div data-ux7-view="overview" class="card ux7-card span-12"><div class="eyebrow">Calibration & Learning Loop</div><div class="section-title">План → факт → коррекция</div><div class="muted" style="margin-top:6px">Автокалибровка использует только наблюдаемые результаты. Оценка времени сравнивается с фактом только для задач с таймером.</div><div id="calibrationOsCommand" style="margin-top:10px"></div><label class="toggle-line" style="margin-top:10px"><input id="calibrationAutoTune" type="checkbox"><span>Автоматически корректировать task-бюджет не чаще 1 раза в неделю</span></label><div class="split" style="margin-top:8px"><button class="btn ghost small" onclick="saveCalibrationSettings()">Сохранить</button><button class="btn ghost small" onclick="resetCalibrationCapacity()">Сбросить коэффициент</button></div></div>`)}
function renderCalibrationOs(){const box=document.getElementById("calibrationOsCommand");if(!box)return;calibrationCaptureDay();const q=calibrationSummary(),auto=document.getElementById("calibrationAutoTune");if(auto&&document.activeElement!==auto)auto.checked=calibrationState().autoTuneEnabled;const plan=q.plan.ready?`${Math.round(q.plan.adherence*100)}% • ${q.plan.n} дн.`:`данных ${q.plan.n}/8`,estimate=q.estimate.ready?`медиана факт/оценка ${q.estimate.medianRatio.toFixed(2)}× • ошибка ${Math.round(q.estimate.mape*100)}%`:`таймер ${q.estimate.n}/5 задач`,decision=q.decision.shown?`${q.decision.actions}/${q.decision.shown} • принято ${q.decision.accepted} • отложено ${q.decision.deferred} • без реакции ${q.decision.ignored}`:`нет выборки`,adj=q.lastAdjustment?`${Math.round((q.lastAdjustment.before??1)*100)}% → ${Math.round(q.lastAdjustment.after*100)}%`:`ещё не было`;box.innerHTML=`<div class="report-grid"><div class="report-item"><div class="smallcaps">Выполнение плана</div><b>${plan}</b></div><div class="report-item"><div class="smallcaps">Точность оценок</div><b>${estimate}</b></div><div class="report-item"><div class="smallcaps">Переносы 28д</div><b>${q.reschedule.total}</b></div><div class="report-item"><div class="smallcaps">Реакции Life OS</div><b>${decision}</b></div><div class="report-item"><div class="smallcaps">Execution factor</div><b>${Math.round(q.factor*100)}%</b></div><div class="report-item"><div class="smallcaps">Последняя коррекция</div><b>${adj}</b></div></div><div class="notice" style="margin-top:10px"><b>Калибровка:</b> ${escapeHtml(q.recommendation.reason)}</div>`}
