"use strict";

/* Life RPG 11.1.0 — Search / Command Palette */

let commandIndex=new Map(),commandListenerInstalled=false;
function commandNorm(s){return String(s||"").toLocaleLowerCase("ru-RU").replace(/ё/g,"е").replace(/[^a-zа-я0-9]+/g," ").trim()}
function commandRoute(type,id){closeCommandPalette();if(type==="task"){ux7Go("today","focus");setTimeout(()=>{document.getElementById("tasksOsCommand")?.scrollIntoView?.({behavior:"smooth",block:"center"});if(id)editTask(id)},100);return}if(type==="routine"){ux7Go("today","focus");setTimeout(()=>document.getElementById("routinesOsCommand")?.scrollIntoView?.({behavior:"smooth",block:"center"}),100);return}if(type==="inbox"){ux7Go("today","focus");setTimeout(()=>document.getElementById("inboxOsCommand")?.scrollIntoView?.({behavior:"smooth",block:"center"}),100);return}if(type==="project"){ux7Go("more","overview");setTimeout(()=>{document.getElementById("projectsOsCommand")?.scrollIntoView?.({behavior:"smooth",block:"center"});if(id)editProject(id)},100);return}if(type==="goal"){ux7Go("more","overview");setTimeout(()=>{document.getElementById("goalsOsCommand")?.scrollIntoView?.({behavior:"smooth",block:"center"});if(id)editGoal(id)},100);return}if(type==="crm"){ux7Go("work","crm");return}if(type==="book"){ux7Go("more","knowledge");return}if(type==="calendar"){ux7Go("more","overview");setTimeout(()=>document.getElementById("calendarOsCommand")?.scrollIntoView?.({behavior:"smooth",block:"center"}),100);return}if(type==="calibration"){ux7Go("more","overview");setTimeout(()=>document.getElementById("calibrationOsCommand")?.scrollIntoView?.({behavior:"smooth",block:"center"}),100);return}if(type==="review"){ux7Go("more","overview");setTimeout(()=>document.getElementById("reviewOsCommand")?.scrollIntoView?.({behavior:"smooth",block:"center"}),100)}}
function commandQuickActions(){return [
  {key:"quick:new-task",kind:"Команда",title:"Новая задача",meta:"Tasks OS",run(){closeCommandPalette();ux7Go("today","focus");setTimeout(()=>{document.getElementById("taskEditorCard").hidden=false;document.getElementById("taskTitle")?.focus()},100)}},
  {key:"quick:capture",kind:"Команда",title:"Записать во Inbox",meta:"Capture OS",run(){closeCommandPalette();ux7Go("today","focus");setTimeout(()=>document.getElementById("inboxCaptureInput")?.focus(),100)}},
  {key:"quick:new-goal",kind:"Команда",title:"Новая цель",meta:"Goals OS",run(){closeCommandPalette();ux7Go("more","overview");setTimeout(()=>{document.getElementById("goalProjectLinks").innerHTML=goalProjectOptions([]);document.getElementById("goalEditorCard").hidden=false;document.getElementById("goalTitle")?.focus()},100)}},
  {key:"quick:new-project",kind:"Команда",title:"Новый проект",meta:"Projects OS",run(){closeCommandPalette();ux7Go("more","overview");setTimeout(()=>projectToggleEditor(true),100)}},
  {key:"quick:new-routine",kind:"Команда",title:"Новая рутина",meta:"Routines OS",run(){closeCommandPalette();ux7Go("today","focus");setTimeout(()=>{document.getElementById("routineDayPicker").innerHTML=routineDayPicker();document.getElementById("routineEditorCard").hidden=false;document.getElementById("routineTitle")?.focus()},100)}},
  {key:"quick:calendar",kind:"Навигация",title:"Открыть календарь",meta:"Calendar / Timeline OS",run(){commandRoute("calendar")}},
  {key:"quick:calibration",kind:"Навигация",title:"Открыть калибровку",meta:"Calibration & Learning Loop",run(){commandRoute("calibration")}},
  {key:"quick:review",kind:"Навигация",title:"Открыть обзор периода",meta:"Review / Planning OS",run(){commandRoute("review")}}
]}
function commandEntityRows(){const out=[];for(const x of (typeof taskActive==="function"?taskActive():[]))out.push({key:`task:${x.id}`,kind:"Задача",title:x.title,meta:`${x.area}${x.dueDate?` • ${x.dueDate}`:""}`,run(){commandRoute("task",x.id)}});for(const x of (typeof projectActive==="function"?projectActive():[]))out.push({key:`project:${x.id}`,kind:"Проект",title:x.title,meta:`${x.area} • ${x.progress||0}%`,run(){commandRoute("project",x.id)}});for(const x of (typeof goalActive==="function"?goalActive():[]))out.push({key:`goal:${x.id}`,kind:"Цель",title:x.title,meta:`${x.area} • ${goalProgress(x)}%`,run(){commandRoute("goal",x.id)}});for(const x of (typeof routineActive==="function"?routineActive():[]))out.push({key:`routine:${x.id}`,kind:"Рутина",title:x.title,meta:x.area,run(){commandRoute("routine",x.id)}});for(const x of (typeof inboxOpen==="function"?inboxOpen():[]))out.push({key:`inbox:${x.id}`,kind:"Inbox",title:x.text,meta:x.area,run(){commandRoute("inbox",x.id)}});for(const x of (S.crmDeals||[]).filter(x=>!["Выиграно","Проиграно"].includes(x.stage)))out.push({key:`crm:${x.id}`,kind:"CRM",title:x.name||"Сделка",meta:`${x.city||""}${x.nextStep?` • ${x.nextStep}`:""}`,run(){commandRoute("crm",x.id)}});for(const x of (S.books||[]).filter(x=>x.status!=="done").slice(0,50))out.push({key:`book:${x.id}`,kind:"Книга",title:x.title||"Книга",meta:x.author||"",run(){commandRoute("book",x.id)}});for(const x of (typeof calendarManualEvents==="function"?calendarManualEvents().filter(x=>x.status==="planned"):[]))out.push({key:`calendar:${x.id}`,kind:"Календарь",title:x.title,meta:`${x.dateKey} • ${x.area}`,run(){commandRoute("calendar",x.id)}});return out}
function commandSearch(q){const n=commandNorm(q),rows=n?[...commandQuickActions(),...commandEntityRows()]:commandQuickActions();if(!n)return rows.slice(0,12);return rows.map(x=>{const h=commandNorm(`${x.kind} ${x.title} ${x.meta}`),parts=n.split(" ").filter(Boolean),score=parts.reduce((s,p)=>s+(h.includes(p)?1:0),0)+(commandNorm(x.title).startsWith(n)?2:0);return {...x,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||xcmp(a.title,b.title)).slice(0,20)}
function xcmp(a,b){return String(a).localeCompare(String(b),"ru")}
function renderCommandPalette(){const box=document.getElementById("commandResults"),input=document.getElementById("commandInput");if(!box)return;const rows=commandSearch(input?.value||"");commandIndex=new Map(rows.map(x=>[x.key,x]));box.innerHTML=rows.length?rows.map(x=>`<button class="btn ghost" style="width:100%;text-align:left;margin-top:6px" onclick="commandExecute('${x.key}')"><b>${escapeHtml(x.title)}</b><span class="sub" style="display:block">${escapeHtml(x.kind)}${x.meta?` • ${escapeHtml(x.meta)}`:""}</span></button>`).join(""):'<div class="empty">Ничего не найдено.</div>'}
function commandExecute(key){const x=commandIndex.get(key);if(x?.run)x.run()}
function openCommandPalette(){const m=document.getElementById("commandPalette");if(!m)return;m.classList.add("open");const i=document.getElementById("commandInput");if(i){i.value="";setTimeout(()=>i.focus(),0)}renderCommandPalette()}
function closeCommandPalette(){document.getElementById("commandPalette")?.classList.remove("open")}
function ensureCommandOsUi(){if(document.getElementById("commandPalette"))return;const top=document.querySelector?.(".top-actions");if(top&&typeof top.insertAdjacentHTML==="function"&&!document.getElementById("commandPaletteBtn"))top.insertAdjacentHTML("afterbegin",'<button class="iconbtn" id="commandPaletteBtn" onclick="openCommandPalette()" title="Поиск и команды">⌕</button>');document.body?.insertAdjacentHTML?.("beforeend",`<div class="modal" id="commandPalette"><div class="modal-card"><div class="modal-head"><div><div class="eyebrow">Command Palette</div><div class="title">Поиск и быстрые команды</div></div><button class="close" onclick="closeCommandPalette()">×</button></div><div class="field"><label>Найти задачу, проект, цель, CRM, книгу…</label><input id="commandInput" autocomplete="off" placeholder="Начни вводить" oninput="renderCommandPalette()"></div><div id="commandResults" style="margin-top:10px"></div><div class="sub" style="margin-top:10px">На компьютере: Ctrl/⌘ + K.</div></div></div>`);if(!commandListenerInstalled&&document.addEventListener){commandListenerInstalled=true;document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&String(e.key).toLowerCase()==="k"){e.preventDefault();openCommandPalette()}else if(e.key==="Escape")closeCommandPalette()})}}
function renderCommandOs(){if(document.getElementById("commandPalette")?.classList?.contains("open"))renderCommandPalette()}
