"use strict";

/* Life RPG 11.0.0 — Explainable Decision Layer */

function decisionPreferenceStore(){if(!S.settings.decisionPreferences||typeof S.settings.decisionPreferences!=="object"||Array.isArray(S.settings.decisionPreferences))S.settings.decisionPreferences={};return S.settings.decisionPreferences}
function decisionPreference(id){return decisionPreferenceStore()[String(id)]||null}
function decisionAdjustCandidates(rows){const today=localDateKey(),prefs=decisionPreferenceStore(),out=[];for(const x of rows){const p=prefs[x.id]||{};if(p.disabled)continue;if(p.hiddenDate===today)continue;if(validDateKey(p.notBefore)&&today<p.notBefore)continue;out.push({...x,score:Math.max(0,(+x.score||0)+(+p.scoreDelta||0)),userAdjusted:!!(p.scoreDelta||p.notBefore||p.hiddenDate)})}return out}
function decisionSource(x){if(x.source)return x.source;if(x.id.startsWith("finance:"))return"Finance OS";if(x.id.startsWith("work:"))return"Work / CRM OS";if(x.id.startsWith("task:"))return"Tasks OS";if(x.id.startsWith("project:"))return"Projects OS";if(x.id.startsWith("goal:"))return"Goals OS";if(x.id.startsWith("routine:"))return"Routines OS";if(x.id.startsWith("review:"))return"Review OS";if(x.id.startsWith("calendar:"))return"Calendar OS";if(x.id.startsWith("rule:"))return"Rules OS";if(x.id.startsWith("execution:"))return"Execution Intelligence";return x.area||"Life OS"}
function decisionConfidence(x){if(x.confidence)return x.confidence;if(x.hard||/overdue|deadline|payment|task-planned/.test(x.kind))return"high";if(/pace|goal|load|form|pipeline|execution/.test(x.kind))return"medium";return"medium"}
function decisionConsequence(x){if(x.consequence)return x.consequence;if(x.hard)return"Откладывание повышает риск нарушения уже существующего обязательства.";if(/overdue/.test(x.kind))return"Просрочка останется открытой и продолжит конкурировать за верхние позиции Life OS.";if(/deadline/.test(x.kind))return"Сократится доступный запас времени до срока.";if(/pace|pipeline/.test(x.kind))return"Отставание по темпу может увеличиться, если не компенсировать его позже.";if(/goal/.test(x.kind))return"Вероятность не успеть к горизонту цели увеличится, если прогресс не будет компенсирован.";if(/execution/.test(x.kind))return"Часть задач останется вне доступной ёмкости недели или уйдёт после дедлайна.";return"Действие останется в очереди и может быть вытеснено более срочными обязательствами."}
function decisionExplain(x,rank=1){const confidence=decisionConfidence(x),pref=decisionPreference(x.id);return {id:x.id,rank,source:decisionSource(x),confidence,why:x.hard?"Жёсткое обязательство имеет приоритет над мягкими действиями.":`Текущий приоритет модели: ${Math.round(x.score)}. Выше оказываются более срочные, просроченные или усиленные пользователем действия.`,evidence:[x.meta||"Нет дополнительного описания",x.userAdjusted?"Ранжирование скорректировано пользователем":"Ранжирование без ручной корректировки"],consequence:decisionConsequence(x),preference:pref}}
function decisionToken(id){return encodeURIComponent(String(id))}
function decisionByToken(token){const id=decodeURIComponent(String(token||""));return lifeOsCandidates().find(x=>x.id===id)||lifeOsRawCandidates().find(x=>x.id===id)||null}
async function decisionExecuteToken(token){const x=decisionByToken(token);if(!x)return;if(x.taskId&&typeof completeTask==="function"){await completeTask(x.taskId);return}if(x.routineId&&typeof completeRoutine==="function"){await completeRoutine(x.routineId);return}lifeOsOpen(x.area,x.route)}
async function decisionSetPreference(token,action){const id=decodeURIComponent(String(token||"")),store=decisionPreferenceStore(),p={...(store[id]||{})},today=localDateKey();if(action==="boost")p.scoreDelta=clamp((+p.scoreDelta||0)+20,-40,60);if(action==="snooze")p.notBefore=localDateKey(addDays(new Date(),1));if(action==="hide")p.hiddenDate=today;if(action==="never")p.disabled=true;if(action==="reset"){delete store[id]}else{p.updatedAt=new Date().toISOString();store[id]=p}audit("Decision preference","system",`${action} • ${id}`);await save("Приоритет Life OS обновлён")}
function decisionActionButtons(x){const t=decisionToken(x.id);return `<div class="split"><button class="btn secondary small" onclick="decisionExecuteToken('${t}')">${x.taskId||x.routineId?"✓":"Открыть"}</button><button class="btn ghost small" onclick="decisionSetPreference('${t}','boost')">↑</button><button class="btn ghost small" onclick="decisionSetPreference('${t}','snooze')">Завтра</button><button class="btn ghost small" onclick="decisionSetPreference('${t}','hide')">Скрыть</button><button class="btn ghost small" onclick="decisionSetPreference('${t}','never')">Не предлагать</button></div>`}
function decisionPreferenceRows(){const store=decisionPreferenceStore();return Object.entries(store).map(([id,p])=>({id,...p})).sort((a,b)=>String(b.updatedAt||"").localeCompare(String(a.updatedAt||"")))}

function todayFlowSummary(){
  const life=lifeOsDailyPlan(),tasks=typeof taskSummary==="function"?taskSummary():{active:0,overdue:0},routines=typeof routineDueToday==="function"?routineDueToday():[],inbox=typeof inboxOpen==="function"?inboxOpen():[],execution=typeof executionPlan==="function"?executionPlan():null;
  const today=localDateKey(),planned=execution?.assignments?.filter(x=>x.dateKey===today).length||0,conflicts=(execution?.late?.length||0)+(execution?.unscheduled?.length||0)+(execution?.overloaded?.length||0);
  return {priorities:life.plan.length,hard:life.hardAll.length,tasks:tasks.active||0,overdue:tasks.overdue||0,routines:routines.length,inbox:inbox.length,planned,conflicts}
}
function todayFlowJump(id){document.getElementById(id)?.scrollIntoView?.({behavior:"smooth",block:"start"})}
function ensureTodayFlowUi(){
  if(document.getElementById("todayFlowCommand"))return;
  const grid=document.querySelector?.("#today .grid"),anchor=document.getElementById("lifeOsCommand")?.closest?.(".card");if(!grid||!anchor||typeof anchor.insertAdjacentHTML!=="function")return;
  anchor.insertAdjacentHTML("afterend",`<div data-ux7-view="focus" class="card ux7-card span-12"><div class="eyebrow">Today Flow</div><div class="section-title">Один рабочий контур на день</div><div class="muted" style="margin-top:6px">Входящие → приоритеты → выполнение → отметка. Аналитические OS остаются ниже и не требуют обхода всех разделов.</div><div id="todayFlowCommand" style="margin-top:10px"></div></div>`)
}
function renderTodayFlow(){
  const box=document.getElementById("todayFlowCommand");if(!box)return;const x=todayFlowSummary();
  box.innerHTML=`<div class="report-grid"><div class="report-item"><div class="smallcaps">Приоритеты</div><b>${x.priorities}${x.hard?` • жёстких ${x.hard}`:""}</b></div><div class="report-item"><div class="smallcaps">Задачи</div><b>${x.tasks}${x.overdue?` • просрочено ${x.overdue}`:""}</b></div><div class="report-item"><div class="smallcaps">Рутины сегодня</div><b>${x.routines}</b></div><div class="report-item"><div class="smallcaps">Inbox</div><b>${x.inbox}</b></div><div class="report-item"><div class="smallcaps">В плане сегодня</div><b>${x.planned}</b></div><div class="report-item"><div class="smallcaps">Конфликты недели</div><b class="${x.conflicts?"income-bad":""}">${x.conflicts}</b></div></div><div class="split" style="margin-top:10px"><button class="btn secondary small" onclick="todayFlowJump('inboxOsCommand')">Inbox</button><button class="btn secondary small" onclick="todayFlowJump('tasksOsCommand')">Задачи</button><button class="btn secondary small" onclick="todayFlowJump('routinesOsCommand')">Рутины</button><button class="btn secondary small" onclick="todayFlowJump('executionOsCommand')">План недели</button></div>`
}

function ensureDecisionOsUi(){
  ensureTodayFlowUi();
  if(!document.getElementById("decisionOsCommand")){const grid=document.querySelector?.("#today .grid"),anchor=document.getElementById("todayFlowCommand")?.closest?.(".card")||document.getElementById("lifeOsCommand")?.closest?.(".card");if(grid&&anchor&&typeof anchor.insertAdjacentHTML==="function")anchor.insertAdjacentHTML("afterend",`<div data-ux7-view="focus" class="card ux7-card span-12"><div class="eyebrow">Decision Transparency</div><div class="section-title">Почему именно это</div><div class="muted" style="margin-top:6px">Факты отделены от эвристик. Уверенность показывает надёжность основания, а не вероятность успеха.</div><div id="decisionOsCommand" style="margin-top:10px"></div></div>`)}
  if(!document.getElementById("decisionPreferences")){const grid=document.querySelector?.("#more .grid");if(grid&&typeof grid.insertAdjacentHTML==="function")grid.insertAdjacentHTML("beforeend",`<div data-ux7-view="settings" class="card ux7-card span-12"><div class="eyebrow">Decision preferences</div><div class="section-title">Мои корректировки Life OS</div><div class="muted" style="margin-top:6px">Здесь видны усиленные, отложенные и отключённые рекомендации. Любую настройку можно отменить.</div><div id="decisionPreferences" style="margin-top:10px"></div></div>`)}
}
function renderDecisionOs(){renderTodayFlow();const box=document.getElementById("decisionOsCommand");if(box){const rows=lifeOsDailyPlan().plan.slice(0,3);box.innerHTML=rows.length?rows.map((x,i)=>{const e=decisionExplain(x,i+1),conf=e.confidence==="high"?"высокая":e.confidence==="low"?"низкая":"средняя";return `<div class="log-item"><div class="split"><div class="qtitle">#${i+1} ${escapeHtml(x.title)}</div><span class="tag">уверенность: ${conf}</span></div><div class="qmeta"><b>Источник:</b> ${escapeHtml(e.source)} • <b>Почему:</b> ${escapeHtml(e.why)}</div><div class="qmeta" style="margin-top:5px"><b>Факты:</b> ${e.evidence.map(escapeHtml).join(" • ")}</div><div class="qmeta" style="margin-top:5px"><b>Если отложить:</b> ${escapeHtml(e.consequence)}</div></div>`}).join(""):'<div class="empty">Нет решений для объяснения.</div>'}
  const pref=document.getElementById("decisionPreferences");if(pref){const rows=decisionPreferenceRows();pref.innerHTML=rows.length?rows.map(p=>`<div class="log-item"><div class="qtitle">${escapeHtml(p.id)}</div><div class="qmeta">${p.disabled?"Не предлагать":p.notBefore?`Отложено до ${p.notBefore}`:p.hiddenDate?`Скрыто ${p.hiddenDate}`:`Корректировка ${p.scoreDelta>0?"+":""}${p.scoreDelta||0}`}</div><button class="btn ghost small" style="margin-top:6px" onclick="decisionSetPreference('${decisionToken(p.id)}','reset')">Сбросить</button></div>`).join(""):'<div class="empty">Ручных корректировок нет.</div>'}}
