"use strict";
const fs=require("fs"),path=require("path"),assert=require("assert"),dist=path.join(__dirname,"dist"),read=n=>fs.readFileSync(path.join(dist,n),"utf8");
for(const f of ["index.html","core.js","bootstrap.js","integration-12.5.js","feedback-os.js","import-hub.js","ux-12.8.js","ux-12.8.css","training-os.js","work-growth.js","tennis-huawei.js","life-os.js","focus-os.js","people-os.js","capture2-os.js","manifest.webmanifest","share-hub.js","share-target-sw.js"]){assert.ok(fs.existsSync(path.join(dist,f)),`dist missing ${f}`)}
assert.ok(!fs.existsSync(path.join(dist,"personal-stabilization-os.js")),"legacy stabilization shim must not ship to production");
const sw=read("sw.js");assert.ok(sw.includes("life-rpg-13.1.1"),"generated Workbox SW does not contain the 13.1.1 cache namespace");
assert.ok(read("core.js").includes('APP_VERSION="13.1.1"'),"dist core release mismatch");assert.ok(read("manifest.webmanifest").includes("Life RPG 13.1.1"),"dist manifest release mismatch");
const boot=read("bootstrap.js");assert.ok(boot.includes('["ensureWork121Ui","renderWork121Panels"]'));assert.ok(boot.includes('["tennisHuaweiEnsureUi","tennisHuaweiRefresh"]'));assert.ok(boot.includes('["ensureShare131Ui","renderShare131"]'));assert.ok(boot.includes("lifeRuntimeInvoke"));
assert.ok(!read("work-growth.js").includes("renderWork=function"));assert.ok(!read("tennis-huawei.js").includes("MutationObserver"));assert.ok(read("life-os.js").includes("lifeOsRegisterCandidateProvider"));assert.ok(!read("training-os.js").includes("lifeOsRawCandidates=function"));assert.ok(!read("ux-12.8.js").includes("switchTab=function"));
assert.ok(sw.includes("share-target-sw.js"),"generated Workbox SW missing share target bridge");assert.ok(read("share-hub.js").includes("Android Acceptance 13.1.1"),"dist missing Android Acceptance layer");assert.ok(read("manifest.webmanifest").includes("share_target"));assert.ok(read("share-target-sw.js").includes('addEventListener("fetch"'));console.log("OK — production dist contains Life RPG 13.1.1 with Android Share Target bridge and clean Workbox namespace");
