"use strict";
process.env.TZ="Europe/Amsterdam";
const fs=require("node:fs"),vm=require("node:vm"),path=require("node:path"),assert=require("node:assert/strict");
const RealDate=Date,FIXED=new RealDate("2026-10-05T12:00:00+02:00").getTime();class FakeDate extends RealDate{constructor(...a){super(...(a.length?a:[FIXED]))}static now(){return FIXED}}
const ctx=vm.createContext({console,Date:FakeDate,Math,JSON,Intl,Number,Promise,setTimeout:()=>0,clearTimeout:()=>{},setInterval:()=>0,structuredClone:global.structuredClone,crypto:global.crypto,document:{getElementById:()=>null,querySelectorAll:()=>[],addEventListener:()=>{},body:{classList:{add(){},remove(){}}}},window:{addEventListener:()=>{},scrollTo:()=>{},location:{reload:()=>{}}},navigator:{},location:{reload:()=>{}},localStorage:{getItem:()=>null,setItem:()=>{},removeItem:()=>{}},Notification:function(){},confirm:()=>true,prompt:()=>"",Blob:global.Blob,URL:global.URL});ctx.window.window=ctx.window;ctx.window.document=ctx.document;for(const f of ["core.js","state.js","finance.js"])new vm.Script(fs.readFileSync(path.join(__dirname,f),"utf8"),{filename:f}).runInContext(ctx);const run=c=>new vm.Script(c).runInContext(ctx);
run(`S=deepClone(DEFAULT_STATE);S.settings.reportStart="2026-10-01";S.settings.campaignStart="2026-10-01";S.accounts=[{id:"main",name:"Main",active:true,verifiedBalance:null,verifiedAt:""}];S.settings.primaryAccountId="main";S.incomeLogs=[{id:"i",accountId:"main",amount:1000,dateKey:"2026-10-05",date:"2026-10-05T09:00:00+02:00"}];S.expenses=[];S.payments=[];S.cashAdjustments=[];S.fundTransfers=[];S.bankTransfers=[];S.assetTransfers=[{id:"a",accountId:"main",amount:400,direction:"toAsset",dateKey:"2026-10-05",date:"2026-10-05T10:00:00+02:00"}];`);assert.equal(run("legacyOperatingCashBalance()"),600,"asset transfer must leave legacy cash");
run(`S=deepClone(DEFAULT_STATE);S.accounts=[{id:"a",name:"A",active:true,verifiedBalance:1000,verifiedAt:"2026-10-01T00:00:00Z"}];S.settings.primaryAccountId="a";S.incomeLogs=[];S.expenses=[];S.bankTransfers=[];S.assetTransfers=[];S.fundTransfers=[];S.cashAdjustments=[];S.payments=[{id:"p",accountId:"a",amount:200,historicalOnly:true,localDate:"2026-10-02",date:"2026-10-02T12:00:00+02:00"}];`);assert.equal(run('accountBalanceById("a")'),800,"historical debt payment must still move cash after account anchor");
run(`S=deepClone(DEFAULT_STATE);S.accounts=[{id:"v",name:"Verified",active:true,verifiedBalance:500,verifiedAt:"2026-10-01T00:00:00Z"},{id:"u",name:"Unverified",active:true,verifiedBalance:null,verifiedAt:""}];S.settings.primaryAccountId="u";S.incomeLogs=[];S.expenses=[];S.payments=[];S.bankTransfers=[];S.assetTransfers=[];S.fundTransfers=[];S.cashAdjustments=[];`);assert.equal(run("defaultAccountId()"),"v");assert.deepEqual(Array.from(run("operationalAccounts().map(x=>x.id)")),["v"]);assert.ok(run('accountOptions().includes("не сверено")'));
run(`S=deepClone(DEFAULT_STATE);S.debts=[{id:"d",name:"Unknown",balance:1000,rate:0,rateKnown:false,active:true}];`);assert.equal(run("bestDebt()"),null);assert.equal(run("debtPriorityLabel()"),"нужно подтвердить ставки долгов");
assert.ok(run("renderDynamicBudget.toString().includes('monthLivingExpenses()')"),"dynamic budget must use living expenses only");
const worker=fs.readFileSync(path.join(__dirname,"ai-bridge-worker.mjs"),"utf8"),ops=fs.readFileSync(path.join(__dirname,"life-ops.js"),"utf8"),guide=fs.readFileSync(path.join(__dirname,"docs/guides/AI-BRIDGE-13.4-SETUP.txt"),"utf8");assert.ok(worker.includes('if(!required)return json({ok:false,error:"BRIDGE_ACCESS_TOKEN is not configured"}'));assert.ok(worker.includes("readJsonBodyLimited(request,MAX_BODY_BYTES)"));assert.ok(ops.includes("debtPriorityLabel"));assert.ok(guide.includes("Обязательно добавь Secret"));console.log("OK — final audit 2026-10-05 financial/security invariants");
