"use strict";

/* Life RPG 11.0.0 — Goals / Horizons OS
   Goal = desired outcome + horizon. Execution stays in Projects / Tasks. */

function goalStore(){if(!S.entities||typeof S.entities!=="object")S.entities={};if(!Array.isArray(S.entities.goals))S.entities.goals=[];return S.entities.goals}
function goalNormalize(x={}){return {id:String(x.id||uid()),title:String(x.title||"Цель").trim(),area:String(x.area||"Личное"),priority:clamp(Math.round(+x.priority||2),1,3),horizon:["90d","year","custom"].includes(x.horizon)?x.horizon:"90d",deadline:String(x.deadline||""),outcome:String(x.outcome||""),manualProgress:clamp(Math.round(+x.manualProgress||0),0,100),projectIds:Array.isArray(x.projectIds)?x.projectIds.map(String):[],status:["active","paused","done","archived"].includes(x.status)?x.status:"active",createdAt:String(x.createdAt||new Date().toISOString()),updatedAt:String(x.updatedAt||x.createdAt||new Date().toISOString()),completedAt:String(x.completedAt||""),archivedAt:String(x.archivedAt||""),xpAwarded:+x.xpAwarded||0}}
function goalAll(){const a=goalStore();for(let i=0;i<a.length;i++)a[i]=goalNormalize(a[i]);return a}
function goalActive(){return goalAll().filter(x=>x.status==="active")}
function goalAreaStat(area){return area==="Финансы"?"Финансы":area==="Работа"?"Карьера":area==="Теннис"?"Теннис":area==="Знания"?"Разум":"Дисциплина"}
function goalHorizonLabel(h){return h==="year"?"Год":h==="custom"?"Свой срок":"90 дней"}
function goalDefaultDeadline(h){const d=new Date();if(h==="90d")return localDateKey(addDays(d,90));if(h==="year"){let y=d.getFullYear(),x=new Date(y,11,31,12);if(x<d)x=new Date(y+1,11,31,12);return localDateKey(x)}return""}
function goalLinkedProjects(g){const ids=new Set(g.projectIds||[]);return (typeof projectStore==="function"?projectStore():[]).filter(p=>ids.has(String(p.id))&&p.status!=="archived")}
function goalProgress(g){const ps=goalLinkedProjects(g);if(!ps.length)return clamp(Math.round(+g.manualProgress||0),0,100);return clamp(Math.round(ps.reduce((s,p)=>s+(p.status==="done"?100:clamp(+p.progress||0,0,100)),0)/ps.length),0,100)}
function goalHealth(g){const today=parseLocal(localDateKey()),progress=goalProgress(g),created=new Date(g.createdAt||Date.now());let days=null,overdue=false,due14=false,expected=null,behind=false;if(validDateKey(g.deadline)){const deadline=parseLocal(g.deadline);days=Math.round((deadline-today)/86400000);overdue=days<0;due14=days>=0&&days<=14;const total=Math.max(1,Math.round((deadline-created)/86400000)),elapsed=Math.max(0,Math.round((today-created)/86400000));if(total>=14){expected=clamp(Math.round(elapsed/total*100),0,100);behind=expected-progress>=20}}return {progress,days,overdue,due14,expected,behind,atRisk:overdue||(due14&&progress<80)||behind}}
function goalSummary(){const a=goalActive(),hs=a.map(goalHealth),doneMonth=goalAll().filter(x=>x.status==="done"&&String(x.completedAt||"").slice(0,7)===localMonthKey()).length;return {active:a.length,atRisk:hs.filter(x=>x.atRisk).length,overdue:hs.filter(x=>x.overdue).length,avg:a.length?Math.round(hs.reduce((s,x)=>s+x.progress,0)/a.length):0,doneMonth}}
function goalDecisionEngine(){const out=[];for(const g of goalActive()){const h=goalHealth(g),boost=g.priority===1?20:g.priority===2?10:0,base={id:`goal:${g.id}`,goalId:g.id,area:g.area,route:"goals",minutes:15,hard:false};if(h.overdue&&h.progress<100)out.push({...base,kind:"goal-overdue",title:`Просрочена цель: ${g.title}`,meta:`Прогресс ${h.progress}% • срок ${fmtDate(parseLocal(g.deadline))}`,score:118+boost,hard:g.priority===1});else if(h.due14&&h.progress<80)out.push({...base,kind:"goal-deadline",title:`Цель близко к сроку: ${g.title}`,meta:`Осталось ${h.days} дн. • прогресс ${h.progress}%`,score:84+boost});else if(h.behind)out.push({...base,kind:"goal-pace",title:`Цель отстаёт от темпа: ${g.title}`,meta:`Прогресс ${h.progress}% • ориентир по времени ${h.expected}%`,score:68+boost});else if(!goalLinkedProjects(g).length&&h.progress<100)out.push({...base,kind:"goal-structure",title:`Определи исполнение цели: ${g.title}`,meta:"Свяжи цель с проектом или обнови ручной прогресс.",score:40+boost})}return out.sort((a,b)=>b.score-a.score).slice(0,12)}
function goalCalendarEvents(startKey,endKey){const out=[];for(const g of goalActive()){if(!validDateKey(g.deadline)||g.deadline<startKey||g.deadline>endKey)continue;const h=goalHealth(g);out.push({id:`cal:goal:${g.id}:${g.deadline}`,dateKey:g.deadline,source:"goal",kind:"goal-deadline",area:g.area,title:`Цель: ${g.title}`,meta:`${h.progress}% • ${goalHorizonLabel(g.horizon)}`,minutes:10,hard:h.overdue&&g.priority===1,priority:g.priority,refId:g.id,route:"goals",manual:false})}return out}
function goalProjectOptions(selected=[]){const set=new Set(selected.map(String));return (typeof projectStore==="function"?projectStore():[]).filter(p=>!["archived"].includes(p.status)).map(p=>`<label class="toggle-line"><input type="checkbox" data-goal-project value="${escapeHtml(p.id)}" ${set.has(String(p.id))?"checked":""}><span>${escapeHtml(p.title)} • ${p.status==="done"?100:p.progress||0}%</span></label>`).join("")||'<div class="empty">Проектов пока нет.</div>'}
function goalCreate(data={}){const g=goalNormalize({...data,id:uid(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});goalStore().push(g);return g}
async function saveGoalForm(){const id=String(document.getElementById("goalEditId")?.value||""),title=String(document.getElementById("goalTitle")?.value||"").trim();if(!title){toast("Укажи цель");return}const horizon=String(document.getElementById("goalHorizon")?.value||"90d"),deadline=String(document.getElementById("goalDeadline")?.value||"")||goalDefaultDeadline(horizon),projectIds=[...document.querySelectorAll?.('#goalProjectLinks input[data-goal-project]:checked')||[]].map(x=>x.value),data={title,area:String(document.getElementById("goalArea")?.value||"Личное"),priority:clamp(Math.round(+document.getElementById("goalPriority")?.value||2),1,3),horizon,deadline,outcome:String(document.getElementById("goalOutcome")?.value||"").trim(),manualProgress:clamp(Math.round(+document.getElementById("goalProgress")?.value||0),0,100),projectIds,updatedAt:new Date().toISOString()};const old=id?goalAll().find(x=>x.id===id):null;if(old)Object.assign(old,data);else goalCreate(data);audit(old?"Цель обновлена":"Цель создана","system",title);clearGoalForm();await save(old?"Цель обновлена":"Цель создана")}
function clearGoalForm(){for(const id of ["goalEditId","goalTitle","goalDeadline","goalOutcome"]){const el=document.getElementById(id);if(el)el.value=""}if(document.getElementById("goalArea"))document.getElementById("goalArea").value="Работа";if(document.getElementById("goalPriority"))document.getElementById("goalPriority").value="2";if(document.getElementById("goalHorizon"))document.getElementById("goalHorizon").value="90d";if(document.getElementById("goalProgress"))document.getElementById("goalProgress").value="0";const links=document.getElementById("goalProjectLinks");if(links)links.innerHTML=goalProjectOptions([]);const card=document.getElementById("goalEditorCard");if(card)card.hidden=true}
function editGoal(id){const g=goalAll().find(x=>x.id===id);if(!g)return;const vals={goalEditId:g.id,goalTitle:g.title,goalArea:g.area,goalPriority:g.priority,goalHorizon:g.horizon,goalDeadline:g.deadline,goalOutcome:g.outcome,goalProgress:g.manualProgress};for(const [k,v] of Object.entries(vals)){const el=document.getElementById(k);if(el)el.value=String(v??"")}const links=document.getElementById("goalProjectLinks");if(links)links.innerHTML=goalProjectOptions(g.projectIds);const card=document.getElementById("goalEditorCard");if(card)card.hidden=false}
async function setGoalStatus(id,status){const g=goalAll().find(x=>x.id===id);if(!g||!["active","paused","done","archived"].includes(status))return;g.status=status;g.updatedAt=new Date().toISOString();if(status==="done"){g.completedAt=g.updatedAt;g.manualProgress=100;if(!g.xpAwarded){const xp=g.priority===1?300:g.priority===2?220:150;g.xpAwarded=xp;addXp(xp,goalAreaStat(g.area),"Цель достигнута",`goal:${g.id}`,"result",localDateKey())}}if(status==="archived")g.archivedAt=g.updatedAt;audit(status==="done"?"Цель достигнута":"Статус цели изменён","system",g.title);await save(status==="done"?"Цель достигнута":"Статус цели обновлён")}
function ensureGoalsOsUi(){if(document.getElementById("goalsOsCommand"))return;const grid=document.querySelector?.("#more .grid");if(!grid)return;const anchor=document.getElementById("projectsOsCommand")?.closest?.(".card")||grid.firstElementChild;if(!anchor||typeof anchor.insertAdjacentHTML!=="function")return;anchor.insertAdjacentHTML("beforebegin",`<div data-ux7-view="overview" class="card ux7-card span-12"><div class="split"><div><div class="eyebrow">Goals / Horizons OS</div><div class="section-title">Направление на 90 дней и год</div></div><button class="btn secondary small" onclick="document.getElementById('goalProjectLinks').innerHTML=goalProjectOptions([]);document.getElementById('goalEditorCard').hidden=false;document.getElementById('goalTitle').focus()">+ Цель</button></div><div class="muted" style="margin-top:6px">Цель хранит результат и горизонт. Исполнение остаётся в Projects / Tasks; при связке с проектами прогресс считается автоматически.</div><div id="goalsOsCommand" style="margin-top:10px"></div><div id="goalsOsList" style="margin-top:10px"></div></div><div data-ux7-view="overview" class="card ux7-card span-12" id="goalEditorCard" hidden><div class="title">Редактор цели</div><input id="goalEditId" type="hidden"><div class="formgrid" style="margin-top:10px"><div class="field"><label>Цель</label><input id="goalTitle"></div><div class="field"><label>Область</label><select id="goalArea"><option>Работа</option><option>Финансы</option><option>Теннис</option><option>Знания</option><option>Личное</option><option>Система</option></select></div><div class="field"><label>Горизонт</label><select id="goalHorizon"><option value="90d">90 дней</option><option value="year">Год</option><option value="custom">Свой срок</option></select></div><div class="field"><label>Приоритет</label><select id="goalPriority"><option value="1">Высокий</option><option value="2" selected>Средний</option><option value="3">Низкий</option></select></div><div class="field"><label>Дедлайн</label><input id="goalDeadline" type="date"></div><div class="field"><label>Ручной прогресс, %</label><input id="goalProgress" type="number" min="0" max="100" value="0"></div></div><div class="field" style="margin-top:8px"><label>Как выглядит достигнутый результат</label><input id="goalOutcome"></div><div class="title" style="margin-top:12px">Связанные проекты</div><div id="goalProjectLinks" style="margin-top:7px"></div><div class="split" style="margin-top:10px"><button class="btn" onclick="saveGoalForm()">Сохранить</button><button class="btn ghost" onclick="clearGoalForm()">Отмена</button></div></div>`)}
function renderGoalsOs(){const box=document.getElementById("goalsOsCommand"),list=document.getElementById("goalsOsList");if(!box||!list)return;const q=goalSummary(),rows=goalActive().slice().sort((a,b)=>{const ha=goalHealth(a),hb=goalHealth(b);return (hb.atRisk-ha.atRisk)||(a.priority-b.priority)||((ha.days??9999)-(hb.days??9999))});box.innerHTML=`<div class="report-grid"><div class="report-item"><div class="smallcaps">Активных</div><b>${q.active}</b></div><div class="report-item"><div class="smallcaps">Под риском</div><b class="${q.atRisk?"income-bad":""}">${q.atRisk}</b></div><div class="report-item"><div class="smallcaps">Просрочено</div><b>${q.overdue}</b></div><div class="report-item"><div class="smallcaps">Средний прогресс</div><b>${q.avg}%</b></div><div class="report-item"><div class="smallcaps">Достигнуто в месяце</div><b>${q.doneMonth}</b></div></div>`;list.innerHTML=rows.length?rows.map(g=>{const h=goalHealth(g),cls=h.overdue?"bad":h.atRisk?"warn":"";return `<div class="log-item"><div class="split"><div><span class="tag ${cls}">${escapeHtml(g.area)}</span><div class="qtitle" style="margin-top:6px">${escapeHtml(g.title)}</div><div class="qmeta">${goalHorizonLabel(g.horizon)}${g.deadline?` • ${fmtDate(parseLocal(g.deadline))}`:""} • ${h.progress}%${goalLinkedProjects(g).length?` • проектов ${goalLinkedProjects(g).length}`:""}</div>${g.outcome?`<div class="qmeta">Результат: ${escapeHtml(g.outcome)}</div>`:""}${h.behind?`<div class="status" style="margin-top:6px">Темп по времени ~${h.expected}%, фактический прогресс ${h.progress}%.</div>`:""}</div><div class="split"><button class="btn ghost small" onclick="editGoal('${g.id}')">Изм.</button><button class="btn secondary small" onclick="setGoalStatus('${g.id}','done')">✓</button><button class="btn ghost small" onclick="setGoalStatus('${g.id}','paused')">Пауза</button></div></div></div>`}).join(""):'<div class="empty">Активных целей пока нет.</div>'}
