"use strict";

/* Life RPG 10.1.0 — Inbox / Capture OS */

function inboxStore(){if(!S.entities||typeof S.entities!=="object")S.entities={};if(!Array.isArray(S.entities.inbox))S.entities.inbox=[];return S.entities.inbox}
function knowledgeNoteStore(){if(!Array.isArray(S.settings.knowledgeNotes))S.settings.knowledgeNotes=[];return S.settings.knowledgeNotes}
function inboxInferArea(text){text=String(text||"").toLowerCase();if(/оплат|деньг|руб|₽|карт|кредит|долг|банк/.test(text))return"Финансы";if(/клиент|сделк|звон|коммер|счет|счёт|crm|работ/.test(text))return"Работа";if(/теннис|тренир|турнир|подач|ракет/.test(text))return"Теннис";if(/книг|чита|тезис|идея|знани|изуч/.test(text))return"Знания";return"Личное"}
function inboxInferDate(text){text=String(text||"").toLowerCase();if(/сегодня/.test(text))return localDateKey();if(/завтра/.test(text))return localDateKey(addDays(new Date(),1));const m=text.match(/\b(\d{1,2})[.\/-](\d{1,2})(?:[.\/-](\d{2,4}))?\b/);if(m){const y=m[3]?((+m[3]<100?2000:0)+ +m[3]):new Date().getFullYear(),d=String(+m[1]).padStart(2,"0"),mo=String(+m[2]).padStart(2,"0"),k=`${y}-${mo}-${d}`;if(validDateKey(k))return k}return""}
function inboxNormalize(x={}){const text=String(x.text||"").trim();return {id:String(x.id||uid()),text,status:["open","processed","discarded"].includes(x.status)?x.status:"open",area:String(x.area||inboxInferArea(text)),dateKey:String(x.dateKey||inboxInferDate(text)),createdAt:String(x.createdAt||new Date().toISOString()),processedAt:String(x.processedAt||""),route:String(x.route||""),resultId:String(x.resultId||"")}}
function inboxAll(){const a=inboxStore();for(let i=0;i<a.length;i++){const current=a[i],normalized=inboxNormalize(current);if(current&&typeof current==="object"&&!Array.isArray(current))Object.assign(current,normalized);else a[i]=normalized}return a}
function inboxOpen(){return inboxAll().filter(x=>x.status==="open")}
function inboxCapture(text){text=String(text||"").trim();if(!text)return null;const x=inboxNormalize({id:uid(),text,status:"open",createdAt:new Date().toISOString()});inboxStore().unshift(x);return x}
async function captureInbox(){const el=document.getElementById("inboxCaptureInput"),x=inboxCapture(el?.value);if(!x){toast("Напиши мысль или обязательство");return}if(el)el.value="";audit("Inbox capture","system",x.text);await save("Добавлено во входящие")}
function inboxAgeDays(x){const t=Date.parse(x.createdAt||"");return Number.isFinite(t)?Math.floor((Date.now()-t)/86400000):0}
function inboxDecisionEngine(){const open=inboxOpen(),old=open.filter(x=>inboxAgeDays(x)>=2),veryOld=open.filter(x=>inboxAgeDays(x)>=5);if(!old.length)return[];return [{id:"inbox:backlog",kind:"inbox-backlog",area:"Система",title:"Разобрать входящие",meta:`Необработано ${open.length} • старше 2 дней ${old.length}${veryOld.length?` • старше 5 дней ${veryOld.length}`:""}`,score:veryOld.length?76:open.length>=5?66:54,hard:false,route:"inbox",minutes:Math.min(30,Math.max(10,open.length*3))}]}
function markInboxProcessed(x,route,resultId=""){x.status="processed";x.processedAt=new Date().toISOString();x.route=route;x.resultId=resultId}
async function inboxToTask(id){const x=inboxAll().find(z=>z.id===id);if(!x)return;const t=taskCreate({title:x.text,area:x.area,priority:2,dueDate:x.dateKey,minutes:30,note:"Из Inbox"});markInboxProcessed(x,"task",t.id);await save("Inbox → задача")}
async function inboxToCalendar(id){const x=inboxAll().find(z=>z.id===id);if(!x)return;const made=addCalendarPlan({title:x.text,dateKey:x.dateKey||localDateKey(),type:x.area==="Теннис"?"Тренировка":x.area==="Работа"?"Работа":x.area==="Финансы"?"Финансы":x.area==="Знания"?"Знания":"Личное",minutes:x.area==="Теннис"?90:30,priority:2,repeatWeeks:1});markInboxProcessed(x,"calendar",made[0]?.id||"");await save("Inbox → календарь")}
async function inboxToProject(id){const x=inboxAll().find(z=>z.id===id);if(!x)return;const p={id:uid(),title:x.text,area:x.area,priority:2,deadline:x.dateKey||"",outcome:"",progress:0,nextStep:"",nextDate:"",status:"active",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),completedAt:"",xpAwarded:0};projectStore().push(p);markInboxProcessed(x,"project",p.id);await save("Inbox → проект")}
async function inboxToKnowledge(id){const x=inboxAll().find(z=>z.id===id);if(!x)return;const n={id:uid(),text:x.text,dateKey:x.dateKey||localDateKey(),createdAt:new Date().toISOString(),source:"inbox"};knowledgeNoteStore().unshift(n);markInboxProcessed(x,"knowledge",n.id);await save("Inbox → знание")}
async function inboxToCrm(id){const x=inboxAll().find(z=>z.id===id);if(!x)return;const sel=document.getElementById(`inboxCrm_${id}`),deal=(S.crmDeals||[]).find(d=>d.id===sel?.value);if(!deal){toast("Выбери сделку CRM");return}deal.nextStep=x.text;deal.nextDate=x.dateKey||localDateKey();deal.updatedAt=new Date().toISOString();markInboxProcessed(x,"crm",deal.id);audit("Inbox → CRM","work",`${deal.name}: ${x.text}`);await save("Следующий шаг CRM обновлён")}
async function discardInbox(id){const x=inboxAll().find(z=>z.id===id);if(!x)return;x.status="discarded";x.processedAt=new Date().toISOString();await save("Входящее закрыто")}
function ensureInboxOsUi(){}
function renderInboxOs(){}

const renderKnowledgeBaseInboxBase=renderKnowledgeBase;
renderKnowledgeBase=function(){renderKnowledgeBaseInboxBase();const box=document.getElementById("knowledgeBase");if(!box)return;const q=String(document.getElementById("knowledgeSearch")?.value||"").toLowerCase(),notes=knowledgeNoteStore().filter(x=>!q||String(x.text||"").toLowerCase().includes(q)).slice(0,40);if(notes.length)box.insertAdjacentHTML("beforeend",'<div class="title" style="margin-top:12px">Быстрые заметки</div>'+notes.map(x=>`<div class="log-item"><div class="qtitle">Inbox • ${fmtDate(parseLocal(x.dateKey||localDateKey()))}</div><div class="qmeta">${escapeHtml(x.text)}</div></div>`).join(""))};
