"use strict";

/* Life RPG 10.2.0 — Insights OS
   Only descriptive associations with minimum sample sizes. Never labels correlation as causation. */

function insightPearson(xs,ys){const n=Math.min(xs.length,ys.length);if(n<3)return null;const ax=xs.slice(0,n).reduce((a,b)=>a+b,0)/n,ay=ys.slice(0,n).reduce((a,b)=>a+b,0)/n;let num=0,dx=0,dy=0;for(let i=0;i<n;i++){const x=xs[i]-ax,y=ys[i]-ay;num+=x*y;dx+=x*x;dy+=y*y}if(dx<=0||dy<=0)return null;return num/Math.sqrt(dx*dy)}
function insightStrength(r){const a=Math.abs(r);return a>=.7?"сильная":a>=.45?"умеренная":a>=.25?"слабая":"очень слабая"}
function insightWeeksFromWork(){const m=new Map();for(const x of S.workLogs||[]){if(!validDateKey(x.date))continue;const k=isoWeekKey(parseLocal(x.date)),z=m.get(k)||{week:k,activity:0,sales:0,days:0};z.activity+=(+x.contacts||0)+(+x.followups||0)+(+x.lpr||0)*2+(+x.meetings||0)*3+(+x.proposals||0)*4;z.sales+=+x.sales||0;z.days++;m.set(k,z)}return [...m.values()].sort((a,b)=>a.week.localeCompare(b.week))}
function insightWorkAssociation(){const rows=insightWeeksFromWork().filter(x=>x.days>0);if(rows.length<6)return {ready:false,title:"Активность ↔ продажи",need:`Нужно минимум 6 недель рабочих данных; сейчас ${rows.length}.`};const r=insightPearson(rows.map(x=>x.activity),rows.map(x=>x.sales));if(r==null)return {ready:false,title:"Активность ↔ продажи",need:"Пока недостаточно вариативности активности или продаж."};return {ready:true,title:"Активность ↔ продажи",value:`r=${r.toFixed(2)} • ${insightStrength(r)} связь`,meta:`${rows.length} недель. Индекс активности = контакты + follow-up + 2×ЛПР + 3×встречи + 4×КП. Это наблюдаемая корреляция, не доказательство причинности.`}}
function insightWipAssociation(){const rows=(typeof reviewStore==="function"?reviewStore():[]).filter(x=>x.kind==="week"&&x.snapshot?.projects&&Number.isFinite(+x.snapshot?.lifeScore));if(rows.length<4)return {ready:false,title:"WIP проектов ↔ Life Score",need:`Нужно минимум 4 сохранённых недельных обзора; сейчас ${rows.length}.`};const r=insightPearson(rows.map(x=>+x.snapshot.projects.active||0),rows.map(x=>+x.snapshot.lifeScore||0));if(r==null)return {ready:false,title:"WIP проектов ↔ Life Score",need:"Пока нет достаточной вариативности числа проектов или Life Score."};return {ready:true,title:"WIP проектов ↔ Life Score",value:`r=${r.toFixed(2)} • ${insightStrength(r)} связь`,meta:`${rows.length} недельных снимков. Отрицательный r означает, что недели с большим числом активных проектов совпадали с более низким Life Score. Не причинный вывод.`}}
function insightCalendarReading(){if(typeof calendarManualEvents!=="function")return {ready:false,title:"Календарная нагрузка ↔ чтение",need:"Calendar OS недоступен."};const today=new Date(),xs=[],ys=[];let sampled=0;for(let i=1;i<=28;i++){const k=localDateKey(addDays(today,-i)),mins=calendarManualEvents().filter(e=>e.dateKey===k&&e.status!=="cancelled").reduce((s,e)=>s+(+e.minutes||0),0),read=(S.readingLogs||[]).filter(x=>x.dateKey===k).reduce((s,x)=>s+(+x.minutes||0),0);if(mins>0||read>0){xs.push(mins);ys.push(read);sampled++}}if(sampled<10)return {ready:false,title:"Календарная нагрузка ↔ чтение",need:`Нужно минимум 10 дней с календарной нагрузкой или чтением; сейчас ${sampled}.`};const r=insightPearson(xs,ys);if(r==null)return {ready:false,title:"Календарная нагрузка ↔ чтение",need:"Пока недостаточно вариативности."};return {ready:true,title:"Календарная нагрузка ↔ чтение",value:`r=${r.toFixed(2)} • ${insightStrength(r)} связь`,meta:`${sampled} дней за последние 28. Сравниваются минуты плановых событий и минуты чтения; связь не доказывает влияние одного на другое.`}}
function insightDebtTrend(){const rows=(typeof reviewStore==="function"?reviewStore():[]).filter(x=>x.kind==="month"&&Number.isFinite(+x.snapshot?.finance?.debt)).sort((a,b)=>String(a.periodKey).localeCompare(String(b.periodKey)));if(rows.length<2)return {ready:false,title:"Тренд долга",need:`Нужно 2 месячных обзора; сейчас ${rows.length}.`};const first=+rows[0].snapshot.finance.debt,last=+rows.at(-1).snapshot.finance.debt,delta=last-first;return {ready:true,title:"Тренд долга",value:`${delta>0?"+":""}${compactRub(delta)}`,meta:`От ${compactRub(first)} до ${compactRub(last)} за ${rows.length} сохранённых месячных снимков. Это фактическое изменение между обзорами.`}}
function insightTaskFlow(){if(typeof taskAll!=="function")return {ready:false,title:"Поток задач",need:"Tasks OS недоступен."};const cutoff=Date.now()-28*86400000,rows=taskAll(),created=rows.filter(x=>Date.parse(x.createdAt||0)>=cutoff),done=rows.filter(x=>x.status==="done"&&Date.parse(x.completedAt||0)>=cutoff),over=taskActive().filter(x=>taskHealth(x).overdue).length;if(created.length<5)return {ready:false,title:"Поток задач",need:`Нужно минимум 5 созданных задач за 28 дней; сейчас ${created.length}.`};const ratio=Math.round(done.length/created.length*100);return {ready:true,title:"Поток задач за 28 дней",value:`${done.length}/${created.length} • ${ratio}%`,meta:`Создано ${created.length}, завершено ${done.length}, сейчас просрочено ${over}. Это операционный факт, а не оценка эффективности.`}}
function insightRoutineConsistency(){if(typeof routine28Stats!=="function")return {ready:false,title:"Стабильность рутин",need:"Routines OS недоступен."};const r=routine28Stats();if(r.scheduled<10)return {ready:false,title:"Стабильность рутин",need:`Нужно минимум 10 запланированных повторений; сейчас ${r.scheduled}.`};return {ready:true,title:"Стабильность рутин за 28 дней",value:`${r.rate}%`,meta:`Выполнено ${r.done} из ${r.scheduled} запланированных повторений. Пропуски не переносятся как долг.`}}
function insightGoalPortfolio(){if(typeof goalSummary!=="function")return {ready:false,title:"Портфель целей",need:"Goals OS недоступен."};const q=goalSummary();if(!q.active)return {ready:false,title:"Портфель целей",need:"Добавь хотя бы одну активную цель."};const linked=goalActive().filter(g=>goalLinkedProjects(g).length>0).length;return {ready:true,title:"Портфель целей",value:`${q.avg}% среднего прогресса`,meta:`Активных ${q.active} • под риском ${q.atRisk} • связаны с проектами ${linked}/${q.active}. Это текущий снимок портфеля.`}}
function insightRoutineLifeAssociation(){const rows=(typeof reviewStore==="function"?reviewStore():[]).filter(x=>x.kind==="week"&&Number.isFinite(+x.snapshot?.routines?.rate)&&Number.isFinite(+x.snapshot?.lifeScore));if(rows.length<4)return {ready:false,title:"Рутины ↔ Life Score",need:`Нужно минимум 4 недельных обзора с данными Routines OS; сейчас ${rows.length}.`};const r=insightPearson(rows.map(x=>+x.snapshot.routines.rate),rows.map(x=>+x.snapshot.lifeScore));if(r==null)return {ready:false,title:"Рутины ↔ Life Score",need:"Недостаточно вариативности показателей."};return {ready:true,title:"Рутины ↔ Life Score",value:`r=${r.toFixed(2)} • ${insightStrength(r)} связь`,meta:`${rows.length} недельных снимков. Корреляция описывает совместное изменение и не доказывает причинность.`}}
function insightsData(){return [insightGoalPortfolio(),insightTaskFlow(),insightRoutineConsistency(),insightWorkAssociation(),insightWipAssociation(),insightCalendarReading(),insightRoutineLifeAssociation(),insightDebtTrend()]}
function ensureInsightsOsUi(){if(document.getElementById("insightsOsCommand"))return;const grid=document.querySelector?.("#more .grid");if(!grid)return;const anchor=document.getElementById("rulesOsCommand")?.closest?.(".card")||grid.lastElementChild;if(!anchor||typeof anchor.insertAdjacentHTML!=="function")return;anchor.insertAdjacentHTML("afterend",`<div data-ux7-view="overview" class="card ux7-card span-6"><div class="eyebrow">Insights OS</div><div class="section-title">Факты, тренды и связи в собственных данных</div><div class="muted" style="margin-top:6px">Показываются только расчёты с минимальной выборкой. Корреляции не трактуются как причинность.</div><div id="insightsOsCommand" style="margin-top:10px"></div></div>`)}
function renderInsightsOs(){const box=document.getElementById("insightsOsCommand");if(!box)return;box.innerHTML=insightsData().map(x=>`<div class="log-item"><div class="qtitle">${escapeHtml(x.title)}</div>${x.ready?`<div class="metric" style="font-size:18px;margin-top:4px">${escapeHtml(x.value)}</div><div class="qmeta">${escapeHtml(x.meta)}</div>`:`<div class="qmeta">${escapeHtml(x.need)}</div>`}</div>`).join("")}
