import { test, expect } from "@playwright/test";
async function boot(page){const errors=[];page.on("pageerror",e=>errors.push(String(e)));await page.goto("/",{waitUntil:"domcontentloaded"});await expect(page.locator("html")).not.toHaveClass(/life-rpg-booting/);await expect(page.locator("#versionStatus")).toContainText("13.2.1");await page.evaluate(()=>{switchTab("today");ux7SetView("today","focus",false)});return errors}

test("Calibration 13.2.1 enforces Top-3 with reserve and explains why-not",async({page})=>{const errors=await boot(page);await expect(page.locator("#intelligence1321Control")).toBeVisible();await page.evaluate(()=>{lifeOsRegisterCandidateProvider("e2e-calibration",()=>[
 {id:"e2e-fin",area:"Финансы",kind:"payment",title:"E2E finance",score:110,hard:false,minutes:10,source:"E2E"},
 {id:"e2e-work",area:"Работа",kind:"next",title:"E2E work",score:100,hard:false,minutes:20,source:"E2E"},
 {id:"e2e-body",area:"Тело",kind:"recovery",title:"E2E body",score:90,hard:false,minutes:20,source:"E2E"},
 {id:"e2e-knowledge",area:"Знания",kind:"read",title:"E2E knowledge",score:80,hard:false,minutes:20,source:"E2E"}
]);render()});await expect.poll(()=>page.evaluate(()=>lifeOsDailyPlan().plan.length)).toBe(3);expect(await page.evaluate(()=>lifeOsDailyPlan().reserve.length)).toBeGreaterThan(0);const card=page.locator("#intelligence1321Control").locator("xpath=ancestor::div[contains(@class,'card')]");await card.locator("summary",{hasText:"Почему не Top-3?"}).click();await expect(page.locator("#intelligence1321WhyNot")).toContainText("Top-3");expect(errors).toEqual([])});

test("Calibration 13.2.1 safe reset preserves journal",async({page})=>{const errors=await boot(page);await page.evaluate(()=>{const st=intelligence132Store();st.journal=[{id:"e2e-j",type:"exposure",dateKey:localDateKey(),candidateId:"x",signature:"work|next",area:"Работа",score:80,confidenceScore:80,outcome:"helped",outcomeAt:new Date().toISOString()}];st.candidateState={x:{score:80}};intelligence1321Store().overrides=[{signature:"work|next",at:new Date().toISOString()}];render()});page.on("dialog",d=>d.accept());const before=await page.evaluate(()=>intelligence132Store().journal.length);await page.getByRole("button",{name:"Сбросить обучение"}).click();await expect.poll(()=>page.evaluate(()=>Boolean(intelligence1321Store().learningResetAt))).toBe(true);expect(await page.evaluate(()=>intelligence132Store().journal.length)).toBe(before);expect(await page.evaluate(()=>Object.keys(intelligence132Store().candidateState).length)).toBe(0);expect(await page.evaluate(()=>intelligence1321Store().overrides.length)).toBe(0);expect(errors).toEqual([])});
