"use strict";

/* Life RPG 8.2.0 — Reading queue, imports and knowledge */

function readingDaysThisWeek(){const wk=isoWeekKey();return new Set(S.readingLogs.filter(x=>isoWeekKey(parseLocal(x.dateKey))===wk).map(x=>x.dateKey)).size}

function currentBook(){return S.books.find(b=>b.status==="reading")||null}

function readingQueueSorted(){return (S.books||[]).filter(b=>b.status==="queued").slice().sort((a,b)=>(+a.readingOrder||999999)-(+b.readingOrder||999999)||String(a.created||"").localeCompare(String(b.created||""))||String(a.title||"").localeCompare(String(b.title||""),"ru"))}

function nextQueuedBook(){return readingQueueSorted()[0]||null}

function nextReadingOrder(){return (S.books||[]).reduce((m,b)=>Math.max(m,+b.readingOrder||0),0)+1}

function normalizeBookText(s){return String(s||"").normalize("NFKC").toLowerCase().replace(/[«»„“”"'’]/g,"").replace(/\s+/g," ").trim()}

function bookIdentityKey(author,title){return `${normalizeBookText(author)}|${normalizeBookText(title)}`}

function normalizeReadingListPackage(obj){if(!obj||obj.format!=="life-rpg-reading-list-v1"||!Array.isArray(obj.books))throw new Error("Неподдерживаемый формат списка чтения");const books=obj.books.map((x,i)=>({order:Math.max(1,Math.round(+x.order||i+1)),author:String(x.author||"").trim(),title:String(x.title||"").trim(),totalPages:Math.max(0,Math.round(+x.totalPages||0))})).filter(x=>x.title).sort((a,b)=>a.order-b.order);if(!books.length)throw new Error("В списке нет книг");return {title:String(obj.title||"Список чтения").trim(),books}}

function mergeReadingListPackage(obj){const pkg=normalizeReadingListPackage(obj),existing=new Set((S.books||[]).map(b=>bookIdentityKey(b.author,b.title))),added=[],skipped=[];let order=nextReadingOrder();for(const item of pkg.books){const key=bookIdentityKey(item.author,item.title);if(existing.has(key)){skipped.push(item);continue}const b={id:uid(),title:item.title,author:item.author,totalPages:item.totalPages,currentPage:0,status:"queued",readingOrder:order++,created:localDateKey(),notes:"",source:"reading-list-import"};S.books.push(b);existing.add(key);added.push(b)}return {title:pkg.title,added,skipped,total:pkg.books.length}}

async function importReadingListFile(file){if(!file)return;try{let obj=JSON.parse(await file.text());const checked=window.LifePlatform?.validateReadingList?.(obj);if(checked&&!checked.ok)throw new Error(checked.error||"Список чтения не прошёл проверку");obj=checked?.data||obj;await createPreActionSnapshot("Перед импортом списка чтения");const r=mergeReadingListPackage(obj);audit("Импорт списка чтения","knowledge",`${r.added.length} добавлено • ${r.skipped.length} пропущено`);await persist();render();const box=$("readingListImportStatus");if(box)box.innerHTML=`<b>Импортировано: ${r.added.length}</b> • уже было: ${r.skipped.length} • всего в файле: ${r.total}`;toast(r.added.length?`Добавлено книг: ${r.added.length}`:"Новых книг в списке нет")}catch(e){const box=$("readingListImportStatus");if(box)box.textContent=`Ошибка импорта: ${e.message||e}`;toast("Не удалось импортировать список чтения")}finally{const input=$("readingListImport");if(input)input.value=""}}

async function addBook(){const title=$("bookTitle").value.trim(),pages=+$("bookPages").value||0;if(!title||pages<=0){toast("Укажи название и страницы");return}const queued=!!currentBook(),book={id:uid(),title,author:$("bookAuthor").value.trim(),totalPages:pages,currentPage:0,status:queued?"queued":"reading",readingOrder:queued?nextReadingOrder():0,created:localDateKey(),notes:""};S.books.push(book);$("bookTitle").value=$("bookAuthor").value=$("bookPages").value="";closeModal("bookModal");await save(queued?"Книга добавлена в очередь":"Книга добавлена и начата")}

async function startQueuedBook(id){const b=S.books.find(x=>x.id===id);if(!b||b.status!=="queued")return;const active=currentBook();if(active&&active.id!==id){toast(`Сначала заверши текущую книгу: ${active.title}`);return}let pages=Math.max(0,+b.totalPages||0);if(!pages){const raw=prompt(`Сколько страниц в твоём издании «${b.title}»?`,"");if(raw==null)return;pages=Math.max(0,Math.round(+raw||0))}if(pages<=0){toast("Укажи количество страниц");return}b.totalPages=pages;b.currentPage=Math.max(0,+b.currentPage||0);b.status="reading";b.started=localDateKey();audit("Книга начата","knowledge",b.title);await save(`Начата книга: ${b.title}`)}

function readingBaseXpOnDate(dateKey,excludeId=""){return Math.min(40,(S.readingLogs||[]).filter(x=>x.dateKey===dateKey&&x.id!==excludeId).reduce((s,x)=>s+Math.min(40,Math.max(0,x.baseXpAward==null?Math.min(40,+x.xpAward||0):+x.baseXpAward||0)),0))}

function recomputeBookProgress(bookId){const b=S.books.find(x=>x.id===bookId);if(!b)return;const pages=(S.readingLogs||[]).filter(x=>x.bookId===bookId).reduce((s,x)=>s+Math.max(0,+x.pages||0),0);b.currentPage=Math.min(Math.max(0,+b.totalPages||0),pages);if(b.currentPage>=b.totalPages&&b.totalPages>0){b.status="done";const last=(S.readingLogs||[]).filter(x=>x.bookId===bookId).map(x=>x.dateKey).sort().at(-1);b.completed=last||b.completed||localDateKey()}else if(b.status!=="queued"){b.status="reading";delete b.completed}}

async function addReading(){const id=$("readBook").value,dateKey=$("readDate")?.value||localDateKey();if(!validActivityDate(dateKey)){toast("Чтение можно добавить только за сегодня или прошедшую дату");return}const min=Math.max(0,+$("readMinutes").value||0),pages=Math.max(0,+$("readPages").value||0);if(min<=0){toast("Укажи время чтения");return}const b=S.books.find(x=>x.id===id);if(!b||b.status!=="reading"){toast("Сначала начни книгу из очереди");return}const before=b.currentPage,remainingPages=Math.max(0,b.totalPages-before),actualPages=Math.min(pages,remainingPages);b.currentPage=Math.min(b.totalPages,b.currentPage+actualPages);const completed=before<b.totalPages&&b.currentPage>=b.totalPages;if(completed){b.status="done";b.completed=dateKey}const rawBase=Math.min(40,Math.floor(min/15)*10),baseXpAward=Math.min(rawBase,Math.max(0,40-readingBaseXpOnDate(dateKey))),completionBonus=completed?300:0,x={id:uid(),bookId:id,dateKey,minutes:min,pages:actualPages,note:$("readNote")?.value.trim()||"",baseXpAward,completionBonus,xpAward:baseXpAward+completionBonus};S.readingLogs.unshift(x);S.readingLogs.sort((a,b)=>String(b.dateKey).localeCompare(String(a.dateKey)));addXp(x.xpAward,"Разум",completed?"Книга закончена":"Чтение",`read:${x.id}`,"",dateKey);if($("readNote"))$("readNote").value="";if($("readDate"))$("readDate").value=localDateKey();closeModal("readingModal");await save(completed?"Книга завершена • бонус 300 XP":baseXpAward?`Чтение сохранено • +${baseXpAward} XP`:"Чтение сохранено • дневной лимит XP достигнут")}

async function deleteReading(id){const i=S.readingLogs.findIndex(x=>x.id===id);if(i<0)return;const x=S.readingLogs[i];if(!confirm("Удалить эту сессию чтения и пересчитать прогресс книги?"))return;S.readingLogs.splice(i,1);removeXp(x.xpAward||0,"Разум","Удалена сессия чтения",`read:${id}`,x.dateKey);recomputeBookProgress(x.bookId);await save("Сессия чтения удалена")}

async function deleteBook(id){if(!confirm("Удалить книгу? История чтения останется."))return;S.books=S.books.filter(x=>x.id!==id);await save("Книга удалена")}

function renderKnowledgeBase(){const box=$("knowledgeBase");if(!box)return;const q=String($("knowledgeSearch")?.value||"").toLowerCase(),notes=S.readingLogs.filter(x=>x.note).filter(x=>{const b=S.books.find(z=>z.id===x.bookId);return !q||`${x.note} ${b?.title||""} ${b?.author||""}`.toLowerCase().includes(q)}).slice(0,50);box.innerHTML=notes.length?notes.map(x=>{const b=S.books.find(z=>z.id===x.bookId);return `<div class="log-item"><div class="qtitle">${escapeHtml(b?.title||"Книга")} • ${fmtDate(parseLocal(x.dateKey))}</div><div class="qmeta">${escapeHtml(x.note)}</div></div>`}).join(""):'<div class="empty">Заметки не найдены.</div>'}

function renderReadingDashboard(){const month=S.readingLogs.filter(x=>x.dateKey?.startsWith(localMonthKey())),mins=month.reduce((a,x)=>a+(+x.minutes||0),0),pages=month.reduce((a,x)=>a+(+x.pages||0),0),completed=S.books.filter(b=>b.status==="done"&&String(b.completed||"").startsWith(localMonthKey())).length,notes=S.readingLogs.filter(x=>x.note).slice(0,5),recent=S.readingLogs.slice(0,8);$("readingDashboard").innerHTML=`<div class="report-grid"><div class="report-item"><div class="smallcaps">Минуты месяца</div><b>${mins}</b></div><div class="report-item"><div class="smallcaps">Страницы</div><b>${pages}</b></div><div class="report-item"><div class="smallcaps">Книг завершено в месяце</div><b>${completed}</b></div></div><div class="title" style="margin-top:14px">Последние тезисы</div>${notes.length?notes.map(x=>{const b=S.books.find(q=>q.id===x.bookId);return `<div class="log-item"><div class="qtitle">${escapeHtml(b?.title||"Удалённая книга")} • ${fmtDate(parseLocal(x.dateKey))}</div><div class="qmeta">${escapeHtml(x.note)}</div></div>`}).join(""):`<div class="empty">Добавляй мысль после чтения — она появится здесь.</div>`}<div class="title" style="margin-top:14px">Последние сессии</div>${recent.length?recent.map(x=>{const b=S.books.find(q=>q.id===x.bookId);return `<div class="log-item"><div class="qtitle">${fmtDate(parseLocal(x.dateKey))} • ${escapeHtml(b?.title||"Удалённая книга")} • ${x.minutes} мин</div><div class="qmeta">${x.pages||0} стр. • +${x.xpAward||0} XP</div><button class="btn ghost small" style="margin-top:7px" onclick="deleteReading('${x.id}')">Удалить запись</button></div>`}).join(""):`<div class="empty">Сессий пока нет.</div>`}` }

function renderBooks(){const reading=(S.books||[]).filter(b=>b.status==="reading"),queued=readingQueueSorted(),done=(S.books||[]).filter(b=>b.status==="done").slice().sort((a,b)=>String(b.completed||"").localeCompare(String(a.completed||""))),ordered=[...reading,...queued,...done];$("readBook").innerHTML=reading.length?reading.map(b=>`<option value="${b.id}">${escapeHtml(b.title)}</option>`).join(""):'<option value="">Сначала начни книгу из очереди</option>';$("bookList").innerHTML=ordered.length?ordered.map(b=>{const isDone=b.status==="done",isQueued=b.status==="queued",pages=Math.max(0,+b.totalPages||0),current=Math.max(0,+b.currentPage||0),p=pages>0?clamp(current/pages*100,0,100):0,tag=isDone?"прочитано":isQueued?`№${+b.readingOrder||"—"} в очереди`:`читаю • ${current}/${pages}`;return `<div class="book"><div class="book-head"><div><b>${escapeHtml(b.title)}</b><div class="sub">${escapeHtml(b.author||"")}</div></div><span class="tag ${isDone?"good":""}">${tag}</span></div>${isQueued?`<div class="sub" style="margin-top:9px">${pages?`${pages} стр.`:"Количество страниц укажешь при старте книги."}</div>`:`<div class="progress" style="margin-top:9px"><i style="width:${p}%"></i></div>`}<div class="split" style="margin-top:9px">${isQueued?`<button class="btn secondary small" onclick="startQueuedBook('${b.id}')">Начать</button>`:!isDone?`<button class="btn ghost small" onclick="openReadingFor('${b.id}')">+ Читать</button>`:""}<button class="btn ghost small" onclick="deleteBook('${b.id}')">Удалить</button></div></div>`}).join(""):'<div class="empty">Добавь книгу или импортируй список чтения.</div>'}

function openReadingFor(id){const b=S.books.find(x=>x.id===id);if(!b||b.status!=="reading"){toast("Сначала начни книгу из очереди");return}$("readBook").value=id;openModal("readingModal")}

$("readingListImport")?.addEventListener("change",e=>importReadingListFile(e.target.files?.[0]));
