"use strict";

/* Life RPG 8.0.2 — Reading and knowledge */

function readingDaysThisWeek(){const wk=isoWeekKey();return new Set(S.readingLogs.filter(x=>isoWeekKey(parseLocal(x.dateKey))===wk).map(x=>x.dateKey)).size}

function currentBook(){return S.books.find(b=>b.status!=="done")}

async function addBook(){const title=$("bookTitle").value.trim(),pages=+$("bookPages").value||0;if(!title||pages<=0){toast("Укажи название и страницы");return}S.books.push({id:uid(),title,author:$("bookAuthor").value.trim(),totalPages:pages,currentPage:0,status:"reading",created:localDateKey(),notes:""});$("bookTitle").value=$("bookAuthor").value=$("bookPages").value="";closeModal("bookModal");await save("Книга добавлена")}

function readingBaseXpOnDate(dateKey,excludeId=""){return Math.min(40,(S.readingLogs||[]).filter(x=>x.dateKey===dateKey&&x.id!==excludeId).reduce((s,x)=>s+Math.min(40,Math.max(0,x.baseXpAward==null?Math.min(40,+x.xpAward||0):+x.baseXpAward||0)),0))}

function recomputeBookProgress(bookId){const b=S.books.find(x=>x.id===bookId);if(!b)return;const pages=(S.readingLogs||[]).filter(x=>x.bookId===bookId).reduce((s,x)=>s+Math.max(0,+x.pages||0),0);b.currentPage=Math.min(b.totalPages,pages);if(b.currentPage>=b.totalPages&&b.totalPages>0){b.status="done";const last=(S.readingLogs||[]).filter(x=>x.bookId===bookId).map(x=>x.dateKey).sort().at(-1);b.completed=last||b.completed||localDateKey()}else{b.status="reading";delete b.completed}}

async function addReading(){const id=$("readBook").value,dateKey=$("readDate")?.value||localDateKey();if(!validActivityDate(dateKey)){toast("Чтение можно добавить только за сегодня или прошедшую дату");return}const min=Math.max(0,+$("readMinutes").value||0),pages=Math.max(0,+$("readPages").value||0);if(min<=0){toast("Укажи время чтения");return}const b=S.books.find(x=>x.id===id);if(!b){toast("Сначала добавь книгу");return}const before=b.currentPage,remainingPages=Math.max(0,b.totalPages-before),actualPages=Math.min(pages,remainingPages);b.currentPage=Math.min(b.totalPages,b.currentPage+actualPages);const completed=before<b.totalPages&&b.currentPage>=b.totalPages;if(completed){b.status="done";b.completed=dateKey}const rawBase=Math.min(40,Math.floor(min/15)*10),baseXpAward=Math.min(rawBase,Math.max(0,40-readingBaseXpOnDate(dateKey))),completionBonus=completed?300:0,x={id:uid(),bookId:id,dateKey,minutes:min,pages:actualPages,note:$("readNote")?.value.trim()||"",baseXpAward,completionBonus,xpAward:baseXpAward+completionBonus};S.readingLogs.unshift(x);S.readingLogs.sort((a,b)=>String(b.dateKey).localeCompare(String(a.dateKey)));addXp(x.xpAward,"Разум",completed?"Книга закончена":"Чтение",`read:${x.id}`,"",dateKey);if($("readNote"))$("readNote").value="";if($("readDate"))$("readDate").value=localDateKey();closeModal("readingModal");await save(completed?"Книга завершена • бонус 300 XP":baseXpAward?`Чтение сохранено • +${baseXpAward} XP`:"Чтение сохранено • дневной лимит XP достигнут")}

async function deleteReading(id){const i=S.readingLogs.findIndex(x=>x.id===id);if(i<0)return;const x=S.readingLogs[i];if(!confirm("Удалить эту сессию чтения и пересчитать прогресс книги?"))return;S.readingLogs.splice(i,1);removeXp(x.xpAward||0,"Разум","Удалена сессия чтения",`read:${id}`,x.dateKey);recomputeBookProgress(x.bookId);await save("Сессия чтения удалена")}

async function deleteBook(id){if(!confirm("Удалить книгу? История чтения останется."))return;S.books=S.books.filter(x=>x.id!==id);await save("Книга удалена")}

function renderKnowledgeBase(){const box=$("knowledgeBase");if(!box)return;const q=String($("knowledgeSearch")?.value||"").toLowerCase(),notes=S.readingLogs.filter(x=>x.note).filter(x=>{const b=S.books.find(z=>z.id===x.bookId);return !q||`${x.note} ${b?.title||""} ${b?.author||""}`.toLowerCase().includes(q)}).slice(0,50);box.innerHTML=notes.length?notes.map(x=>{const b=S.books.find(z=>z.id===x.bookId);return `<div class="log-item"><div class="qtitle">${escapeHtml(b?.title||"Книга")} • ${fmtDate(parseLocal(x.dateKey))}</div><div class="qmeta">${escapeHtml(x.note)}</div></div>`}).join(""):'<div class="empty">Заметки не найдены.</div>'}

function renderReadingDashboard(){const month=S.readingLogs.filter(x=>x.dateKey?.startsWith(localMonthKey())),mins=month.reduce((a,x)=>a+(+x.minutes||0),0),pages=month.reduce((a,x)=>a+(+x.pages||0),0),completed=S.books.filter(b=>b.status==="done"&&String(b.completed||"").startsWith(localMonthKey())).length,notes=S.readingLogs.filter(x=>x.note).slice(0,5),recent=S.readingLogs.slice(0,8);$("readingDashboard").innerHTML=`<div class="report-grid"><div class="report-item"><div class="smallcaps">Минуты месяца</div><b>${mins}</b></div><div class="report-item"><div class="smallcaps">Страницы</div><b>${pages}</b></div><div class="report-item"><div class="smallcaps">Книг завершено в месяце</div><b>${completed}</b></div></div><div class="title" style="margin-top:14px">Последние тезисы</div>${notes.length?notes.map(x=>{const b=S.books.find(q=>q.id===x.bookId);return `<div class="log-item"><div class="qtitle">${escapeHtml(b?.title||"Удалённая книга")} • ${fmtDate(parseLocal(x.dateKey))}</div><div class="qmeta">${escapeHtml(x.note)}</div></div>`}).join(""):`<div class="empty">Добавляй мысль после чтения — она появится здесь.</div>`}<div class="title" style="margin-top:14px">Последние сессии</div>${recent.length?recent.map(x=>{const b=S.books.find(q=>q.id===x.bookId);return `<div class="log-item"><div class="qtitle">${fmtDate(parseLocal(x.dateKey))} • ${escapeHtml(b?.title||"Удалённая книга")} • ${x.minutes} мин</div><div class="qmeta">${x.pages||0} стр. • +${x.xpAward||0} XP</div><button class="btn ghost small" style="margin-top:7px" onclick="deleteReading('${x.id}')">Удалить запись</button></div>`}).join(""):`<div class="empty">Сессий пока нет.</div>`}` }

function renderBooks(){const active=S.books.filter(b=>b.status!=="done"),done=S.books.filter(b=>b.status==="done");$("readBook").innerHTML=active.length?active.map(b=>`<option value="${b.id}">${escapeHtml(b.title)}</option>`).join(""):'<option value="">Нет активной книги</option>';$("bookList").innerHTML=S.books.length?S.books.map(b=>{const p=clamp(b.currentPage/b.totalPages*100,0,100);return `<div class="book"><div class="book-head"><div><b>${escapeHtml(b.title)}</b><div class="sub">${escapeHtml(b.author||"")}</div></div><span class="tag ${b.status==="done"?"good":""}">${b.status==="done"?"прочитано":`${b.currentPage}/${b.totalPages}`}</span></div><div class="progress" style="margin-top:9px"><i style="width:${p}%"></i></div><div class="split" style="margin-top:9px"><button class="btn ghost small" onclick="openReadingFor('${b.id}')">+ Читать</button><button class="btn ghost small" onclick="deleteBook('${b.id}')">Удалить</button></div></div>`}).join(""):'<div class="empty">Добавь книгу и фиксируй чтение.</div>'}

function openReadingFor(id){$("readBook").value=id;openModal("readingModal")}
