"use strict";

/* Life RPG 10.0.0 — Knowledge OS */

function readingDaysThisWeek(){const wk=isoWeekKey();return new Set(S.readingLogs.filter(x=>isoWeekKey(parseLocal(x.dateKey))===wk).map(x=>x.dateKey)).size}
function currentBook(){return S.books.find(b=>b.status==="reading")||null}
function readingQueueSorted(){return (S.books||[]).filter(b=>b.status==="queued").slice().sort((a,b)=>(+a.readingOrder||999999)-(+b.readingOrder||999999)||String(a.created||"").localeCompare(String(b.created||""))||String(a.title||"").localeCompare(String(b.title||""),"ru"))}
function nextQueuedBook(){return readingQueueSorted()[0]||null}
function nextReadingOrder(){return (S.books||[]).reduce((m,b)=>Math.max(m,+b.readingOrder||0),0)+1}
function normalizeBookText(s){return String(s||"").normalize("NFKC").toLowerCase().replace(/[«»„“”"'’]/g,"").replace(/\s+/g," ").trim()}
function bookIdentityKey(author,title){return `${normalizeBookText(author)}|${normalizeBookText(title)}`}

function normalizeReadingListPackage(obj){if(!obj||obj.format!=="life-rpg-reading-list-v1"||!Array.isArray(obj.books))throw new Error("Неподдерживаемый формат списка чтения");const books=obj.books.map((x,i)=>({order:Math.max(1,Math.round(+x.order||i+1)),author:String(x.author||"").trim(),title:String(x.title||"").trim(),totalPages:Math.max(0,Math.round(+x.totalPages||0))})).filter(x=>x.title).sort((a,b)=>a.order-b.order);if(!books.length)throw new Error("В списке нет книг");return {title:String(obj.title||"Список чтения").trim(),books}}
function mergeReadingListPackage(obj){const pkg=normalizeReadingListPackage(obj),existing=new Set((S.books||[]).map(b=>bookIdentityKey(b.author,b.title))),added=[],skipped=[];let order=nextReadingOrder();for(const item of pkg.books){const key=bookIdentityKey(item.author,item.title);if(existing.has(key)){skipped.push(item);continue}const b={id:uid(),title:item.title,author:item.author,totalPages:item.totalPages,currentPage:0,status:"queued",readingOrder:order++,created:localDateKey(),notes:"",source:"reading-list-import"};S.books.push(b);existing.add(key);added.push(b)}return {title:pkg.title,added,skipped,total:pkg.books.length}}
async function importReadingListFile(file){if(!file)return;try{let obj=JSON.parse(await file.text());const checked=window.LifePlatform?.validateReadingList?.(obj);if(checked&&!checked.ok)throw new Error(checked.error||"Список чтения не прошёл проверку");obj=checked?.data||obj;await createPreActionSnapshot("Перед импортом списка чтения");const r=mergeReadingListPackage(obj);audit("Импорт списка чтения","knowledge",`${r.added.length} добавлено • ${r.skipped.length} пропущено`);await persist();render();const box=$("readingListImportStatus");if(box)box.innerHTML=`<b>Импортировано: ${r.added.length}</b> • уже было: ${r.skipped.length} • всего в файле: ${r.total}`;toast(r.added.length?`Добавлено книг: ${r.added.length}`:"Новых книг в списке нет")}catch(e){const box=$("readingListImportStatus");if(box)box.textContent=`Ошибка импорта: ${e.message||e}`;toast("Не удалось импортировать список чтения")}finally{const input=$("readingListImport");if(input)input.value=""}}

async function addBook(){const title=$("bookTitle").value.trim(),pages=+$("bookPages").value||0;if(!title||pages<=0){toast("Укажи название и страницы");return}const queued=!!currentBook(),book={id:uid(),title,author:$("bookAuthor").value.trim(),totalPages:pages,currentPage:0,status:queued?"queued":"reading",readingOrder:queued?nextReadingOrder():0,created:localDateKey(),started:queued?"":localDateKey(),notes:""};S.books.push(book);$("bookTitle").value=$("bookAuthor").value=$("bookPages").value="";closeModal("bookModal");await save(queued?"Книга добавлена в очередь":"Книга добавлена и начата")}
async function startQueuedBook(id){const b=S.books.find(x=>x.id===id);if(!b||!["queued","paused"].includes(b.status))return;const active=currentBook();if(active&&active.id!==id){toast(`Сначала заверши текущую книгу: ${active.title}`);return}let pages=Math.max(0,+b.totalPages||0);if(!pages){const raw=prompt(`Сколько страниц в твоём издании «${b.title}»?`,"");if(raw==null)return;pages=Math.max(0,Math.round(+raw||0))}if(pages<=0){toast("Укажи количество страниц");return}b.totalPages=pages;b.currentPage=Math.max(0,+b.currentPage||0);b.status="reading";b.started=b.started||localDateKey();audit("Книга начата","knowledge",b.title);await save(`Начата книга: ${b.title}`)}
async function setBookStatus(id,status){const b=S.books.find(x=>x.id===id);if(!b)return;if(status==="reading")return startQueuedBook(id);if(!["queued","paused","done","dropped","archived"].includes(status))return;if(status==="queued")b.readingOrder=b.readingOrder||nextReadingOrder();b.status=status;if(status==="done"){b.currentPage=Math.max(+b.totalPages||0,+b.currentPage||0);b.completed=b.completed||localDateKey()}if(status!=="done")delete b.completed;audit("Статус книги","knowledge",`${b.title} → ${status}`);await save("Статус книги обновлён")}
async function moveBookQueue(id,dir){const arr=readingQueueSorted(),i=arr.findIndex(b=>b.id===id),j=i+dir;if(i<0||j<0||j>=arr.length)return;const a=arr[i],b=arr[j],ao=+a.readingOrder||i+1,bo=+b.readingOrder||j+1;a.readingOrder=bo;b.readingOrder=ao;await save("Очередь чтения обновлена")}

function readingBaseXpOnDate(dateKey,excludeId=""){return (S.readingLogs||[]).filter(x=>x.dateKey===dateKey&&x.id!==excludeId).reduce((s,x)=>s+(+x.baseXpAward||Math.min(40,+x.xpAward||0)),0)}
function recomputeBookProgress(bookId){const b=S.books.find(x=>x.id===bookId);if(!b)return;const pages=(S.readingLogs||[]).filter(x=>x.bookId===bookId).reduce((s,x)=>s+Math.max(0,+x.pages||0),0);b.currentPage=Math.min(Math.max(0,+b.totalPages||0),pages);if(b.currentPage>=b.totalPages&&b.totalPages>0){b.status="done";const last=(S.readingLogs||[]).filter(x=>x.bookId===bookId).map(x=>x.dateKey).sort().at(-1);b.completed=last||b.completed||localDateKey()}else if(b.status==="done"){b.status="reading";delete b.completed}}

async function addReading(){const id=$("readBook").value,dateKey=$("readDate")?.value||localDateKey();if(!validActivityDate(dateKey)){toast("Чтение можно добавить только за сегодня или прошедшую дату");return}const min=Math.max(0,+$("readMinutes").value||0),requestedPages=Math.max(0,+$("readPages").value||0),editId=$("readEditId")?.value||"",old=editId?S.readingLogs.find(x=>x.id===editId):null,b=S.books.find(x=>x.id===id);if(min<=0){toast("Укажи время чтения");return}if(!b||(b.status!=="reading"&&!(old&&b.status==="done"))){toast("Сначала начни книгу из очереди");return}const otherActive=currentBook();if(old){S.readingLogs=S.readingLogs.filter(x=>x.id!==editId);removeXp(old.xpAward||0,"Разум","Редактирование чтения",`read:${editId}`,old.dateKey);recomputeBookProgress(old.bookId)}const before=(S.readingLogs||[]).filter(x=>x.bookId===id).reduce((s,x)=>s+Math.max(0,+x.pages||0),0),remainingPages=Math.max(0,(+b.totalPages||0)-before),actualPages=Math.min(requestedPages,remainingPages),after=before+actualPages,completed=before<(+b.totalPages||0)&&after>=(+b.totalPages||0);const rawBase=Math.min(40,Math.floor(min/15)*10),baseXpAward=Math.min(rawBase,Math.max(0,40-readingBaseXpOnDate(dateKey))),completionBonus=completed?300:0,x={id:old?.id||uid(),bookId:id,dateKey,minutes:min,pages:actualPages,chapter:$("readChapter")?.value.trim()||"",tags:$("readTags")?.value.split(",").map(v=>v.trim()).filter(Boolean)||[],note:$("readNote")?.value.trim()||"",application:$("readApply")?.value.trim()||"",reviewedAt:old?.reviewedAt||"",baseXpAward,completionBonus,xpAward:baseXpAward+completionBonus};S.readingLogs.unshift(x);S.readingLogs.sort((a,b)=>String(b.dateKey).localeCompare(String(a.dateKey)));recomputeBookProgress(id);if(b.status==="reading"&&otherActive&&otherActive.id!==b.id)b.status="paused";addXp(x.xpAward,"Разум",completed?"Книга закончена":old?"Сессия чтения обновлена":"Чтение",`read:${x.id}`,completed?"result":"process",dateKey);audit(old?"Чтение изменено":"Чтение","knowledge",`${b.title} • ${min} мин • ${actualPages} стр.`);cancelReadingEdit();closeModal("readingModal");await save(completed?"Книга завершена • бонус 300 XP":baseXpAward?`${old?"Чтение обновлено":"Чтение сохранено"} • +${baseXpAward} XP`:`${old?"Чтение обновлено":"Чтение сохранено"} • дневной лимит XP достигнут`)}
function editReading(id){const x=S.readingLogs.find(z=>z.id===id),b=x&&S.books.find(q=>q.id===x.bookId);if(!x||!b)return;if(b.status!=="reading"&&b.status!=="done"){toast("Редактирование доступно для активной/завершённой книги");return}openModal("readingModal");if($("readBook"))$("readBook").value=b.id;const vals={readEditId:x.id,readDate:x.dateKey,readMinutes:x.minutes,readPages:x.pages||0,readChapter:x.chapter||"",readTags:(x.tags||[]).join(", "),readNote:x.note||"",readApply:x.application||""};for(const [id,v] of Object.entries(vals))if($(id))$(id).value=v??"";if($("readSaveBtn"))$("readSaveBtn").textContent="Обновить чтение";if($("readCancelEdit"))$("readCancelEdit").hidden=false}
function cancelReadingEdit(){for(const id of ["readEditId","readChapter","readTags","readNote","readApply"])if($(id))$(id).value="";if($("readMinutes"))$("readMinutes").value=30;if($("readPages"))$("readPages").value=0;if($("readDate"))$("readDate").value=localDateKey();if($("readSaveBtn"))$("readSaveBtn").textContent="Сохранить чтение";if($("readCancelEdit"))$("readCancelEdit").hidden=true}
async function deleteReading(id){const i=S.readingLogs.findIndex(x=>x.id===id);if(i<0)return;const x=S.readingLogs[i];if(!confirm("Удалить эту сессию чтения? Её можно будет восстановить из корзины."))return;await createPreActionSnapshot("Перед удалением сессии чтения");trashPush("reading",x);S.readingLogs.splice(i,1);removeXp(x.xpAward||0,"Разум","Удалена сессия чтения",`read:${id}`,x.dateKey);recomputeBookProgress(x.bookId);await save("Сессия чтения удалена • прогресс пересчитан")}
async function deleteBook(id){const b=S.books.find(x=>x.id===id);if(!b)return;if(!confirm(`Архивировать книгу «${b.title}»? История чтения сохранится.`))return;b.status="archived";b.archivedAt=new Date().toISOString();audit("Книга архивирована","knowledge",b.title);await save("Книга перемещена в архив")}

function readingPaceData(){const b=currentBook();if(!b||!b.totalPages)return null;const since=localDateKey(addDays(new Date(),-13)),logs=S.readingLogs.filter(x=>x.bookId===b.id&&x.dateKey>=since),pages=logs.reduce((s,x)=>s+(+x.pages||0),0),days=new Set(logs.map(x=>x.dateKey)).size,pace=days?pages/days:0,remaining=Math.max(0,b.totalPages-b.currentPage),readingDays=pace>0?Math.ceil(remaining/pace):null;return {book:b,pages,days,pace,remaining,readingDays}}
function knowledgeReviewQueue(){const days=Math.max(1,+S.settings.readingReviewDays||7),cut=Date.now()-days*86400000;return (S.readingLogs||[]).filter(x=>x.note||x.application).filter(x=>!x.reviewedAt||Date.parse(x.reviewedAt)<cut).slice().sort((a,b)=>String(a.reviewedAt||a.dateKey).localeCompare(String(b.reviewedAt||b.dateKey))).slice(0,8)}
async function markKnowledgeReviewed(id){const x=S.readingLogs.find(z=>z.id===id);if(!x)return;x.reviewedAt=new Date().toISOString();audit("Повторение знания","knowledge",x.note||x.application||id);await save("Тезис отмечен повторённым")}

function renderKnowledgeBase(){const box=$("knowledgeBase");if(!box)return;const q=String($("knowledgeSearch")?.value||"").toLowerCase(),notes=S.readingLogs.filter(x=>x.note||x.application||x.chapter||(x.tags||[]).length).filter(x=>{const b=S.books.find(z=>z.id===x.bookId);return !q||`${x.note||""} ${x.application||""} ${x.chapter||""} ${(x.tags||[]).join(" ")} ${b?.title||""} ${b?.author||""}`.toLowerCase().includes(q)}).slice(0,80);box.innerHTML=notes.length?notes.map(x=>{const b=S.books.find(z=>z.id===x.bookId);return `<div class="log-item"><div class="qtitle">${escapeHtml(b?.title||"Книга")} • ${fmtDate(parseLocal(x.dateKey))}${x.chapter?` • ${escapeHtml(x.chapter)}`:""}</div>${x.tags?.length?`<div class="qmeta">${x.tags.map(t=>`#${escapeHtml(t)}`).join(" ")}</div>`:""}${x.note?`<div class="qmeta">Тезис: ${escapeHtml(x.note)}</div>`:""}${x.application?`<div class="qmeta">Применение: ${escapeHtml(x.application)}</div>`:""}</div>`}).join(""):'<div class="empty">Заметки не найдены.</div>'}
function renderReadingDashboard(){const month=S.readingLogs.filter(x=>x.dateKey?.startsWith(localMonthKey())),mins=month.reduce((a,x)=>a+(+x.minutes||0),0),pages=month.reduce((a,x)=>a+(+x.pages||0),0),completed=S.books.filter(b=>b.status==="done"&&String(b.completed||"").startsWith(localMonthKey())).length,pace=readingPaceData(),review=knowledgeReviewQueue(),recent=S.readingLogs.slice(0,8);$("readingDashboard").innerHTML=`<div class="report-grid"><div class="report-item"><div class="smallcaps">Минуты месяца</div><b>${mins}</b></div><div class="report-item"><div class="smallcaps">Страницы</div><b>${pages}</b></div><div class="report-item"><div class="smallcaps">Книг завершено</div><b>${completed}</b></div><div class="report-item"><div class="smallcaps">На повторение</div><b>${review.length}</b></div></div>${pace?`<div class="notice" style="margin-top:10px"><b>${escapeHtml(pace.book.title)}</b>: ${pace.remaining} стр. осталось • темп ${pace.pace.toFixed(1)} стр./день чтения${pace.readingDays!=null?` • примерно ${pace.readingDays} дней чтения до конца`:""}.</div>`:""}<div class="title" style="margin-top:14px">Повторить знания</div>${review.length?review.slice(0,4).map(x=>{const b=S.books.find(q=>q.id===x.bookId);return `<div class="log-item"><div class="qtitle">${escapeHtml(b?.title||"Книга")}</div><div class="qmeta">${escapeHtml(x.note||x.application||"")}</div><button class="btn ghost small" style="margin-top:7px" onclick="markKnowledgeReviewed('${x.id}')">Повторил</button></div>`}).join(""):`<div class="empty">Очередь повторения пуста.</div>`}<div class="title" style="margin-top:14px">Последние сессии</div>${recent.length?recent.map(x=>{const b=S.books.find(q=>q.id===x.bookId);return `<div class="log-item"><div class="qtitle">${fmtDate(parseLocal(x.dateKey))} • ${escapeHtml(b?.title||"Архивная книга")} • ${x.minutes} мин</div><div class="qmeta">${x.pages||0} стр. • +${x.xpAward||0} XP${x.chapter?` • ${escapeHtml(x.chapter)}`:""}</div><div class="split" style="margin-top:7px"><button class="btn ghost small" onclick="editReading('${x.id}')">Изменить</button><button class="btn ghost small" onclick="deleteReading('${x.id}')">Удалить</button></div></div>`}).join(""):`<div class="empty">Сессий пока нет.</div>`}`}
function renderBooks(){const reading=(S.books||[]).filter(b=>b.status==="reading"),queued=readingQueueSorted(),paused=(S.books||[]).filter(b=>b.status==="paused"),done=(S.books||[]).filter(b=>b.status==="done").slice().sort((a,b)=>String(b.completed||"").localeCompare(String(a.completed||""))),dropped=(S.books||[]).filter(b=>b.status==="dropped"),ordered=[...reading,...queued,...paused,...done,...dropped];$("readBook").innerHTML=reading.length?reading.map(b=>`<option value="${b.id}">${escapeHtml(b.title)}</option>`).join(""):'<option value="">Сначала начни книгу из очереди</option>';$("bookList").innerHTML=ordered.length?ordered.map(b=>{const isDone=b.status==="done",isQueued=b.status==="queued",isPaused=b.status==="paused",pages=Math.max(0,+b.totalPages||0),current=Math.max(0,+b.currentPage||0),p=pages>0?clamp(current/pages*100,0,100):0,tag=isDone?"прочитано":isQueued?`№${+b.readingOrder||"—"} в очереди`:isPaused?"пауза":b.status==="dropped"?"отложено":`читаю • ${current}/${pages}`;return `<div class="book"><div class="book-head"><div><b>${escapeHtml(b.title)}</b><div class="sub">${escapeHtml(b.author||"")}</div></div><span class="tag ${isDone?"good":""}">${tag}</span></div>${isQueued?`<div class="sub" style="margin-top:9px">${pages?`${pages} стр.`:"Количество страниц укажешь при старте книги."}</div>`:`<div class="progress" style="margin-top:9px"><i style="width:${p}%"></i></div>`}<div class="split" style="margin-top:9px">${isQueued?`<button class="btn secondary small" onclick="startQueuedBook('${b.id}')">Начать</button><button class="btn ghost small" onclick="moveBookQueue('${b.id}',-1)">↑</button><button class="btn ghost small" onclick="moveBookQueue('${b.id}',1)">↓</button>`:isPaused?`<button class="btn secondary small" onclick="startQueuedBook('${b.id}')">Продолжить</button>`:!isDone&&b.status==="reading"?`<button class="btn ghost small" onclick="openReadingFor('${b.id}')">+ Читать</button><button class="btn ghost small" onclick="setBookStatus('${b.id}','paused')">Пауза</button>`:""}${!isDone?`<button class="btn ghost small" onclick="setBookStatus('${b.id}','dropped')">Отложить</button>`:""}<button class="btn ghost small" onclick="deleteBook('${b.id}')">Архив</button></div></div>`}).join(""):'<div class="empty">Добавь книгу или импортируй список чтения.</div>'}
function openReadingFor(id){const b=S.books.find(x=>x.id===id);if(!b||b.status!=="reading"){toast("Эта книга сейчас не активна");return}openModal("readingModal");if($("readBook"))$("readBook").value=id}
