"use strict";
const fs=require("fs"),path=require("path"),vm=require("vm"),assert=require("assert"),root=__dirname,read=n=>fs.readFileSync(path.join(root,n),"utf8");
const predictive=read("predictive-trends-13.2.2.js"),core=read("core.js"),boot=read("bootstrap.js"),vite=read("vite.config.mjs"),pkg=JSON.parse(read("package.json")),play=read("playwright.config.mjs"),manifest=read("manifest.webmanifest");
assert.ok(core.includes('APP_VERSION="13.2.2"'));assert.ok(core.includes("STATE_VERSION=18"));assert.ok(manifest.includes("Life RPG 13.2.2"));assert.ok(vite.includes('cacheId:"life-rpg-13.2.2"'));
assert.ok(boot.includes('"predictive-trends-13.2.2.js"'));assert.ok(boot.includes('["ensurePredictive1322Ui","renderPredictive1322"]'));assert.ok(vite.includes('"predictive-trends-13.2.2.js"'));
for(const name of ["predictive1322Forecasts","predictive1322EarlyWarnings","predictive1322Verification","predictive1322CaptureDaily","predictive1322Candidates","predictive1322Top3Coverage","predictive1322Top3Scenario","predictive1322RiskMap","predictive1322Reliability"])assert.ok(predictive.includes(`function ${name}`),`${name} missing`);
assert.ok(!/fetch\(["'`]https?:/i.test(predictive),"Predictive Trends must remain local-first");assert.ok(pkg.scripts.test.includes("predictive-trends-13.2.2.test.js"));assert.ok(play.includes("predictive-trends-13.2.2.e2e.test.js"));

const RealDate=Date,futureGapDate=(()=>{const d=new RealDate();d.setDate(d.getDate()+3);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`})();
const ctx={console,Date:RealDate,Math,Number,String,Array,Object,Map,Set,JSON,Promise,TextEncoder,TextDecoder,URL,Blob,
  S:{settings:{minimumCashFloor:1000,workMonthlyPlan:1000000,tennisWeeklyTarget:3,readingWeeklyDaysTarget:5},accounts:[{id:"a",active:true,verifiedAt:new RealDate().toISOString()}],expenses:[],incomeLogs:[],payments:[],workLogs:[{date:"2026-09-20",sales:100000}],tennis:[],readingLogs:[{dateKey:"2026-09-24",minutes:30,pages:10}],crmDeals:[{id:"d",stage:"КП",potential:300000,probability:50,updatedAt:new RealDate().toISOString()}],entities:{}},
  document:{getElementById(){return null},querySelector(){return null},activeElement:null,createElement(){return {click(){},set href(v){this._href=v},get href(){return this._href},download:""}}},globalThis:null,
  clamp:(n,a,b)=>Math.max(a,Math.min(b,n)),validDateKey:s=>/^\d{4}-\d{2}-\d{2}$/.test(String(s||"")),localDateKey(d=new RealDate()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`},addDays(d,n){const x=new RealDate(d);x.setDate(x.getDate()+n);return x},parseLocal(s){const [y,m,d]=s.split("-").map(Number);return new RealDate(y,m-1,d,12)},localMonthKey(d=new RealDate()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`},uid:()=>"u"+Math.random().toString(36).slice(2),rub:n=>`${Math.round(+n||0)} ₽`,pct:(n,d=0)=>`${(+n||0).toFixed(d)}%`,escapeHtml:String,
  accountsModeActive:()=>true,operatingCashBalance:()=>900,buildFinancialProjection:(days,opts={})=>{const f=opts.incomeFactor==null?100:+opts.incomeFactor;const gap=f<=90?futureGapDate:"";return {balanceStart:5000,endingBalance:f<=90?700:2500,minBalance:f<=90?700:1800,minDate:futureGapDate,cashGapDate:gap,warnings:[],series:[]}},
  workPaceData:()=>({plan:1000000,sales:200000,total:22,elapsedBefore:10,left:12,requiredDaily:66667}),work121PaceForecast:()=>({plan:1000000,sales:200000,total:22,elapsed:10,left:12,daily:20000,requiredDaily:66667,paceForecast:440000,probabilityForecast:500000}),
  taskActive:()=>[{id:"t1",dueDate:"2026-09-27",priority:1,updatedAt:new RealDate().toISOString(),blockedByIds:[]}],taskHealth:t=>({overdue:false}),taskUnresolvedDependencies:()=>[],taskSummary:()=>({overdue:1}),calendarOverloadedDays:()=>[{dateKey:"2026-09-27",level:"bad"}],calendarDayLoad:()=>({level:"bad"}),
  training129Range:(days,offset)=>offset?{rows:[{dateKey:"2026-09-15"},{dateKey:"2026-09-16"},{dateKey:"2026-09-17"}],load:600}:{rows:[{dateKey:"2026-09-24"}],load:100},training129LoadProfile:()=>({interpretable:true,ratio:.4,weeklyBase:500,baseSessions:8}),training129Quality:()=>({sessions:12}),
  readingConsistencyData:()=>({weeklyDays:2,streak:1}),readingVelocityData:()=>({calendarDays:40}),
  lifeOsDailyPlan:()=>({plan:[{area:"Работа",id:"w"},{area:"Финансы",id:"f"},{area:"Система",id:"s",taskId:"t1"}]}),lifeOsRegisterCandidateProvider(){},lifeOsRegisterRouteHandler(){},ux7Go(){},persist:async()=>{},render(){},setTimeout(){},share131DownloadBlob(){},URL:{createObjectURL:()=>"blob:x",revokeObjectURL(){}}
};ctx.globalThis=ctx;vm.createContext(ctx);vm.runInContext(predictive,ctx);const run=code=>vm.runInContext(code,ctx);

const f7=JSON.parse(run(`JSON.stringify(predictive1322Forecasts(7))`));assert.equal(f7.length,5);assert.deepEqual(f7.map(x=>x.domain),["finance","work","system","training","knowledge"]);assert.ok(f7.every(x=>x.horizon===7));assert.ok(f7.every(x=>Number.isFinite(x.riskScore)&&Number.isFinite(x.confidence)));
const finance=f7.find(x=>x.domain==="finance");assert.ok(finance.riskScore>=60);assert.equal(finance.timeToRisk,3);assert.ok(finance.range.includes("₽"));assert.ok(finance.limits.some(x=>x.includes("вероятностный")));
const work=f7.find(x=>x.domain==="work");assert.ok(work.riskScore>=50);assert.ok(work.requiredPace.includes("рабочий день"));assert.ok(work.limits.some(x=>x.includes("не конвертируется")));
const system=f7.find(x=>x.domain==="system");assert.ok(system.riskScore>=40);assert.ok(system.evidence.some(x=>x.includes("приоритет 1")));
const training=f7.find(x=>x.domain==="training");assert.equal(training.key,"training-inactivity");assert.equal(training.timeToRisk,null);assert.ok(training.limits.some(x=>x.includes("не прогнозирует медицинский")));
const knowledge=f7.find(x=>x.domain==="knowledge");assert.ok(knowledge.riskScore>=50);assert.equal(knowledge.timeToRisk,0);assert.ok(knowledge.requiredPace.includes("дн./нед"));

const candidates=JSON.parse(run(`JSON.stringify(predictive1322Candidates())`));assert.ok(candidates.length>=2);assert.ok(candidates.every(x=>x.kind==="early-warning"&&x.source.includes("13.2.2")));assert.ok(candidates.every(x=>x.hard===false));
const coverage=JSON.parse(run(`JSON.stringify(predictive1322Top3Coverage())`));assert.ok(coverage.total>=1);assert.ok(coverage.covered>=1);assert.equal(run(`S.settings.workMonthlyPlan`),1000000,"coverage must not mutate source data");
const scenario=JSON.parse(run(`JSON.stringify(predictive1322Top3Scenario())`));assert.equal(scenario.quantified,false);assert.equal(scenario.afterTop3.length,coverage.rows.length);assert.ok(scenario.reason.includes("фактического результата"));

// Forecast verification is directional and never interprets risk score as probability.
run(`predictive1322Store().snapshots=[{capturedDate:"2026-09-01",targetDate:localDateKey(),key:"finance-buffer",domain:"finance",horizon:7,riskScore:80,confidence:90,evaluatedAt:"",verificationStatus:"pending",observed:null,predictedRisk:true,directionHit:null}]`);run(`predictive1322EvaluateSnapshots()`);const ver=JSON.parse(run(`JSON.stringify(predictive1322Verification())`));assert.equal(ver.n,1);assert.equal(ver.expired,0);assert.equal(ver.directionalAccuracy,1);assert.equal(ver.riskHitRate,1);assert.equal(ver.byDomain.finance.n,1);assert.equal(ver.byHorizon["7"].n,1);

// Missed target dates must expire instead of being compared with today's state.
run(`predictive1322Store().snapshots=[{capturedDate:"2026-09-01",targetDate:localDateKey(addDays(new Date(),-1)),key:"work-pace",domain:"work",horizon:7,riskScore:80,confidence:90,evaluatedAt:"",verificationStatus:"pending",observed:null,predictedRisk:true,directionHit:null}]`);run(`predictive1322EvaluateSnapshots()`);const missed=JSON.parse(run(`JSON.stringify(predictive1322Verification())`));assert.equal(missed.n,0);assert.equal(missed.expired,1);

// Reliability calibration is bounded and adjusts confidence only after enough verified samples.
run(`predictive1322Store().snapshots=Array.from({length:5},(_,i)=>({id:"r"+i,domain:"work",horizon:7,verificationStatus:"verified",directionHit:false,evaluatedAt:new Date().toISOString()}))`);const rel=JSON.parse(run(`JSON.stringify(predictive1322Reliability("work",7))`));assert.equal(rel.n,5);assert.ok(rel.adjustment<0&&rel.adjustment>=-12);const calibrated=JSON.parse(run(`JSON.stringify(predictive1322Work(7))`));assert.equal(calibrated.riskScore,work.riskScore);assert.ok(calibrated.confidence<work.confidence);

const map=JSON.parse(run(`JSON.stringify(predictive1322RiskMap())`));assert.deepEqual(map.map(x=>x.horizon),[3,7,14,30]);
console.log("OK — Predictive Trends & Early Warning 13.2.2: multi-horizon forecasts, confidence separation, verification, radar candidates and Top-3 coverage passed");
