"use strict";

/* Life RPG 8.1.0 — PWA and notifications • UX cleanup */

async function enableNotifications(){if(!("Notification" in window)){toast("Уведомления не поддерживаются");return}const p=await Notification.requestPermission();$("notificationStatus").textContent=`Разрешение: ${p}`;if(p==="granted"){toast("Уведомления включены");runReminderCheck(true)}}

async function notifyOnce(tag,title,body,force=false){if(!("Notification" in window)||Notification.permission!=="granted")return;const key=`notif:${tag}`,day=localDateKey();if(!force&&localStorage.getItem(key)===day)return;localStorage.setItem(key,day);if(navigator.serviceWorker?.controller)navigator.serviceWorker.controller.postMessage({type:"NOTIFY",title,body,tag});else new Notification(title,{body,icon:"./icon-192.png",tag})}

function runReminderCheck(force=false){const now=new Date();for(const e of financialEvents().filter(x=>x.type==="payment")){const days=daysBetween(now,e.date);if(e.amount<=0)continue;if(e.overdue)notifyOnce(`overdue-${e.kind}-${e.debtId||e.regularPaymentId||e.label}`,"Проверь обязательный платёж",`${e.label}: не закрыто ${rub(e.amount)}`,force);else if(days>=0&&days<=2)notifyOnce(`due-${e.kind}-${e.debtId||e.regularPaymentId||e.label}-${localDateKey(e.date)}`,"Скоро обязательный платёж",`${e.label}: ${rub(e.amount)}, срок ${fmtDate(e.date)}`,force)}const remain=Math.max(0,S.settings.monthlyDebtGoal-monthPayments()),daysLeft=new Date(now.getFullYear(),now.getMonth()+1,0).getDate()-now.getDate();if(S.settings.monthlyDebtGoal>0&&remain>0&&daysLeft<=5)notifyOnce(`monthgoal-${localMonthKey()}`,"Финансовый квест месяца",`До цели осталось ${rub(remain)} и ${daysLeft} дн.`,force);for(const d of (S.crmDeals||[]).filter(x=>!["Выиграно","Проиграно"].includes(x.stage)&&x.nextDate)){const days=daysBetween(now,parseLocal(d.nextDate));if(days<0)notifyOnce(`crm-overdue-${d.id}`,"CRM: просрочен следующий шаг",`${d.name}: ${d.nextStep||"следующий шаг не указан"}`,force);else if(days<=1)notifyOnce(`crm-due-${d.id}-${d.nextDate}`,"CRM: следующий шаг",`${d.name}: ${d.nextStep||"проверь сделку"} • ${days===0?"сегодня":"завтра"}`,force)}}

let pwaRegistration=null,pwaRefreshing=false,pwaHadController=false;

async function checkForAppUpdate(){try{const resp=await fetch(`./core.js?check=${Date.now()}`,{cache:"no-store"});if(!resp.ok)throw new Error(`HTTP ${resp.status}`);const txt=await resp.text(),m=txt.match(/const\s+APP_VERSION\s*=\s*["\']([^"\']+)["\']/),remote=m?.[1]||"";if(pwaRegistration)await pwaRegistration.update();if(remote&&remote!==APP_VERSION){toast(`Доступно обновление ${remote}`);setTimeout(()=>location.replace(`./?v=${encodeURIComponent(remote)}&t=${Date.now()}`),350);return}toast(`Life RPG ${APP_VERSION} — актуальная версия`)}catch(e){toast("Не удалось проверить обновление")}}

function setupPwa(){if("serviceWorker" in navigator){pwaHadController=!!navigator.serviceWorker.controller;navigator.serviceWorker.addEventListener("controllerchange",()=>{if(pwaHadController&&!pwaRefreshing){pwaRefreshing=true;location.reload()}pwaHadController=true});window.addEventListener("load",async()=>{try{pwaRegistration=await navigator.serviceWorker.register("./sw.js?v=8.1.0",{updateViaCache:"none"});$("versionStatus").textContent=`Life RPG ${APP_VERSION} • PWA готова • данные v${STATE_VERSION}`;await pwaRegistration.update();setInterval(()=>pwaRegistration?.update().catch(()=>{}),21600000)}catch(e){$("versionStatus").textContent=`Life RPG ${APP_VERSION} • service worker не запущен`}})}window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;$("installBtn").hidden=false});$("installBtn").addEventListener("click",async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$("installBtn").hidden=true})}
