"use strict";

/* Life RPG 11.1.0 — Recovery / Disaster Recovery 2.0 */

let recoverySnapshotsCache=[],recoverySelectedTs=0;
const RECOVERY_ENTITY_TYPES=["projects","tasks","goals","routines","reviews","inbox","calendarEvents","crmDeals","books"];
function recoveryCollection(state,type){if(["crmDeals","books"].includes(type))return Array.isArray(state?.[type])?state[type]:[];return Array.isArray(state?.entities?.[type])?state.entities[type]:[]}
function recoveryLabel(type){return ({projects:"Проект",tasks:"Задача",goals:"Цель",routines:"Рутина",reviews:"Review",inbox:"Inbox",calendarEvents:"Событие",crmDeals:"CRM",books:"Книга"})[type]||type}
function recoveryItemTitle(x){return String(x?.title||x?.name||x?.label||x?.id||"Без названия")}
function recoveryDiffState(snapshotState,current=S){const snap=normalizeState(snapshotState),out=[];for(const type of RECOVERY_ENTITY_TYPES){const a=new Map(recoveryCollection(snap,type).map(x=>[String(x.id),x])),b=new Map(recoveryCollection(current,type).map(x=>[String(x.id),x])),ids=new Set([...a.keys(),...b.keys()]);for(const id of ids){const old=a.get(id),now=b.get(id);if(!old){out.push({type,id,kind:"created",snapshot:null,current:now});continue}if(!now){out.push({type,id,kind:"deleted",snapshot:old,current:null});continue}if(JSON.stringify(old)!==JSON.stringify(now))out.push({type,id,kind:"changed",snapshot:old,current:now})}}return out}
async function recoveryLoadSnapshots(){try{if(!db)await openDB();recoverySnapshotsCache=(await dbGetAll("backups")).sort((a,b)=>b.ts-a.ts).slice(0,20);return recoverySnapshotsCache}catch{return []}}
async function recoveryCreateCheckpoint(){await createPreActionSnapshot("Ручной checkpoint 11.0");await recoveryLoadSnapshots();renderRecoveryOs();toast("Checkpoint создан")}
async function recoveryInspect(ts){recoverySelectedTs=+ts;await renderRecoveryOs()}
async function recoveryRestoreEntity(ts,type,id){if(!RECOVERY_ENTITY_TYPES.includes(type))return;if(!confirm(`Восстановить только сущность «${recoveryLabel(type)}» из выбранного снимка? Текущее состояние будет сохранено.`))return;try{if(!db)await openDB();const snap=await dbGet("backups",+ts);if(!snap?.state)throw new Error("snapshot missing");const old=normalizeState(snap.state),source=recoveryCollection(old,type).find(x=>String(x.id)===String(id));if(!source){toast("В снимке этой сущности нет");return}await createPreActionSnapshot(`Перед точечным восстановлением ${type}:${id}`);const target=recoveryCollection(S,type),idx=target.findIndex(x=>String(x.id)===String(id));if(idx>=0)target[idx]=deepClone(source);else target.push(deepClone(source));if(type==="projects"&&typeof projectStore==="function")S.entities.projects=target;if(type==="tasks")S.entities.tasks=target;if(type==="goals")S.entities.goals=target;if(type==="routines")S.entities.routines=target;if(type==="reviews")S.entities.reviews=target;if(type==="inbox")S.entities.inbox=target;if(type==="calendarEvents")S.entities.calendarEvents=target;if(type==="crmDeals")S.crmDeals=target;if(type==="books")S.books=target;audit("Точечное восстановление","system",`${type}:${id}`);await save("Сущность восстановлена из снимка");await recoveryLoadSnapshots();render()}catch(e){console.error(e);toast("Не удалось восстановить сущность")}}
function ensureRecoveryOsUi(){if(document.getElementById("recoveryOsCommand"))return;const grid=document.querySelector?.("#more .grid");if(!grid||typeof grid.insertAdjacentHTML!=="function")return;grid.insertAdjacentHTML("beforeend",`<div data-ux7-view="settings" class="card ux7-card span-12"><div class="split"><div><div class="eyebrow">Recovery 2.0</div><div class="section-title">Снимки и точечное восстановление</div></div><button class="btn secondary small" onclick="recoveryCreateCheckpoint()">+ Checkpoint</button></div><div class="muted" style="margin-top:6px">Финансовые журналы точечно не восстанавливаются: для них безопаснее полный snapshot. Проекты, задачи, цели, рутины, CRM и книги можно вернуть отдельно.</div><div id="recoveryOsCommand" style="margin-top:10px"></div><div id="recoveryDiff" style="margin-top:10px"></div></div>`);recoveryLoadSnapshots().then(()=>renderRecoveryOs())}
async function renderRecoveryOs(){const box=document.getElementById("recoveryOsCommand"),diff=document.getElementById("recoveryDiff");if(!box||!diff)return;if(!recoverySnapshotsCache.length)await recoveryLoadSnapshots();box.innerHTML=recoverySnapshotsCache.length?recoverySnapshotsCache.slice(0,10).map(x=>`<div class="log-item"><div class="split"><div><div class="qtitle">${new Date(x.ts).toLocaleString("ru-RU")}</div><div class="qmeta">${escapeHtml(x.label||"Локальный снимок")}</div></div><div class="split"><button class="btn ghost small" onclick="recoveryInspect(${x.ts})">Сравнить</button><button class="btn ghost small" onclick="restoreSnapshot(${x.ts})">Полный откат</button></div></div></div>`).join(""):'<div class="empty">Снимков пока нет.</div>';if(!recoverySelectedTs){diff.innerHTML='';return}const snap=recoverySnapshotsCache.find(x=>x.ts===recoverySelectedTs);if(!snap){diff.innerHTML='';return}const rows=recoveryDiffState(snap.state);diff.innerHTML=`<div class="title">Отличия выбранного снимка: ${rows.length}</div>`+(rows.length?rows.slice(0,30).map(r=>`<div class="quest"><span class="tag">${escapeHtml(recoveryLabel(r.type))}</span><div class="qbody"><div class="qtitle">${escapeHtml(recoveryItemTitle(r.snapshot||r.current))}</div><div class="qmeta">${r.kind==="created"?"Появилось после снимка":r.kind==="deleted"?"Удалено после снимка":"Изменено после снимка"}</div></div>${r.snapshot?`<button class="btn secondary small" onclick="recoveryRestoreEntity(${snap.ts},'${r.type}','${String(r.id).replace(/'/g,"\\'")}')">Восстановить</button>`:""}</div>`).join(""):'<div class="status">Существенных различий в поддерживаемых сущностях нет.</div>')}
