"use strict";

/* Life RPG 10.2.0 — Habits / Routines OS
   Missed routines remain historical misses; they do not become an ever-growing overdue task stack. */

function routineStore(){if(!Array.isArray(S.settings.routines))S.settings.routines=[];return S.settings.routines}
function routineLogStore(){if(!Array.isArray(S.settings.routineLogs))S.settings.routineLogs=[];return S.settings.routineLogs}
function routineNormalize(x={}){return {id:String(x.id||uid()),title:String(x.title||"Рутина").trim(),area:String(x.area||"Личное"),priority:clamp(Math.round(+x.priority||2),1,3),days:Array.isArray(x.days)?[...new Set(x.days.map(Number).filter(n=>n>=1&&n<=7))].sort((a,b)=>a-b):[1,2,3,4,5,6,7],minutes:clamp(Math.round(+x.minutes||15),0,360),status:["active","paused","archived"].includes(x.status)?x.status:"active",createdAt:String(x.createdAt||new Date().toISOString()),updatedAt:String(x.updatedAt||x.createdAt||new Date().toISOString())}}
function routineAll(){const a=routineStore();for(let i=0;i<a.length;i++)a[i]=routineNormalize(a[i]);return a}
function routineActive(){return routineAll().filter(x=>x.status==="active")}
function routineDayNumber(d=new Date()){const n=d.getDay();return n===0?7:n}
function routineScheduledOn(r,date){return (r.days||[]).includes(routineDayNumber(date instanceof Date?date:parseLocal(date)))}
function routineExistsOn(r,dateKey){const created=String(r.createdAt||"").slice(0,10);return !validDateKey(created)||dateKey>=created}
function routineLog(routineId,dateKey){return routineLogStore().find(x=>String(x.routineId)===String(routineId)&&x.dateKey===dateKey)||null}
function routineDoneOn(r,dateKey){return !!routineLog(r.id,dateKey)}
function routineWeekStats(r){const [a,b]=weekBounds(),today=localDateKey();let scheduled=0,elapsed=0,done=0;for(let d=parseLocal(a);localDateKey(d)<=b;d=addDays(d,1)){const k=localDateKey(d);if(!routineExistsOn(r,k)||!routineScheduledOn(r,d))continue;scheduled++;if(k<=today){elapsed++;if(routineDoneOn(r,k))done++}}return {scheduled,elapsed,done,rate:elapsed?Math.round(done/elapsed*100):100}}
function routine28Stats(){let scheduled=0,done=0;for(const r of routineActive())for(let i=0;i<28;i++){const d=addDays(new Date(),-i),k=localDateKey(d);if(routineExistsOn(r,k)&&routineScheduledOn(r,d)){scheduled++;if(routineDoneOn(r,k))done++}}return {scheduled,done,rate:scheduled?Math.round(done/scheduled*100):0}}
function routineDueToday(){const today=localDateKey();return routineActive().filter(r=>routineScheduledOn(r,new Date())&&!routineDoneOn(r,today))}
function routineDecisionEngine(){return routineDueToday().map(r=>{const w=routineWeekStats(r),boost=r.priority===1?18:r.priority===2?8:0;return {id:`routine:${r.id}:${localDateKey()}`,routineId:r.id,area:r.area,kind:"routine",title:r.title,meta:`Рутина сегодня • ${w.done}/${w.elapsed||0} выполнено по прошедшим дням недели${r.minutes?` • ~${r.minutes} мин`:""}`,score:36+boost,hard:false,minutes:r.minutes||15,route:"routines"}}).sort((a,b)=>b.score-a.score).slice(0,5)}
function routineCalendarEvents(startKey,endKey){const out=[];for(const r of routineActive())for(let d=parseLocal(startKey);localDateKey(d)<=endKey;d=addDays(d,1)){const k=localDateKey(d);if(k<localDateKey()||!routineExistsOn(r,k)||!routineScheduledOn(r,d)||routineDoneOn(r,k))continue;out.push({id:`cal:routine:${r.id}:${k}`,dateKey:k,source:"routine",kind:"routine",area:r.area,title:`Рутина: ${r.title}`,meta:"Запланированная рутина",minutes:r.minutes||0,hard:false,priority:r.priority,refId:r.id,route:"routines",manual:false})}return out}
function routineAreaStat(area){return area==="Финансы"?"Финансы":area==="Работа"?"Карьера":area==="Теннис"?"Теннис":area==="Знания"?"Разум":"Дисциплина"}
async function completeRoutine(id,dateKey=localDateKey()){const r=routineAll().find(x=>x.id===id);if(!r||routineLog(id,dateKey))return;const xp=r.priority===1?15:r.priority===2?10:8;routineLogStore().push({id:uid(),routineId:id,dateKey,completedAt:new Date().toISOString(),xpAwarded:xp});addXp(xp,routineAreaStat(r.area),"Рутина выполнена",`routine:${id}:${dateKey}`,"process",dateKey);audit("Рутина выполнена","system",`${r.title} • ${dateKey}`);await save("Рутина выполнена")}
async function undoRoutine(id,dateKey=localDateKey()){const arr=routineLogStore(),i=arr.findIndex(x=>String(x.routineId)===String(id)&&x.dateKey===dateKey);if(i<0)return;const log=arr[i],r=routineAll().find(x=>x.id===id);if(log.xpAwarded&&r)removeXp(log.xpAwarded,routineAreaStat(r.area),"Откат рутины",`routine:${id}:${dateKey}`,dateKey);arr.splice(i,1);await save("Выполнение рутины отменено")}
function routineCreate(data={}){const r=routineNormalize({...data,id:uid(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});routineStore().push(r);return r}
async function saveRoutineForm(){const id=String(document.getElementById("routineEditId")?.value||""),title=String(document.getElementById("routineTitle")?.value||"").trim();if(!title){toast("Укажи рутину");return}const days=[...document.querySelectorAll?.('#routineDayPicker input[data-routine-day]:checked')||[]].map(x=>+x.value);if(!days.length){toast("Выбери хотя бы один день");return}const data={title,area:String(document.getElementById("routineArea")?.value||"Личное"),priority:clamp(Math.round(+document.getElementById("routinePriority")?.value||2),1,3),minutes:clamp(Math.round(+document.getElementById("routineMinutes")?.value||15),0,360),days,updatedAt:new Date().toISOString()},old=id?routineAll().find(x=>x.id===id):null;if(old)Object.assign(old,data);else routineCreate(data);audit(old?"Рутина обновлена":"Рутина создана","system",title);clearRoutineForm();await save(old?"Рутина обновлена":"Рутина создана")}
function routineDayPicker(days=[1,2,3,4,5,6,7]){const set=new Set(days.map(Number)),labels=[[1,"Пн"],[2,"Вт"],[3,"Ср"],[4,"Чт"],[5,"Пт"],[6,"Сб"],[7,"Вс"]];return labels.map(([n,l])=>`<label class="toggle-line"><input type="checkbox" data-routine-day value="${n}" ${set.has(n)?"checked":""}><span>${l}</span></label>`).join("")}
function clearRoutineForm(){for(const id of ["routineEditId","routineTitle"]){const el=document.getElementById(id);if(el)el.value=""}if(document.getElementById("routineArea"))document.getElementById("routineArea").value="Личное";if(document.getElementById("routinePriority"))document.getElementById("routinePriority").value="2";if(document.getElementById("routineMinutes"))document.getElementById("routineMinutes").value="20";const p=document.getElementById("routineDayPicker");if(p)p.innerHTML=routineDayPicker();const card=document.getElementById("routineEditorCard");if(card)card.hidden=true}
function editRoutine(id){const r=routineAll().find(x=>x.id===id);if(!r)return;for(const [k,v] of Object.entries({routineEditId:r.id,routineTitle:r.title,routineArea:r.area,routinePriority:r.priority,routineMinutes:r.minutes})){const el=document.getElementById(k);if(el)el.value=String(v)}const p=document.getElementById("routineDayPicker");if(p)p.innerHTML=routineDayPicker(r.days);const card=document.getElementById("routineEditorCard");if(card)card.hidden=false}
async function setRoutineStatus(id,status){const r=routineAll().find(x=>x.id===id);if(!r||!["active","paused","archived"].includes(status))return;r.status=status;r.updatedAt=new Date().toISOString();await save(status==="paused"?"Рутина на паузе":"Статус рутины обновлён")}
function ensureRoutinesOsUi(){if(document.getElementById("routinesOsCommand"))return;const grid=document.querySelector?.("#today .grid");if(!grid)return;const anchor=document.getElementById("tasksOsCommand")?.closest?.(".card")||document.getElementById("lifeOsCommand")?.closest?.(".card");if(!anchor||typeof anchor.insertAdjacentHTML!=="function")return;anchor.insertAdjacentHTML("afterend",`<div data-ux7-view="focus" class="card ux7-card span-12"><div class="split"><div><div class="eyebrow">Habits / Routines OS</div><div class="section-title">Рутины без накопления долга</div></div><button class="btn secondary small" onclick="document.getElementById('routineDayPicker').innerHTML=routineDayPicker();document.getElementById('routineEditorCard').hidden=false;document.getElementById('routineTitle').focus()">+ Рутина</button></div><div id="routinesOsCommand" style="margin-top:10px"></div><div id="routinesOsList" style="margin-top:10px"></div></div><div data-ux7-view="focus" class="card ux7-card span-12" id="routineEditorCard" hidden><div class="title">Редактор рутины</div><input id="routineEditId" type="hidden"><div class="formgrid" style="margin-top:10px"><div class="field"><label>Что повторять</label><input id="routineTitle"></div><div class="field"><label>Область</label><select id="routineArea"><option>Работа</option><option>Финансы</option><option>Теннис</option><option>Знания</option><option selected>Личное</option><option>Система</option></select></div><div class="field"><label>Приоритет</label><select id="routinePriority"><option value="1">Высокий</option><option value="2" selected>Средний</option><option value="3">Низкий</option></select></div><div class="field"><label>Оценка, мин</label><input id="routineMinutes" type="number" min="0" max="360" value="20"></div></div><div class="title" style="margin-top:12px">Дни недели</div><div id="routineDayPicker" class="formgrid" style="margin-top:7px"></div><div class="split" style="margin-top:10px"><button class="btn" onclick="saveRoutineForm()">Сохранить</button><button class="btn ghost" onclick="clearRoutineForm()">Отмена</button></div></div>`)}
function renderRoutinesOs(){const box=document.getElementById("routinesOsCommand"),list=document.getElementById("routinesOsList");if(!box||!list)return;const all=routineActive(),due=routineDueToday(),stats=routine28Stats();box.innerHTML=`<div class="report-grid"><div class="report-item"><div class="smallcaps">Активных</div><b>${all.length}</b></div><div class="report-item"><div class="smallcaps">Сегодня</div><b>${due.length}</b></div><div class="report-item"><div class="smallcaps">28 дней</div><b>${stats.rate}%</b></div><div class="report-item"><div class="smallcaps">Факт / план</div><b>${stats.done}/${stats.scheduled}</b></div></div>`;const today=localDateKey();list.innerHTML=all.length?all.map(r=>{const scheduled=routineScheduledOn(r,new Date()),done=routineDoneOn(r,today),w=routineWeekStats(r);return `<div class="quest"><span class="tag ${scheduled&&!done?"warn":""}">${escapeHtml(r.area)}</span><div class="qbody"><div class="qtitle">${escapeHtml(r.title)}</div><div class="qmeta">Неделя ${w.done}/${w.elapsed} • ${w.rate}% • ${r.minutes?`~${r.minutes} мин • `:""}${r.days.map(n=>["","Пн","Вт","Ср","Чт","Пт","Сб","Вс"][n]).join(" ")}</div></div><div class="split">${scheduled?(done?`<button class="btn ghost small" onclick="undoRoutine('${r.id}')">Отменить ✓</button>`:`<button class="btn secondary small" onclick="completeRoutine('${r.id}')">✓</button>`):""}<button class="btn ghost small" onclick="editRoutine('${r.id}')">Изм.</button><button class="btn ghost small" onclick="setRoutineStatus('${r.id}','paused')">Пауза</button></div></div>`}).join(""):'<div class="empty">Рутин пока нет.</div>'}

const routinesLegacyActiveDay=activeDay;
activeDay=function(dateKey){return routinesLegacyActiveDay(dateKey)||routineLogStore().some(x=>x.dateKey===dateKey)};
