"use strict";

/* RPG Growth — evidence-backed domain levels and progression milestones. */
function rpgGrowthLevelForXp(xp){xp=Math.max(0,+xp||0);return Math.min(25,1+Math.floor(Math.sqrt(xp/80)))}
function rpgGrowthLevelThreshold(level){return Math.max(0,80*Math.pow(Math.max(0,level-1),2))}
function rpgGrowthDomainRows(){const map=[
  {name:"Финансы",stat:"Финансы"},{name:"Знания",stat:"Разум"},{name:"Теннис",stat:"Теннис"},{name:"Тело",stat:"Тело"},{name:"Отношения",stat:"Отношения"},{name:"Система",stat:"Дисциплина"}
];return map.map(x=>{const xp=Math.max(0,+S.stats?.[x.stat]||0),level=rpgGrowthLevelForXp(xp),prev=rpgGrowthLevelThreshold(level),next=rpgGrowthLevelThreshold(level+1),pct=next>prev?clamp((xp-prev)/(next-prev)*100,0,100):100;return {...x,xp,level,pct,next}})}
function rpgGrowthEvidence(){const k=typeof knowledgeGrowthCaptureStats==="function"?knowledgeGrowthCaptureStats(28):{sessions:0,rate:0},notes=typeof knowledgeGrowthNotes==="function"?knowledgeGrowthNotes():[],apps=typeof knowledgeGrowthApplications==="function"?knowledgeGrowthApplications(30):0,tg=typeof tennisGrowthExposure==="function"?tennisGrowthExposure(30):{sessions:0,exact:0},matches=typeof tennisAllMatches==="function"?tennisAllMatches().length:0,habits=typeof habitStrengthRows==="function"?habitStrengthRows():[],events=typeof lifeTimelineEvents==="function"?lifeTimelineEvents(30):[],time=events.reduce((s,x)=>s+(+x.durationMin||0),0),strong=habits.filter(x=>x.strength>=80).length;return {knowledgeSessions:k.sessions,captureRate:k.rate,knowledgeNotes:notes.length,applications:apps,tennisSessions:tg.sessions,tennisExact:tg.exact,matches,habits:habits.length,strongHabits:strong,avgHabit:habits.length?habits.reduce((s,x)=>s+x.strength,0)/habits.length:0,events:events.length,time}}
function rpgGrowthMilestones(){const e=rpgGrowthEvidence();return [
  {id:"observer",title:"Наблюдатель",desc:"30 событий в единой временной шкале",done:e.events>=30,progress:Math.min(e.events,30),target:30},
  {id:"rhythm",title:"Устойчивый ритм",desc:"Хотя бы одна привычка с силой 80%+",done:e.strongHabits>=1,progress:e.strongHabits?1:0,target:1},
  {id:"knowledge",title:"Извлекаю знания",desc:"10 сохранённых идей / вопросов / применений",done:e.knowledgeNotes>=10,progress:Math.min(e.knowledgeNotes,10),target:10},
  {id:"apply",title:"Переношу в жизнь",desc:"5 применений знаний за 30 дней",done:e.applications>=5,progress:Math.min(e.applications,5),target:5},
  {id:"tennisdata",title:"Тренирую осознанно",desc:"5 тренировок с точной разбивкой по навыкам",done:e.tennisExact>=5,progress:Math.min(e.tennisExact,5),target:5},
  {id:"time",title:"Вижу время",desc:"10 часов фактической активности в трекинге за 30 дней",done:e.time>=600,progress:Math.min(Math.round(e.time),600),target:600}
]}
function rpgGrowthNextMilestones(){return rpgGrowthMilestones().filter(x=>!x.done).sort((a,b)=>(b.progress/b.target)-(a.progress/a.target)).slice(0,4)}
function ensureRpgGrowthUi(){if(document.getElementById("rpgGrowthCommand"))return;const anchor=document.getElementById("monthlyLifeReport")?.closest(".card"),grid=document.querySelector("#more .grid");if(!anchor||!grid)return;anchor.insertAdjacentHTML("afterend",`<div data-ux7-view="overview" class="card ux7-card span-12"><div class="eyebrow">RPG / Growth 2</div><div class="section-title">Уровни отражают накопленный факт</div><div class="muted" style="margin-top:6px">Уровень домена считается только из уже заработанного XP. Отдельно показываются проверяемые milestones — без штрафов за пропуски.</div><div id="rpgGrowthCommand" style="margin-top:10px"></div><div class="title" style="margin-top:14px">Фактическая прокачка</div><div id="rpgGrowthEvidence" style="margin-top:8px"></div><div class="title" style="margin-top:14px">Milestones</div><div id="rpgGrowthMilestones" style="margin-top:8px"></div></div>`)}
function renderRpgGrowth(){const box=document.getElementById("rpgGrowthCommand"),eBox=document.getElementById("rpgGrowthEvidence"),mBox=document.getElementById("rpgGrowthMilestones");if(!box||!eBox||!mBox)return;const rows=rpgGrowthDomainRows(),e=rpgGrowthEvidence(),ms=rpgGrowthMilestones();box.innerHTML=`<div class="stats-list">${rows.map(x=>`<div class="stat-row"><div class="stat-name">${escapeHtml(x.name)} Lv.${x.level}</div><div class="statbar"><i style="width:${x.pct}%"></i></div><div class="stat-xp">${x.xp}/${x.next}</div></div>`).join("")}</div>`;eBox.innerHTML=`<div class="report-grid"><div class="report-item"><div class="smallcaps">Habit strength</div><b>${Math.round(e.avgHabit)}%</b><div class="sub">сильных ${e.strongHabits}/${e.habits}</div></div><div class="report-item"><div class="smallcaps">Знаний</div><b>${e.knowledgeNotes}</b><div class="sub">захват ${Math.round(e.captureRate)}%</div></div><div class="report-item"><div class="smallcaps">Применений 30д</div><b>${e.applications}</b></div><div class="report-item"><div class="smallcaps">Теннис: точных сессий</div><b>${e.tennisExact}/${e.tennisSessions}</b></div><div class="report-item"><div class="smallcaps">Событий 30д</div><b>${e.events}</b></div><div class="report-item"><div class="smallcaps">Факт времени 30д</div><b>${Math.round(e.time/6)/10} ч</b></div></div>`;mBox.innerHTML=ms.map(x=>`<div class="log-item"><div class="split"><div><span class="tag ${x.done?"good":""}">${x.done?"✓":"в процессе"}</span><div class="qtitle" style="margin-top:5px">${escapeHtml(x.title)}</div><div class="qmeta">${escapeHtml(x.desc)}</div></div><b>${x.progress}/${x.target}</b></div></div>`).join("")}
