"use strict";

/* Life RPG 11.0.0 — Automation / Rules OS
   Transparent heuristics only. Domain engines remain authoritative for finance/CRM/projects. */

function ruleToggles(){if(!S.settings.ruleToggles||typeof S.settings.ruleToggles!=="object")S.settings.ruleToggles={};return S.settings.ruleToggles}
function ruleEnabled(id){return ruleToggles()[id]!==false}
function ruleDefinitions(){return [
  {id:"calendar-tomorrow-overload",title:"Завтрашняя перегрузка → Life OS",description:"Если завтра плановая нагрузка превышает дневной лимит, поднять системное предупреждение.",kind:"cross",evaluate(){const k=localDateKey(addDays(new Date(),1)),d=typeof calendarDayLoad==="function"?calendarDayLoad(k):null;return d?.level==="bad"?{id:"rule:calendar-tomorrow-overload",kind:"rule-calendar",area:"Система",title:"Разгрузить завтрашний календарь",meta:`${fmtDate(parseLocal(k))} • ~${d.minutes}/${d.capacity} мин • событий ${d.rows.length}`,score:64,hard:false,route:"calendar",minutes:10}:null}},
  {id:"portfolio-over-wip",title:"WIP проектов превышен → Review",description:"Если активных проектов больше WIP-лимита, предложить пересмотреть портфель.",kind:"cross",evaluate(){if(typeof projectActive!=="function"||typeof reviewWipLimit!=="function")return null;const n=projectActive().length,lim=reviewWipLimit();return n>lim?{id:"rule:portfolio-over-wip",kind:"rule-wip",area:"Система",title:"Сократить число активных проектов",meta:`Активных ${n} при WIP-лимите ${lim}. Review OS предложит кандидатов на паузу.`,score:58,hard:false,route:"rules",minutes:15}:null}},
  {id:"work-vs-nonwork-load",title:"Дефицит рабочего темпа + высокая внешняя нагрузка",description:"Если рабочий темп ниже плана, а сегодня/завтра много непроизводственной нагрузки, показать конфликт ресурсов.",kind:"cross",evaluate(){const w=typeof workPaceData==="function"?workPaceData():null;if(!w||w.plan<=0||w.paceDelta>=0||typeof calendarEvents!=="function")return null;const a=localDateKey(),b=localDateKey(addDays(new Date(),1)),mins=calendarEvents(2,0).filter(e=>e.manual&&e.dateKey>=a&&e.dateKey<=b&&e.area!=="Работа"&&e.status!=="done").reduce((s,e)=>s+(+e.minutes||0),0);return mins>=180?{id:"rule:work-vs-nonwork-load",kind:"rule-conflict",area:"Работа",title:"Защитить рабочий фокус",meta:`Рабочий темп ниже плана, при этом на сегодня/завтра ~${mins} мин непроизводственных планов.`,score:57,hard:false,route:"rules",minutes:10}:null}},
  {id:"inbox-aging",title:"Старый Inbox → разбор",description:"Если входящие не разобраны 3+ дня, поднять отдельное системное действие.",kind:"cross",evaluate(){const rows=typeof inboxOpen==="function"?inboxOpen():[],old=rows.filter(x=>typeof inboxAgeDays==="function"&&inboxAgeDays(x)>=3);return old.length?{id:"rule:inbox-aging",kind:"rule-inbox",area:"Система",title:"Разобрать старые входящие",meta:`Старше 3 дней: ${old.length} из ${rows.length}.`,score:55,hard:false,route:"inbox",minutes:Math.min(30,old.length*4)}:null}},
  {id:"task-overdue-stack",title:"Стек просроченных задач → перепланирование",description:"Если просрочено 3+ задач, не добавлять новые — сначала перепланировать хвост.",kind:"cross",evaluate(){const over=typeof taskActive==="function"?taskActive().filter(t=>taskHealth(t).overdue):[];return over.length>=3?{id:"rule:task-overdue-stack",kind:"rule-task-stack",area:"Система",title:"Разобрать стек просроченных задач",meta:`Просрочено задач: ${over.length}. Заверши, перенеси или отмени хвост.`,score:69,hard:false,route:"tasks",minutes:20}:null}},
  {id:"goal-overload",title:"Слишком много активных целей → Review",description:"Если активных целей больше пяти, предложить сократить число одновременно поддерживаемых направлений.",kind:"cross",evaluate(){const n=typeof goalActive==="function"?goalActive().length:0;return n>5?{id:"rule:goal-overload",kind:"rule-goals",area:"Система",title:"Сократить число активных целей",meta:`Активных целей ${n}. Оставь рабочий набор горизонтов, остальные поставь на паузу.`,score:54,hard:false,route:"goals",minutes:15}:null}},
  {id:"crm-overdue",title:"Просроченный CRM → Work/Life OS",description:"Делегировано Work OS: просроченный следующий шаг автоматически получает высокий приоритет.",kind:"delegated"},
  {id:"finance-overdue",title:"Просроченный платёж → Finance/Life OS",description:"Делегировано Finance OS: обязательные платежи остаются выше мягких целей.",kind:"delegated"},
  {id:"project-stale",title:"Застрявший проект → Projects/Review OS",description:"Делегировано Projects OS: отсутствие следующего шага, просрочка и застой уже контролируются.",kind:"delegated"}
]}
function rulesEvaluate(){const out=[];for(const r of ruleDefinitions())if(r.kind!=="delegated"&&ruleEnabled(r.id)){try{const x=r.evaluate?.();if(x)out.push({...x,ruleId:r.id})}catch{}}return out.sort((a,b)=>b.score-a.score)}
function ruleEngineActions(){return rulesEvaluate()}
async function toggleRule(id){ruleToggles()[id]=!ruleEnabled(id);await save(ruleEnabled(id)?"Правило включено":"Правило выключено")}
function ensureRulesOsUi(){if(document.getElementById("rulesOsCommand"))return;const grid=document.querySelector?.("#more .grid");if(!grid)return;const anchor=document.getElementById("calendarOsCommand")?.closest?.(".card")||grid.lastElementChild;if(!anchor||typeof anchor.insertAdjacentHTML!=="function")return;anchor.insertAdjacentHTML("afterend",`<div data-ux7-view="overview" class="card ux7-card span-6"><div class="eyebrow">Automation / Rules OS</div><div class="section-title">Правила автоматизации</div><div class="muted" style="margin-top:6px">Правила только поднимают приоритеты и конфликты. Никаких автоматических платежей, пауз проектов или удаления данных.</div><div id="rulesOsCommand" style="margin-top:10px"></div></div>`)}
function renderRulesOs(){const box=document.getElementById("rulesOsCommand");if(!box)return;const fired=new Map(rulesEvaluate().map(x=>[x.ruleId,x]));box.innerHTML=ruleDefinitions().map(r=>{const f=fired.get(r.id),delegated=r.kind==="delegated",enabled=delegated||ruleEnabled(r.id);return `<div class="log-item"><div class="split"><div><div class="qtitle">${escapeHtml(r.title)}</div><div class="qmeta">${escapeHtml(r.description)}</div></div><span class="tag ${f?"warn":""}">${f?"Сработало":delegated?"Встроено":enabled?"Вкл.":"Выкл."}</span></div>${f?`<div class="status" style="margin-top:7px">${escapeHtml(f.meta)}</div>`:""}${delegated?"":`<button class="btn ghost small" style="margin-top:7px" onclick="toggleRule('${r.id}')">${enabled?"Выключить":"Включить"}</button>`}</div>`}).join("")}
