"use strict";

/* Life RPG 13.1 — Mobile Automation & Share Hub.
   Receives Android/PWA shares, keeps files in a separate IndexedDB queue,
   routes through existing preview-first import engines, and stores only compact history in S. */

const SHARE131_DB="life-rpg-share-13.1";
const SHARE131_DB_VERSION=1;
const SHARE131_STORE="queue";
let SHARE131_ICS_PREVIEW=null,SHARE131_LAUNCH_HANDLED=false,SHARE131_LAUNCH_QUEUE_INSTALLED=false,SHARE131_RENDER_SEQ=0;

function share131State(){
  S.settings=S.settings||{};let x=S.settings.shareHub131;if(!x||typeof x!=="object"||Array.isArray(x))x={};
  if(!Array.isArray(x.history))x.history=[];if(!Array.isArray(x.fingerprints))x.fingerprints=[];x.version=1;S.settings.shareHub131=x;return x
}
function share131OpenDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(SHARE131_DB,SHARE131_DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(SHARE131_STORE))db.createObjectStore(SHARE131_STORE,{keyPath:"id"})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error("Share Queue недоступна"))})}
async function share131DbRun(mode,fn){const db=await share131OpenDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(SHARE131_STORE,mode),store=tx.objectStore(SHARE131_STORE);let result;try{result=fn(store,tx)}catch(e){reject(e);return}tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error||new Error("Share Queue error"));tx.onabort=()=>reject(tx.error||new Error("Share Queue aborted"))})}finally{db.close()}}
async function share131QueueAll(){const db=await share131OpenDb();try{return await new Promise((resolve,reject)=>{const req=db.transaction(SHARE131_STORE,"readonly").objectStore(SHARE131_STORE).getAll();req.onsuccess=()=>resolve((req.result||[]).sort((a,b)=>String(b.receivedAt||"").localeCompare(String(a.receivedAt||""))));req.onerror=()=>reject(req.error)})}finally{db.close()}}
async function share131QueueGet(id){const db=await share131OpenDb();try{return await new Promise((resolve,reject)=>{const req=db.transaction(SHARE131_STORE,"readonly").objectStore(SHARE131_STORE).get(id);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)})}finally{db.close()}}
async function share131QueuePut(row){const db=await share131OpenDb();try{await new Promise((resolve,reject)=>{const tx=db.transaction(SHARE131_STORE,"readwrite");tx.objectStore(SHARE131_STORE).put(row);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});return row}finally{db.close()}}
async function share131QueueDelete(id){const db=await share131OpenDb();try{await new Promise((resolve,reject)=>{const tx=db.transaction(SHARE131_STORE,"readwrite");tx.objectStore(SHARE131_STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}finally{db.close()}}
async function share131QueuePatch(id,patch){const row=await share131QueueGet(id);if(!row)return null;Object.assign(row,patch);return share131QueuePut(row)}
function share131FileObj(x){if(!x)return null;if(typeof File!=="undefined"&&x.blob instanceof File)return x.blob;return new File([x.blob],x.name||"shared-file",{type:x.type||"application/octet-stream",lastModified:+x.lastModified||Date.now()})}
function share131Files(row){return (row?.files||[]).map(share131FileObj).filter(Boolean)}
function share131Ext(name){const m=String(name||"").toLowerCase().match(/\.([a-z0-9]+)$/);return m?m[1]:""}
function share131CombinedText(row){return [row?.title,row?.text,row?.url].map(x=>String(x||"").trim()).filter(Boolean).join("\n")}
function share131Classify(row){
  const files=row?.files||[],text=share131CombinedText(row),low=text.toLowerCase();if(!files.length)return text?"inbox":"error";
  const exts=files.map(x=>share131Ext(x.name)),types=files.map(x=>String(x.type||"").toLowerCase());
  if(exts.some(x=>x==="ics")||types.some(x=>x==="text/calendar"))return"calendar";
  if(exts.every(x=>["json","lrpg","csv","pdf","xlsx","xls"].includes(x)))return"import";
  if(files.every((x,i)=>types[i].startsWith("image/")||["png","jpg","jpeg","webp"].includes(exts[i]))){if(/huawei|watch fit|health|пульс|аэроб|анаэроб|трениров/.test(low)||files.some(x=>/huawei|health|watch/i.test(x.name)))return"huawei";return"image"}
  if(exts.some(x=>["json","lrpg","csv","pdf","xlsx","xls"].includes(x)))return"import";return"files"
}
async function share131Sha(bytes){if(globalThis.crypto?.subtle){const hash=await crypto.subtle.digest("SHA-256",bytes),a=[...new Uint8Array(hash)];return a.map(x=>x.toString(16).padStart(2,"0")).join("")}let h=2166136261;for(const b of new Uint8Array(bytes)){h^=b;h=Math.imul(h,16777619)}return(h>>>0).toString(16)}
async function share131Fingerprint(row){
  const enc=new TextEncoder(),parts=[share131CombinedText(row),String(row?.files?.length||0)];
  for(const f of share131Files(row)){parts.push(`${f.name}|${f.type}|${f.size}|${f.lastModified}`);const buf=await f.arrayBuffer();parts.push(await share131Sha(buf))}
  return "share131:"+await share131Sha(enc.encode(parts.join("\n")))
}
function share131Remember(fp){if(!fp)return;const s=share131State(),set=new Set(s.fingerprints);set.add(fp);s.fingerprints=[...set].slice(-5000)}
function share131HistoryAdd(row){const s=share131State(),x={id:uid(),at:new Date().toISOString(),...row};s.history.unshift(x);s.history=s.history.slice(0,100);return x}
function share131KindLabel(k){return({inbox:"Inbox",import:"Import Hub",calendar:"Календарь ICS",huawei:"Huawei / Training",image:"Скриншот",files:"Файл",error:"Ошибка"})[k]||k}
function share131SafeText(v){return escapeHtml(String(v||""))}
async function share131DedupQueue(){
  const rows=await share131QueueAll(),known=new Set(share131State().fingerprints),local=new Set();let removed=0;
  for(const row of rows){let fp="";try{fp=await share131Fingerprint(row)}catch{}if(fp&&(known.has(fp)||local.has(fp))){share131HistoryAdd({status:"duplicate",route:share131Classify(row),name:(row.files||[])[0]?.name||row.title||"Share",detail:"Повторный share удалён из очереди"});await share131QueueDelete(row.id);removed++;continue}if(fp)local.add(fp)}
  if(removed)await persist();return removed
}
async function share131CaptureText(row,auto=false){const text=share131CombinedText(row);if(!text)return false;const fp=await share131Fingerprint(row);if(share131State().fingerprints.includes(fp)){await share131QueueDelete(row.id);return false}const x=typeof inboxCapture==="function"?inboxCapture(text):null;if(!x)throw new Error("Inbox OS недоступен");share131Remember(fp);share131HistoryAdd({status:"written",route:"inbox",name:row.title||row.url||"Текст",detail:`Inbox • ${x.id}`,queueId:""});await share131QueueDelete(row.id);audit("Share Hub → Inbox","system",text.slice(0,140));await save(auto?"Shared текст сохранён в Inbox":"Текст сохранён в Inbox");return true}
async function share131RouteImport(id,index=0){const row=await share131QueueGet(id);if(!row)return;const file=share131Files(row)[index];if(!file){toast("Файл не найден");return}await import127Prepare({files:[file],value:""});await share131QueuePatch(id,{status:"routed",routedAt:new Date().toISOString(),route:"import"});share131HistoryAdd({status:"routed",route:"import",name:file.name,detail:"Передан в Import Hub preview",queueId:id});await persist();ux7Go("more","settings");setTimeout(()=>document.getElementById("import127Command")?.closest(".card")?.scrollIntoView({behavior:"smooth",block:"start"}),120);renderShare131()}
async function share131RouteHuawei(id,index=0){const row=await share131QueueGet(id);if(!row)return;const file=share131Files(row)[index];if(!file||typeof training129ReadHuaweiFile!=="function"){toast("Huawei importer недоступен");return}await training129ReadHuaweiFile(file);await share131QueuePatch(id,{status:"routed",routedAt:new Date().toISOString(),route:"huawei"});share131HistoryAdd({status:"routed",route:"huawei",name:file.name,detail:"Передан в Training OS; цифры требуют подтверждения",queueId:id});await persist();renderShare131()}
async function share131RouteFinanceImage(id,index=0){return share131RouteImport(id,index)}
function share131IcsUnescape(v){return String(v||"").replace(/\\n/gi,"\n").replace(/\\,/g,",").replace(/\\;/g,";").replace(/\\\\/g,"\\")}
function share131IcsDate(v){const m=String(v||"").match(/(\d{4})(\d{2})(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:""}
function share131IcsMinutes(v){const m=String(v||"").match(/^PT(?:(\d+)H)?(?:(\d+)M)?/i);return m?(+m[1]||0)*60+(+m[2]||0):0}
function share131IcsType(title,description=""){const s=`${title} ${description}`.toLowerCase();if(/турнир/.test(s))return"Турнир";if(/тренир|теннис|спорт|бег|ходьб|кардио/.test(s))return"Тренировка";if(/работ|crm|клиент|встреч/.test(s))return"Работа";if(/плат|долг|финанс/.test(s))return"Финансы";if(/чтен|книг|обуч/.test(s))return"Знания";return"Личное"}
function share131ParseIcs(text){
  const unfolded=String(text||"").replace(/\r/g,"").replace(/\n[ \t]/g,""),blocks=[...unfolded.matchAll(/BEGIN:VEVENT\n([\s\S]*?)\nEND:VEVENT/g)].map(m=>m[1]),rows=[];
  for(const block of blocks){const lines=block.split("\n"),get=name=>{const l=lines.find(x=>x.toUpperCase().startsWith(name+":")||x.toUpperCase().startsWith(name+";"));return l?l.slice(l.indexOf(":")+1):""},title=share131IcsUnescape(get("SUMMARY"))||"Событие",description=share131IcsUnescape(get("DESCRIPTION")),dateKey=share131IcsDate(get("DTSTART")),minutes=share131IcsMinutes(get("DURATION"));if(!validDateKey(dateKey))continue;rows.push({title,description,dateKey,minutes,type:share131IcsType(title,description)})}
  return rows
}
async function share131PrepareIcs(id,index=0){const row=await share131QueueGet(id);if(!row)return;const file=share131Files(row)[index];if(!file)return;const rows=share131ParseIcs(await file.text()),existing=new Set((typeof calendarManualEvents==="function"?calendarManualEvents():[]).map(x=>`${x.dateKey}|${String(x.title||"").toLowerCase()}`));SHARE131_ICS_PREVIEW={queueId:id,fileName:file.name,rows:rows.map(x=>({...x,duplicate:existing.has(`${x.dateKey}|${x.title.toLowerCase()}`)}))};await share131QueuePatch(id,{status:"preview",routedAt:new Date().toISOString(),route:"calendar"});renderShare131()}
async function share131ApplyIcs(){const p=SHARE131_ICS_PREVIEW;if(!p)return;const rows=p.rows.filter(x=>!x.duplicate);if(!rows.length){toast("Новых событий нет");return}if(!confirm(`Добавить ${rows.length} событий в Calendar OS?`))return;await createPreActionSnapshot(`Share Hub ICS • ${p.fileName}`);for(const x of rows)addCalendarPlan({title:x.title,dateKey:x.dateKey,type:x.type,minutes:x.minutes,priority:2,note:x.description||`Импорт ICS • ${p.fileName}`,repeatWeeks:1});const row=await share131QueueGet(p.queueId),fp=row?await share131Fingerprint(row):"";share131Remember(fp);share131HistoryAdd({status:"written",route:"calendar",name:p.fileName,detail:`Calendar OS • ${rows.length} событий`});await share131QueueDelete(p.queueId);SHARE131_ICS_PREVIEW=null;audit("Share Hub → Calendar","system",`${rows.length} событий из ${p.fileName}`);await save(`ICS: добавлено ${rows.length} событий`);renderShare131()}
function share131IcsEscape(v){return String(v||"").replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;")}
function share131IcsDateOut(k){return String(k||"").replaceAll("-","")}
function share131DownloadBlob(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
function share131ExportIcs(){const rows=(typeof calendarManualEvents==="function"?calendarManualEvents():[]).filter(x=>x.status!=="cancelled"&&validDateKey(x.dateKey));const lines=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Life RPG//13.1//RU","CALSCALE:GREGORIAN"];for(const x of rows){lines.push("BEGIN:VEVENT",`UID:${share131IcsEscape(x.id)}@life-rpg`,`DTSTART;VALUE=DATE:${share131IcsDateOut(x.dateKey)}`,`SUMMARY:${share131IcsEscape(x.title)}`,`DESCRIPTION:${share131IcsEscape(x.note||"")}`,x.minutes?`DURATION:PT${Math.max(1,Math.round(+x.minutes||0))}M`:"","END:VEVENT")}lines.push("END:VCALENDAR");share131DownloadBlob(new Blob([lines.filter(Boolean).join("\r\n")],{type:"text/calendar;charset=utf-8"}),`life-rpg-calendar-${localDateKey()}.ics`);share131HistoryAdd({status:"exported",route:"calendar",name:"ICS export",detail:`${rows.length} событий`});persist()}
async function share131MarkDone(id){const row=await share131QueueGet(id);if(!row)return;const fp=await share131Fingerprint(row);share131Remember(fp);share131HistoryAdd({status:"completed",route:row.route||share131Classify(row),name:(row.files||[])[0]?.name||row.title||"Share",detail:"Источник удалён из локальной очереди"});await share131QueueDelete(id);await persist();renderShare131()}
async function share131Discard(id){await share131QueueDelete(id);share131HistoryAdd({status:"discarded",route:"",name:"Share",detail:"Удалено без импорта"});await persist();renderShare131()}
async function share131EnqueueFiles(files,source="manual"){const arr=[...files].slice(0,10);if(!arr.length)return;const row={id:uid(),receivedAt:new Date().toISOString(),source,title:source==="camera"?"Камера":"Файл",text:"",url:"",files:arr.map(f=>({name:f.name||`image-${Date.now()}.jpg`,type:f.type||"application/octet-stream",size:f.size||0,lastModified:f.lastModified||Date.now(),blob:f})),errors:[],status:"queued",routedAt:""};await share131QueuePut(row);share131HistoryAdd({status:"received",route:share131Classify(row),name:row.files[0]?.name||"Файл",detail:`${row.files.length} файл(а)`});await persist();await renderShare131();return row}
async function share131FileInput(input,source="manual"){try{await share131EnqueueFiles(input?.files||[],source)}finally{if(input)input.value=""}}
async function share131Clipboard(){try{const text=await navigator.clipboard.readText();if(!text.trim()){toast("Буфер пуст");return}const row={id:uid(),receivedAt:new Date().toISOString(),source:"clipboard",title:"Буфер обмена",text,url:"",files:[],errors:[],status:"queued",routedAt:""};await share131QueuePut(row);await share131CaptureText(row)}catch(e){toast("Не удалось прочитать буфер обмена")}}
async function share131ManualText(){const el=document.getElementById("share131Text"),text=String(el?.value||"").trim();if(!text){toast("Вставь текст или ссылку");return}const row={id:uid(),receivedAt:new Date().toISOString(),source:"manual-text",title:"Ручной захват",text,url:"",files:[],errors:[],status:"queued",routedAt:""};await share131QueuePut(row);if(el)el.value="";await share131CaptureText(row)}
async function share131AutoRoute(row){const kind=share131Classify(row);if(kind==="inbox")return share131CaptureText(row,true);if(kind==="import")return share131RouteImport(row.id,0);if(kind==="calendar")return share131PrepareIcs(row.id,0);if(kind==="huawei")return share131RouteHuawei(row.id,0);return false}
async function share131HandleLaunch(){
  if(SHARE131_LAUNCH_HANDLED)return;SHARE131_LAUNCH_HANDLED=true;const q=new URLSearchParams(location.search),shared=q.get("share")==="1",error=q.get("share-error")==="1";if(!shared&&!error)return;
  ux7Go("more","settings");setTimeout(()=>document.getElementById("share131Command")?.closest(".card")?.scrollIntoView({behavior:"smooth",block:"start"}),160);if(error){toast("Android Share не удалось сохранить");return}
  await share131DedupQueue();const requested=q.get("id"),rows=await share131QueueAll(),row=rows.find(x=>x.id===requested)||rows[0];if(row&&row.status==="queued")await share131AutoRoute(row);history.replaceState?.(null,"",location.pathname+location.hash)
}
function share131InstallLaunchQueue(){if(SHARE131_LAUNCH_QUEUE_INSTALLED||!globalThis.launchQueue?.setConsumer)return;SHARE131_LAUNCH_QUEUE_INSTALLED=true;launchQueue.setConsumer(async params=>{const files=[];for(const h of params.files||[])try{files.push(await h.getFile())}catch{}if(files.length){const row=await share131EnqueueFiles(files,"file-handler");if(row)await share131AutoRoute(row)}})}
function share131QueueRowHtml(row){const kind=share131Classify(row),file=(row.files||[])[0],name=file?.name||row.title||row.url||"Share",meta=[share131KindLabel(kind),row.files?.length?`${row.files.length} файл(а)`:"",row.status&&row.status!=="queued"?row.status:"",...(row.errors||[])].filter(Boolean).join(" • ");let actions="";if(kind==="inbox")actions=`<button class="btn secondary small" onclick="share131CaptureTextById('${row.id}')">В Inbox</button>`;else if(kind==="calendar")actions=`<button class="btn secondary small" onclick="share131PrepareIcs('${row.id}',0)">ICS preview</button>`;else if(kind==="huawei")actions=`<button class="btn secondary small" onclick="share131RouteHuawei('${row.id}',0)">Huawei</button>`;else if(kind==="image")actions=`<button class="btn secondary small" onclick="share131RouteFinanceImage('${row.id}',0)">Банк</button><button class="btn ghost small" onclick="share131RouteHuawei('${row.id}',0)">Huawei</button>`;else actions=`<button class="btn secondary small" onclick="share131RouteImport('${row.id}',0)">Import Hub</button>`;if(row.status==="routed"||row.status==="preview")actions+=`<button class="btn ghost small" onclick="share131MarkDone('${row.id}')">Готово</button>`;actions+=`<button class="btn ghost small" onclick="share131Discard('${row.id}')">×</button>`;return `<div class="log-item"><div class="qtitle">${share131SafeText(name)}</div><div class="qmeta">${share131SafeText(meta)}</div><div class="split" style="margin-top:8px">${actions}</div></div>`}
async function share131CaptureTextById(id){const row=await share131QueueGet(id);if(row)await share131CaptureText(row)}
function share131IcsPreviewHtml(){const p=SHARE131_ICS_PREVIEW;if(!p)return"";const fresh=p.rows.filter(x=>!x.duplicate),dup=p.rows.length-fresh.length;return `<div class="notice" style="margin-top:10px"><b>ICS preview:</b> ${share131SafeText(p.fileName)} • новых ${fresh.length} • дублей ${dup}<div style="margin-top:8px">${p.rows.slice(0,8).map(x=>`<div class="qmeta">${share131SafeText(x.dateKey)} • ${share131SafeText(x.title)}${x.duplicate?" • дубль":""}</div>`).join("")}</div><button class="btn secondary small" style="margin-top:8px" onclick="share131ApplyIcs()" ${fresh.length?"":"disabled"}>Добавить в Calendar OS</button></div>`}
function share131HistoryHtml(){const rows=share131State().history.slice(0,20);return rows.length?rows.map(x=>`<div class="log-item"><div class="qtitle">${share131SafeText(x.name||share131KindLabel(x.route))}</div><div class="qmeta">${new Date(x.at).toLocaleString("ru-RU")} • ${share131SafeText(x.status||"")} • ${share131SafeText(x.detail||"")}</div></div>`).join(""):'<div class="empty">История Share Hub пока пуста.</div>'}
function share131PatchQuickSheet(){const grid=document.querySelector("#ux7QuickSheet .ux7-action-grid");if(!grid||grid.querySelector('[data-share131-action="1"]'))return;const b=document.createElement("button");b.type="button";b.dataset.share131Action="1";b.innerHTML=`${typeof ui82Icon==="function"?ui82Icon("plus"):""}<span>Share Inbox</span>`;b.addEventListener("click",()=>{closeModal("ux7QuickSheet");ux7Go("more","settings");setTimeout(()=>document.getElementById("share131Command")?.closest(".card")?.scrollIntoView({behavior:"smooth",block:"start"}),120)});grid.appendChild(b);window.LifePlatform?.refreshIcons?.(grid)}
function ensureShare131Ui(){
  share131InstallLaunchQueue();share131PatchQuickSheet();if(document.getElementById("share131Command"))return;const grid=document.querySelector("#more .grid");if(!grid)return;const anchor=document.getElementById("import127Command")?.closest(".card")||grid.lastElementChild;
  anchor?.insertAdjacentHTML("afterend",`<div data-ux7-view="settings" class="card ux7-card span-12"><div class="eyebrow">Mobile Automation & Share Hub 13.1</div><div class="section-title">Поделиться → Life RPG</div><div class="sub">Android Share Target, камера, буфер, файлы и ICS. Бинарные файлы лежат только в локальной Share Queue; финальные записи проходят через существующие preview/confirm-пути.</div><div id="share131Command" style="margin-top:12px"></div><div class="split" style="margin-top:10px"><label class="btn secondary">Файл<input id="share131File" type="file" multiple accept="image/*,.json,.lrpg,.csv,.pdf,.xlsx,.xls,.ics,text/calendar" style="display:none" onchange="share131FileInput(this,'manual')"></label><label class="btn ghost">Камера<input id="share131Camera" type="file" accept="image/*" capture="environment" style="display:none" onchange="share131FileInput(this,'camera')"></label><button class="btn ghost" onclick="share131Clipboard()">Буфер</button><button class="btn ghost" onclick="exportBackup(false)">Backup JSON</button><button class="btn ghost" onclick="share131ExportIcs()">Экспорт ICS</button></div><div class="field" style="margin-top:10px"><label>Текст / ссылка</label><textarea id="share131Text" rows="2" placeholder="Вставить в Inbox"></textarea></div><button class="btn secondary small" style="margin-top:8px" onclick="share131ManualText()">В Inbox</button><div id="share131IcsPreview"></div><div class="title" style="margin-top:14px">Очередь</div><div id="share131Queue"></div><details style="margin-top:12px"><summary>История маршрутизации</summary><div id="share131History" style="margin-top:8px"></div></details></div>`)
}
async function renderShare131(){const seq=++SHARE131_RENDER_SEQ,box=document.getElementById("share131Command"),queue=document.getElementById("share131Queue"),historyBox=document.getElementById("share131History"),ics=document.getElementById("share131IcsPreview");if(!box||!queue||!historyBox||!ics)return;let rows=[];try{rows=await share131QueueAll()}catch(e){if(seq===SHARE131_RENDER_SEQ)box.innerHTML=`<div class="notice">Share Queue недоступна: ${share131SafeText(e.message)}</div>`;return}if(seq!==SHARE131_RENDER_SEQ)return;box.innerHTML=`<div class="report-grid"><div class="report-item"><div class="smallcaps">В очереди</div><b>${rows.length}</b></div><div class="report-item"><div class="smallcaps">История</div><b>${share131State().history.length}</b></div><div class="report-item"><div class="smallcaps">Дедуп fingerprints</div><b>${share131State().fingerprints.length}</b></div><div class="report-item"><div class="smallcaps">Android Share</div><b>${"serviceWorker" in navigator?"готов":"—"}</b></div></div>`;queue.innerHTML=rows.length?rows.map(share131QueueRowHtml).join(""):'<div class="empty">Очередь пуста. В Android используй «Поделиться → Life RPG».</div>';historyBox.innerHTML=share131HistoryHtml();ics.innerHTML=share131IcsPreviewHtml();setTimeout(()=>share131HandleLaunch().catch(e=>toast(String(e?.message||e))),0)}
