"use strict";
const fs=require("fs"),path=require("path"),assert=require("assert"),root=__dirname,read=n=>fs.readFileSync(path.join(root,n),"utf8"),RELEASE="13.0.0";
const core=read("core.js"),manifest=read("manifest.webmanifest"),vite=read("vite.config.mjs"),bootstrap=read("bootstrap.js"),pwa=read("pwa.js"),ui=read("ui.js"),ux=read("ux-12.8.js"),life=read("life-os.js"),training=read("training-os.js"),huawei=read("tennis-huawei.js"),work=read("work-growth.js"),pkg=JSON.parse(read("package.json"));
assert.ok(core.includes(`APP_VERSION="${RELEASE}"`));assert.ok(core.includes("STATE_VERSION=18"),"13.0 must not migrate user state");
assert.ok(manifest.includes(`Life RPG ${RELEASE}`));assert.ok(vite.includes(`cacheId:"life-rpg-${RELEASE}"`));
assert.ok(!vite.includes('"personal-stabilization-os.js"'),"transitional shim must not ship");
assert.ok(bootstrap.includes('["ensureWork121Ui","renderWork121Panels"]'),"Work 12.1 not owned by render pipeline");
assert.ok(bootstrap.includes('["tennisHuaweiEnsureUi","tennisHuaweiRefresh"]'),"Huawei lifecycle not owned by render pipeline");
assert.ok(bootstrap.includes("LIFE_RPG_RUNTIME_ERRORS")&&bootstrap.includes("lifeRuntimeInvoke")&&bootstrap.includes('lifeRuntimeRecordError("base-render","render",e)'),"runtime error isolation missing");
assert.ok(!work.includes("renderWork=function"),"Work 12.1 monkey-patch remains");
assert.ok(!huawei.includes("MutationObserver"),"Huawei MutationObserver remains");
assert.ok(!/document\.addEventListener\(["']click["']/.test(huawei),"Huawei global click listener remains");
assert.ok(life.includes("lifeOsRegisterCandidateProvider")&&life.includes("lifeOsRegisterRouteHandler")&&life.includes("lifeOsExtensionStatus"),"Life OS extension API missing");
assert.ok(training.includes('lifeOsRegisterCandidateProvider("training129"')&&training.includes('lifeOsRegisterRouteHandler("training129"'),"Training OS not registered through extension API");
assert.ok(!training.includes("lifeOsRawCandidates=function")&&!training.includes("lifeOsOpen=function"),"Training OS monkey-patch remains");
assert.ok(ui.includes("ux7RegisterNavigationListener")&&ui.includes("ux7RegisterClarityProvider")&&ui.includes("ux7NavigationStatus"),"UX extension API missing");
assert.ok(ux.includes('ux7RegisterNavigationListener("ux128-navigation"')&&ux.includes('ux7RegisterClarityProvider("ux128-clarity"'),"UX 12.8 not registered through hooks");
assert.ok(!ux.includes("switchTab=function")&&!ux.includes("ux7SetView=function")&&!ux.includes("ux7ClaritySecondary=wrapped"),"UX monkey-patch remains");
assert.ok(pwa.includes("pwaSetupDone")&&pwa.includes("if(pwaSetupDone)return")&&pwa.includes("pwaSetupStatus"),"PWA setup is not idempotent");
assert.ok(!pwa.includes("location.reload()"),"PWA must not force reload on controllerchange");
assert.ok(!pkg.scripts.test.includes("stabilization-12.5.0.test.js"));assert.ok(pkg.scripts.test.includes("stabilization-13.0.0.test.js"));
console.log("OK — Life RPG 13.0.0 stabilization contracts: release, lifecycle, hooks, PWA and legacy cleanup passed");
