"use strict";
const fs=require("fs"),path=require("path"),cp=require("child_process"),assert=require("assert");
const root=__dirname,read=n=>fs.readFileSync(path.join(root,n),"utf8");
const RELEASE="13.2.0",SHELL_ANCHOR="12.0.3";
const baseModules=["core.js","state.js","finance.js","imports.js","work.js","tennis.js","knowledge.js","gamification.js","pwa.js","ui.js"];
const bootstrap=read("bootstrap.js"),registry=bootstrap.match(/const\s+LIFE_RPG_RUNTIME_MODULES\s*=\s*\[(.*?)\];/s);
assert.ok(registry,"Runtime registry not found in bootstrap.js");
const runtimeFiles=[...registry[1].matchAll(/"([^"]+\.js)"/g)].map(m=>m[1]);
assert.ok(runtimeFiles.length>=42,`Runtime registry unexpectedly small: ${runtimeFiles.length}`);
assert.equal(new Set(runtimeFiles).size,runtimeFiles.length,"Duplicate runtime files in bootstrap registry");
const requiredRuntime=["work-growth.js","tennis-decision.js","knowledge-decision.js","today-execution.js","integration-12.5.js","feedback-os.js","import-hub.js","ux-12.8.js","training-os.js","share-hub.js","intelligence-13.2.js"];
for(const f of requiredRuntime)assert.ok(runtimeFiles.includes(f),`${f} missing from runtime registry`);
const files=[...baseModules,...runtimeFiles,"bootstrap.js","app.js"];
for(const f of files){const full=path.join(root,f);assert.ok(fs.existsSync(full),`${f} missing`);const r=cp.spawnSync(process.execPath,["--check",full],{encoding:"utf8"});assert.equal(r.status,0,`${f} syntax failed: ${r.stderr}`)}

const html=read("index.html"),ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length,"Duplicate HTML ids detected");
for(const f of baseModules)assert.ok(new RegExp(`src="\\./${f.replace(".","\\.")}\\?v=[^"]+"`).test(html),`Missing base script ${f}`);
assert.ok(/src="\.\/bootstrap\.js\?v=[^"]+"/.test(html),"Missing bootstrap.js");assert.ok(!html.includes('src="./app.js?v='),"index.html must not load legacy app.js");
for(const f of runtimeFiles)assert.ok(!new RegExp(`src="\\./${f.replace(".","\\.")}`).test(html),`${f} must be loaded by bootstrap`);

const js=[...baseModules,...runtimeFiles,"bootstrap.js","app.js"].map(read).join("\n"),names=[...js.matchAll(/^(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(/gm)].map(m=>m[1]),seen=new Set(),dups=[];for(const n of names){if(seen.has(n))dups.push(n);seen.add(n)}assert.deepEqual([...new Set(dups)],[],"Duplicate function declarations remain");
const handlers=new Set([...html.matchAll(/\bon(?:click|change|input|submit)="\s*([A-Za-z_$][\w$]*)\s*\(/g)].map(m=>m[1]));for(const h of handlers)assert.ok(seen.has(h),`Inline handler missing function: ${h}`);
const refs=new Set([...js.matchAll(/\$\("([^"]+)"\)/g)].map(m=>m[1])),dynamic=new Set(["statementReviewAck","ux7AccountForm","ux7AssetForm","ux7FinancePulse","ux7Fab","ux7NewDebtBtn","ux7QuickSheet","ux7TodayPulse","ux7ToggleDebtForm"]),idSet=new Set(ids),missing=[...refs].filter(x=>!idSet.has(x)&&!dynamic.has(x));assert.deepEqual(missing,[],"Unexpected missing DOM ids: "+missing.join(", "));

const sw=read("sw.js"),manifest=read("manifest.webmanifest"),core=read("core.js"),vite=read("vite.config.mjs"),pwa=read("pwa.js"),state=read("state.js"),integration=read("integration-12.5.js"),hub=read("import-hub.js"),ux128=read("ux-12.8.js"),ux128css=read("ux-12.8.css"),training=read("training-os.js"),share=read("share-hub.js"),shareSw=read("share-target-sw.js");
assert.ok(core.includes(`APP_VERSION="${RELEASE}"`),"Wrong runtime release");assert.ok(core.includes("STATE_VERSION=18"),"State schema changed unexpectedly");
assert.ok(manifest.includes(`Life RPG ${RELEASE}`),"Wrong manifest release");assert.ok(vite.includes(`cacheId:"life-rpg-${RELEASE}"`),"Generated Workbox cacheId missing");
assert.ok(!sw.includes('addEventListener("fetch"')&&!sw.includes("addEventListener('fetch'"),"Source SW must be inert; Workbox owns production SW");
assert.ok(bootstrap.includes("Promise.all(LIFE_RPG_RUNTIME_MODULES.map(lifeRuntimeLoadScript))"),"Runtime files must preload concurrently");
assert.ok(bootstrap.includes('["ensureWork121Ui","renderWork121Panels"]'));assert.ok(bootstrap.includes('["tennisHuaweiEnsureUi","tennisHuaweiRefresh"]'));assert.ok(bootstrap.includes('["ensureIntegration125Ui","renderIntegration125"]'));assert.ok(bootstrap.includes('["ensureFeedback126Ui","renderFeedback126"]'));assert.ok(bootstrap.includes('["ensureImport127Ui","renderImport127"]'));assert.ok(bootstrap.includes('["ensureUx128Ui","renderUx128"]'));assert.ok(bootstrap.includes('["ensureTraining129Ui","renderTraining129"]'));assert.ok(bootstrap.includes('["ensureShare131Ui","renderShare131"]'));assert.ok(bootstrap.includes('["ensureIntelligence132Ui","renderIntelligence132"]'));assert.ok(bootstrap.includes("lifeRuntimeInvoke")&&bootstrap.includes("LIFE_RPG_RUNTIME_ERRORS"));
for(const f of runtimeFiles)assert.ok(vite.includes(`"${f}"`),`${f} not copied to dist`);
assert.ok(!bootstrap.includes("personal-stabilization-os.js"));assert.ok(!vite.includes('"personal-stabilization-os.js"'));
assert.ok(!pwa.includes("location.reload()"));assert.ok(!read("ui.js").includes("location.replace(`./?v="));
assert.ok(integration.includes('todayFlowCommand')&&integration.includes('today123Command'));assert.ok(integration.includes('knowledgeOsCommand')&&integration.includes('knowledge124Today'));
assert.ok(hub.includes("createPreActionSnapshot")&&hub.includes("rollbackImportBatch")&&hub.includes("personalImportPreviewRows"));assert.ok(ux128.includes("UX128_NAV_KEY")&&ux128.includes("dashboardSearchRows")&&ux128.includes("ux128OpenRecent")&&ux128.includes("ux7RegisterNavigationListener")&&ux128.includes("ux7RegisterClarityProvider"));assert.ok(!ux128.includes("switchTab=function")&&!ux128.includes("ux7SetView=function")&&!ux128.includes("ux7ClaritySecondary=wrapped"));assert.ok(training.includes("Training & Physical Capacity OS")&&training.includes("training129LoadProfile")&&training.includes("training129InstallIntegration")&&training.includes("training129ImportHubHuawei")&&training.includes("lifeOsRegisterCandidateProvider"));assert.ok(!training.includes("lifeOsRawCandidates=function")&&!training.includes("lifeOsOpen=function"));assert.ok(read("life-os.js").includes("lifeOsRegisterCandidateProvider")&&read("life-os.js").includes("lifeOsRegisterRouteHandler"));assert.ok(read("ui.js").includes("ux7RegisterNavigationListener")&&read("ui.js").includes("ux7RegisterClarityProvider"));assert.ok(!read("work-growth.js").includes("renderWork=function"));assert.ok(!read("tennis-huawei.js").includes("MutationObserver"));assert.ok(pwa.includes("pwaSetupDone"));assert.ok(ux128css.includes(".ux128-sticky-actions"));assert.ok(vite.includes('"ux-12.8.css"'));assert.ok(vite.includes('importScripts:["share-target-sw.js"]'));assert.ok(manifest.includes("share_target")&&manifest.includes("./share-target"));assert.ok(share.includes("Mobile Automation & Share Hub 13.1")&&share.includes("share131ParseIcs")&&share.includes("share131RouteImport"));assert.ok(shareSw.includes('addEventListener("fetch"')&&shareSw.includes("request.formData"));
assert.ok(state.includes("function isSafeStateId"));assert.ok(state.includes("campaignStart:localDateKey()"));
assert.ok(html.includes("life-rpg-booting"));assert.ok(html.includes(`?v=${SHELL_ANCHOR}`));assert.ok(!html.includes("tesseract.min.js"));assert.ok(read("imports.js").includes("ensureFinancialOcrLoaded"));
assert.ok(fs.existsSync(path.join(root,"reading-list.test.js")));assert.ok(fs.existsSync(path.join(root,"tennis-huawei.test.js")));assert.ok(fs.existsSync(path.join(root,"layout-all.e2e.test.js")));assert.ok(fs.existsSync(path.join(root,"import-hub-12.7.test.js")));assert.ok(fs.existsSync(path.join(root,"ux-12.8.test.js")));assert.ok(fs.existsSync(path.join(root,"training-12.9.test.js")));assert.ok(fs.existsSync(path.join(root,"stabilization-13.0.0.test.js")));assert.ok(fs.existsSync(path.join(root,"mobile-share-13.1.test.js")));assert.ok(fs.existsSync(path.join(root,"android-acceptance-13.1.1.test.js")));assert.ok(fs.existsSync(path.join(root,"decision-intelligence-13.2.test.js")));
assert.ok(share.includes("Android Acceptance 13.1.1")&&share.includes("share131AcceptanceDiagnostics")&&share.includes("share131AcceptanceAuto")&&share.includes("share131AcceptanceExportReport"));const intel=read("intelligence-13.2.js");assert.ok(intel.includes("Decision Intelligence Kernel")&&intel.includes("intelligence132RankCandidates")&&intel.includes("intelligence132RecordOutcome")&&intel.includes("intelligence132Anomalies")&&intel.includes("intelligence132Scenario"));assert.ok(read("life-os.js").includes("intelligence132RankCandidates"));
const lock=JSON.parse(read("package-lock.json"));assert.equal(lock.version,"12.0.3");assert.equal(lock.packages?.[""]?.version,"12.0.3");
const workflow=read(".github/workflows/deploy-pages.yml");assert.ok(workflow.includes("npm ci --no-audit --no-fund"));assert.ok(workflow.includes("npm run test:e2e"));
console.log(`OK — static checks passed for Life RPG ${RELEASE}: ${names.length} unique functions, ${runtimeFiles.length} runtime modules`);
