"use strict";
const fs=require('fs'),path=require('path'),cp=require('child_process'),assert=require('assert');
const root=__dirname;
const baseModules=['core','state','finance','imports','work','tennis','knowledge','gamification','pwa','ui'];
const osModules=['data-os','projects-os','goals-os','review-os','calendar-os','tasks-os','routines-os','inbox-os','rules-os','insights-os','command-os','calibration-os','execution-os','decision-os','recovery-os','life-os'];
const modules=[...baseModules,...osModules,'bootstrap'];
for(const m of [...modules,'app']){
  const f=path.join(root,m+'.js');
  assert.ok(fs.existsSync(f),`${m}.js missing`);
  const r=cp.spawnSync(process.execPath,['--check',f],{encoding:'utf8'});
  assert.equal(r.status,0,`${m}.js syntax failed: ${r.stderr}`);
}
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
assert.equal(new Set(ids).size,ids.length,'Duplicate HTML ids detected');
for(const m of baseModules)assert.ok(new RegExp(`src="\\./${m}\\.js\\?v=[^"]+"`).test(html),`Missing base script ${m}.js`);
assert.ok(/src="\.\/bootstrap\.js\?v=[^"]+"/.test(html),'Missing bootstrap.js');
assert.ok(!html.includes('src="./app.js?v='),'index.html must not load legacy app.js');
for(const m of osModules)assert.ok(!new RegExp(`src="\\./${m}\\.js`).test(html),`${m}.js must be loaded by bootstrap to keep the legacy shell compatible`);
const js=[...modules,'app'].map(m=>fs.readFileSync(path.join(root,m+'.js'),'utf8')).join('\n');
const names=[...js.matchAll(/^(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(/gm)].map(m=>m[1]);
const seen=new Set(),dups=[];for(const n of names){if(seen.has(n))dups.push(n);seen.add(n)}
assert.deepEqual([...new Set(dups)],[],'Duplicate function declarations remain');
const handlers=new Set([...html.matchAll(/\bon(?:click|change|input|submit)="\s*([A-Za-z_$][\w$]*)\s*\(/g)].map(m=>m[1]));
for(const h of handlers)assert.ok(seen.has(h),`Inline handler missing function: ${h}`);
const refs=new Set([...js.matchAll(/\$\("([^"]+)"\)/g)].map(m=>m[1]));
const dynamic=new Set(['statementReviewAck','ux7AccountForm','ux7AssetForm','ux7FinancePulse','ux7Fab','ux7NewDebtBtn','ux7QuickSheet','ux7TodayPulse','ux7ToggleDebtForm']);
const idSet=new Set(ids);const missing=[...refs].filter(x=>!idSet.has(x)&&!dynamic.has(x));
assert.deepEqual(missing,[],'Unexpected missing DOM ids: '+missing.join(', '));
const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),manifest=fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'),core=fs.readFileSync(path.join(root,'core.js'),'utf8'),bootstrap=fs.readFileSync(path.join(root,'bootstrap.js'),'utf8');
assert.ok(sw.includes('life-rpg-v11.1.1-mobile-layout'),'Wrong SW cache');
assert.ok(!sw.includes('?v=10.0.2')&&!sw.includes('?v=10.1.0')&&!sw.includes('?v=10.2.0')&&!sw.includes('?v=11.0.0')&&!sw.includes('?v=11.1.0'),'Stale SW asset query versions');
for(const m of osModules)assert.ok(sw.includes(`./${m}.js?v=11.1.1`),`SW missing ${m}.js`);
assert.ok(manifest.includes('Life RPG 11.1.1'),'Wrong manifest version');
assert.ok(html.includes('mobile-layout.css?v=11.1.1'),'Mobile layout stylesheet missing from HTML shell');assert.ok(fs.existsSync(path.join(root,'mobile-layout.test.js')),'mobile-layout.test.js missing');assert.ok(sw.includes('./mobile-layout.css?v=11.1.1'),'SW source cache missing mobile layout stylesheet');
assert.ok(core.includes('APP_VERSION="11.1.1"'),'Wrong app version');
assert.ok(core.includes('STATE_VERSION=18'),'Wrong state version');
const state=fs.readFileSync(path.join(root,'state.js'),'utf8');
assert.ok(state.includes('entities:{projects:[],tasks:[],goals:[],routines:[],routineLogs:[],reviews:[],inbox:[],calendarEvents:[]}'),'v18 entity layer missing');
assert.ok(state.includes('raw?.settings?.[key]'),'v17 -> v18 migration fallback missing');
assert.ok(fs.readFileSync(path.join(root,'calibration-os.js'),'utf8').includes('function calibrationMaybeAutoTune'),'Calibration loop missing');
assert.ok(fs.readFileSync(path.join(root,'execution-os.js'),'utf8').includes('function executionPlan'),'Execution Intelligence missing');
assert.ok(fs.readFileSync(path.join(root,'decision-os.js'),'utf8').includes('function decisionExplain'),'Decision explanation missing');
assert.ok(fs.readFileSync(path.join(root,'recovery-os.js'),'utf8').includes('function recoveryRestoreEntity'),'Entity recovery missing');
const decision=fs.readFileSync(path.join(root,'decision-os.js'),'utf8');assert.ok(decision.includes("decisionSetPreference('${t}','never')")&&decision.includes('Не предлагать'),'Visible never-suggest action missing');assert.ok(decision.includes('id="todayFlowCommand"'),'Today Flow consolidation missing');
assert.ok(bootstrap.includes('LIFE_RPG_111_MODULES'),'Modular bootstrap registry missing');assert.ok(bootstrap.includes('calibration-os.js'),'Calibration module not registered');
assert.ok(bootstrap.includes('window.__LIFE_RPG_HTML_VERSION__=APP_VERSION'),'Bootstrap must reconcile legacy HTML shell version');
assert.ok(html.includes('window.__LIFE_RPG_HTML_VERSION__="11.1.1"'),'HTML shell version mismatch');
assert.ok(html.includes('<title>Life RPG 11.1.1</title>'),'HTML title mismatch');
assert.ok(!html.includes('11.1.0')&&!html.includes('11.0.0')&&!html.includes('10.2.0')&&!html.includes('10.1.0'),'Stale release references remain in HTML shell');
assert.ok(!html.includes('Financial OS 7.2')&&!html.includes('Life OS 7.2')&&!html.includes('Debt Engine 7.2'),'Stale visible version labels');
assert.ok(fs.readFileSync(path.join(root,'pwa.js'),'utf8').includes('fetch(`./core.js?check='),'Update checker must read core.js version');

const ui=fs.readFileSync(path.join(root,'ui.js'),'utf8');
assert.ok(ui.includes('["bank","Банк"]'),'Finance Bank tab missing');
assert.ok(ui.includes('ux7Go("work","log")'),'Work quick action must open log view');
assert.ok(ui.includes('ux7Go("tennis","training")'),'Tennis quick action must open training view');
assert.ok(html.includes('data-ux7-view="bank" class="card span-12 financial-command-card"'),'Financial command card must be in Bank view');
assert.ok(html.includes('data-ux7-view="bank" class="card span-12 bank-sync-card"'),'Bank sync card must be in Bank view');
assert.ok(html.includes('class="entry-details"'),'Progressive entry details missing');
assert.ok(html.includes('class="settings-group"'),'Grouped settings missing');
assert.ok(html.includes('id="systemDiagnostics"'),'Data diagnostics card missing');
assert.ok(html.includes('tesseract.js@5.1.1/dist/tesseract.min.js'),'Tesseract.js must be pinned to 5.1.1');
assert.ok(fs.existsSync(path.join(root,'final-audit.test.js')),'Final audit test missing');
assert.ok(fs.existsSync(path.join(root,'visual-system.test.js')),'Full visual-system test missing');

const knowledge=fs.readFileSync(path.join(root,'knowledge.js'),'utf8');
assert.ok(html.includes('id="readingListImport"'),'Reading-list import input missing');
assert.ok(html.includes('id="readingListImportStatus"'),'Reading-list import status missing');
assert.ok(knowledge.includes('life-rpg-reading-list-v1'),'Reading-list format support missing');
assert.ok(knowledge.includes('status:"queued"'),'Queued-book status missing');
assert.ok(knowledge.includes('function startQueuedBook'),'Queued-book start action missing');
assert.ok(fs.existsSync(path.join(root,'reading-list.test.js')),'Reading-list test missing');
assert.ok(fs.existsSync(path.join(root,'calibration.test.js')),'Calibration test missing');

console.log(`OK — static checks passed: ${names.length} unique functions, ${ids.length} unique HTML ids, ${handlers.size} inline handlers, ${osModules.length} modular OS files`);
