"use strict";

/* Tennis Growth — templates, exact drill split and clearer load analytics. */
function tennisGrowthTemplates(){const g=growthData();if(!g.tennisTemplatesInitialized){g.tennisTemplates.push(
  {id:"tg-technique",name:"Техника 90",type:"Техника",minutes:90,load:6,focus:"Смешанная",serve:15,foot:15,note:"Техника: качество контакта, стабильность, короткие серии."},
  {id:"tg-serve",name:"Подача + приём 75",type:"Подачи / приём",minutes:75,load:6,focus:"Подача",serve:45,foot:10,note:"Подача / приём: вариативность, первый ход, контроль размещения."},
  {id:"tg-match",name:"Матчевая 90",type:"Спарринг",minutes:90,load:8,focus:"Тактика",serve:15,foot:15,note:"Матчевая практика: решения под счёт, первая атака, разбор повторяющихся ошибок."},
  {id:"tg-light",name:"Лёгкая 60",type:"Техника",minutes:60,load:4,focus:"Смешанная",serve:10,foot:10,note:"Лёгкая техническая сессия без добивания нагрузки."}
);g.tennisTemplatesInitialized=true}return g.tennisTemplates.filter(x=>x&&x.active!==false)}
function tennisGrowthTemplate(id){return tennisGrowthTemplates().find(x=>x.id===id)||null}
function tennisGrowthSet(id,value){const el=document.getElementById(id);if(el)el.value=String(value??"")}
function tennisGrowthApplyTemplate(id){const t=tennisGrowthTemplate(id);if(!t)return;tennisGrowthSet("ttType",t.type);tennisGrowthSet("ttMinutes",t.minutes);tennisGrowthSet("ttLoad",t.load);tennisGrowthSet("ttFocus",t.focus);tennisGrowthSet("ttServe",t.serve);tennisGrowthSet("ttFoot",t.foot);tennisGrowthSet("ttNote",t.note||"");document.getElementById("ttDate")?.scrollIntoView({behavior:"smooth",block:"center"});toast(`Шаблон: ${t.name}`)}
function tennisGrowthDetails(){return growthData().tennisDetails.filter(x=>x&&x.sessionId)}
function tennisGrowthDetail(sessionId){return tennisGrowthDetails().find(x=>String(x.sessionId)===String(sessionId))||null}
function tennisGrowthSession(sessionId){return (S.tennis||[]).find(x=>String(x.id)===String(sessionId))||null}
function tennisGrowthSessionOptions(selected=""){return (typeof tennisSessionsDesc==="function"?tennisSessionsDesc():(S.tennis||[])).slice(0,20).map(x=>`<option value="${escapeHtml(x.id)}" ${x.id===selected?"selected":""}>${escapeHtml(x.dateKey||"")} • ${escapeHtml(x.type||"Сессия")} • ${Math.round(+x.min||0)} мин</option>`).join("")}
function tennisGrowthLoadDetailForm(){const id=String(document.getElementById("tennisGrowthSession")?.value||""),d=tennisGrowthDetail(id)||{};for(const [key,field] of [["FH","tennisGrowthFH"],["BH","tennisGrowthBH"],["serve","tennisGrowthServe"],["receive","tennisGrowthReceive"],["foot","tennisGrowthFoot"],["tactics","tennisGrowthTactics"]])tennisGrowthSet(field,Math.max(0,+d[key]||0))}
async function tennisGrowthSaveDetail(){const sessionId=String(document.getElementById("tennisGrowthSession")?.value||""),s=tennisGrowthSession(sessionId);if(!s){toast("Выбери тренировку");return}const data={};for(const [key,field] of [["FH","tennisGrowthFH"],["BH","tennisGrowthBH"],["serve","tennisGrowthServe"],["receive","tennisGrowthReceive"],["foot","tennisGrowthFoot"],["tactics","tennisGrowthTactics"]])data[key]=Math.max(0,Math.round(+document.getElementById(field)?.value||0));const total=Object.values(data).reduce((a,b)=>a+b,0);if(total>Math.max(0,+s.min||0)+5){toast(`Разбивка ${total} мин больше длительности сессии ${s.min} мин`);return}const old=tennisGrowthDetail(sessionId),row={id:old?.id||uid(),sessionId,...data,total,updatedAt:new Date().toISOString(),createdAt:old?.createdAt||new Date().toISOString()};if(old)Object.assign(old,row);else growthData().tennisDetails.unshift(row);audit("Детализация тенниса","system",`${s.dateKey} • ${total} мин`);await save("Разбивка тренировки сохранена")}
function tennisGrowthSessionExposure(s){const d=tennisGrowthDetail(s.id);if(d)return {FH:+d.FH||0,BH:+d.BH||0,"Подача":+d.serve||0,"Приём":+d.receive||0,"Ноги":+d.foot||0,"Тактика":+d.tactics||0,exact:true};const total=Math.max(0,+s.min||0),serve=Math.min(total,Math.max(0,+s.serveMin||0)),foot=Math.min(Math.max(0,total-serve),Math.max(0,+s.footMin||0)),remaining=Math.max(0,total-serve-foot),exp={FH:0,BH:0,"Подача":serve/2,"Приём":serve/2,"Ноги":foot,"Тактика":0,exact:false},focus=String(s.focus||"Смешанная");if(focus==="Смешанная"){exp.FH+=remaining/3;exp.BH+=remaining/3;exp["Тактика"]+=remaining/3}else if(exp[focus]!=null)exp[focus]+=remaining;else exp["Тактика"]+=remaining;return exp}
function tennisGrowthExposure(days=30){const start=localDateKey(addDays(new Date(),-(days-1))),sum={FH:0,BH:0,"Подача":0,"Приём":0,"Ноги":0,"Тактика":0},sessions=(S.tennis||[]).filter(x=>String(x.dateKey||"")>=start);let exact=0;for(const s of sessions){const e=tennisGrowthSessionExposure(s);if(e.exact)exact++;for(const k of Object.keys(sum))sum[k]+=+e[k]||0}return {sum,sessions:sessions.length,exact,total:Object.values(sum).reduce((a,b)=>a+b,0)}}
function tennisGrowthMatchBands(){const current=typeof computeTennisElo==="function"?computeTennisElo().rating:1000,matches=(typeof tennisAllMatches==="function"?tennisAllMatches():[]).filter(x=>(+x.opponentRating||0)>0&&["W","L"].includes(x.result)),bands={higher:{label:"Сильнее текущего Elo",w:0,l:0},peer:{label:"±100 Elo",w:0,l:0},lower:{label:"Ниже текущего Elo",w:0,l:0}};for(const m of matches){const diff=(+m.opponentRating||0)-current,key=diff>100?"higher":diff<-100?"lower":"peer";if(m.result==="W")bands[key].w++;else bands[key].l++}return {current,matches,bands}}
function tennisGrowthLoad(){const p=typeof tennisLoadProfile==="function"?tennisLoadProfile():null;if(!p)return {acute:0,baseline:0,ratio:null,interpretable:false};return p}
function tennisGrowthRecommendation(){const e=tennisGrowthExposure(21),entries=Object.entries(e.sum).sort((a,b)=>a[1]-b[1]),low=entries[0],high=entries[entries.length-1],load=tennisGrowthLoad();if(load.interpretable&&load.ratio>1.5)return `Нагрузка 7 дней выше обычной в ${load.ratio.toFixed(2)} раза. Следующая сессия — лёгкая техника.`;if(e.total>0&&low)return `Меньше всего целевого времени за 21 день: ${low[0]} (${Math.round(low[1])} мин). Больше всего: ${high[0]} (${Math.round(high[1])} мин).`;return "Добавляй тренировки — рекомендации станут точнее."}
function ensureTennisGrowthUi(){if(document.getElementById("tennisGrowthTraining"))return;const grid=document.querySelector("#tennis .grid"),form=document.getElementById("ttDate")?.closest(".card"),analytics=document.getElementById("tennisAnalytics")?.closest(".card");if(!grid||!form||!analytics)return;form.insertAdjacentHTML("beforebegin",`<div data-ux7-view="training" class="card ux7-card span-12"><div class="eyebrow">Tennis OS 2</div><div class="section-title">Шаблоны и фактическая структура тренировки</div><div class="title" style="margin-top:12px">Шаблоны</div><div id="tennisGrowthTemplates" class="split" style="margin-top:8px"></div><div class="title" style="margin-top:14px">Разбивка уже сохранённой сессии</div><div class="formgrid" style="margin-top:8px"><div class="field span-2"><label>Сессия</label><select id="tennisGrowthSession" onchange="tennisGrowthLoadDetailForm()"></select></div><div class="field"><label>FH, мин</label><input id="tennisGrowthFH" type="number" min="0"></div><div class="field"><label>BH, мин</label><input id="tennisGrowthBH" type="number" min="0"></div><div class="field"><label>Подача, мин</label><input id="tennisGrowthServe" type="number" min="0"></div><div class="field"><label>Приём, мин</label><input id="tennisGrowthReceive" type="number" min="0"></div><div class="field"><label>Ноги, мин</label><input id="tennisGrowthFoot" type="number" min="0"></div><div class="field"><label>Тактика/игра, мин</label><input id="tennisGrowthTactics" type="number" min="0"></div></div><button class="btn secondary" style="margin-top:10px" onclick="tennisGrowthSaveDetail()">Сохранить разбивку</button><div id="tennisGrowthTraining" style="margin-top:10px"></div></div>`);analytics.insertAdjacentHTML("afterend",`<div data-ux7-view="analytics" class="card ux7-card span-12"><div class="eyebrow">Tennis Growth Analytics</div><div class="section-title">Куда реально уходит тренировочное время</div><div id="tennisGrowthAnalytics" style="margin-top:10px"></div></div>`)}
function renderTennisGrowth(){const templates=document.getElementById("tennisGrowthTemplates"),select=document.getElementById("tennisGrowthSession"),train=document.getElementById("tennisGrowthTraining"),analytics=document.getElementById("tennisGrowthAnalytics");if(!templates||!select||!train||!analytics)return;templates.innerHTML=tennisGrowthTemplates().map(t=>`<button class="btn ghost small" onclick="tennisGrowthApplyTemplate('${t.id}')">${escapeHtml(t.name)}</button>`).join("");const before=select.value;select.innerHTML=tennisGrowthSessionOptions(before);if(before&&[...select.options].some(o=>o.value===before))select.value=before;if(!select.dataset.loaded){select.dataset.loaded="1";tennisGrowthLoadDetailForm()}const e=tennisGrowthExposure(30),load=tennisGrowthLoad(),m=tennisGrowthMatchBands(),max=Math.max(1,...Object.values(e.sum));train.innerHTML=`<div class="status">Точная разбивка заполнена для <b>${e.exact}/${e.sessions}</b> сессий за 30 дней. Для остальных используется оценка по полям старой формы.</div>`;const bands=Object.values(m.bands);analytics.innerHTML=`<div class="report-grid"><div class="report-item"><div class="smallcaps">Нагрузка 7 дней</div><b>${Math.round(load.acute||0)}</b><div class="sub">мин × RPE</div></div><div class="report-item"><div class="smallcaps">Обычная неделя</div><b>${Math.round(load.baseline||0)}</b></div><div class="report-item"><div class="smallcaps">7д / база</div><b>${load.interpretable&&load.ratio!=null?load.ratio.toFixed(2):"—"}</b></div><div class="report-item"><div class="smallcaps">Точная детализация</div><b>${e.exact}/${e.sessions}</b></div></div><div class="title" style="margin-top:14px">Техническая экспозиция 30 дней</div><div class="stats-list" style="margin-top:8px">${Object.entries(e.sum).map(([k,v])=>`<div class="stat-row"><div class="stat-name">${escapeHtml(k)}</div><div class="statbar"><i style="width:${clamp(v/max*100,0,100)}%"></i></div><div class="stat-xp">${Math.round(v)}м</div></div>`).join("")}</div><div class="title" style="margin-top:14px">Матчи относительно текущего Elo ${m.current}</div><div class="report-grid" style="margin-top:8px">${bands.map(b=>{const n=b.w+b.l;return `<div class="report-item"><div class="smallcaps">${escapeHtml(b.label)}</div><b>${n?Math.round(b.w/n*100):0}%</b><div class="sub">${b.w}:${b.l} • ${n} матч.</div></div>`}).join("")}</div><div class="notice" style="margin-top:10px">${escapeHtml(tennisGrowthRecommendation())}</div>`}
