"use strict";

/* Life RPG 10.0.1 — Tennis OS */

const TENNIS_WEEKLY=[
  {id:"sessions3",title:"3 тренировки за неделю",stat:"Теннис",xp:180,condition:()=>tennisWeek().sessions>=3},
  {id:"sessions4",title:"4 тренировки за неделю",stat:"Теннис",xp:250,condition:()=>tennisWeek().sessions>=4},
  {id:"tourney",title:"Турнир / рейтинговые игры",stat:"Теннис",xp:250,condition:()=>tennisWeek().tournaments>=1},
  {id:"serve60",title:"60 минут подачи / приёма",stat:"Теннис",xp:100,condition:()=>tennisWeek().serve>=60},
  {id:"foot45",title:"45 минут работы ног",stat:"Теннис",xp:100,condition:()=>tennisWeek().foot>=45}
];

function tennisWeek(){const [a,b]=weekBounds(),arr=S.tennis.filter(x=>inRange(x.dateKey,a,b));return {sessions:arr.length,tournaments:arr.filter(x=>x.type==="Турнир").length,serve:arr.reduce((n,x)=>n+(+x.serveMin||0),0),foot:arr.reduce((n,x)=>n+(+x.footMin||0),0)}}
function tennisSessionsDesc(){return (S.tennis||[]).slice().sort((a,b)=>String(b.dateKey||"").localeCompare(String(a.dateKey||""))||String(b.createdAt||"").localeCompare(String(a.createdAt||"")))}
function eloExpected(r,opp){return 1/(1+Math.pow(10,(opp-r)/400))}
function eloAfterSession(r,opp,w,l,k=24){let cur=r;for(let i=0;i<w;i++)cur+=k*(1-eloExpected(cur,opp));for(let i=0;i<l;i++)cur+=k*(0-eloExpected(cur,opp));return Math.round(cur)}

function normalizeMatchResult(v){const s=String(v||"").trim().toLowerCase();if(["w","win","п","победа","1"].includes(s))return"W";if(["l","loss","пор","поражение","0"].includes(s))return"L";return""}
function parseTennisMatches(text){return String(text||"").split(/\n+/).map((line,i)=>{const parts=line.split("|").map(x=>x.trim());if(!parts.some(Boolean))return null;const [opponent,rating,result,score,note]=parts;return {id:`m-${Date.now()}-${i}`,opponent:opponent||"",opponentRating:Math.max(0,+rating||0),result:normalizeMatchResult(result),score:score||"",note:note||""}}).filter(Boolean).filter(m=>m.opponent||m.result||m.opponentRating||m.score)}
function sessionMatches(x){if(Array.isArray(x?.matches)&&x.matches.length)return x.matches.map((m,i)=>({id:m.id||`${x.id||"s"}-m${i+1}`,opponent:String(m.opponent||""),opponentRating:Math.max(0,+m.opponentRating||0),result:normalizeMatchResult(m.result),score:String(m.score||""),note:String(m.note||"")}));return []}
function tennisMatchText(x){const m=sessionMatches(x);return m.map(z=>[z.opponent,z.opponentRating||"",z.result,z.score,z.note].join(" | ")).join("\n")}
function sessionWinLoss(x){const m=sessionMatches(x);if(m.length)return {w:m.filter(z=>z.result==="W").length,l:m.filter(z=>z.result==="L").length};return {w:Math.max(0,+x.w||0),l:Math.max(0,+x.l||0)}}
function tennisAllMatches(){const out=[];for(const s of S.tennis||[]){const ms=sessionMatches(s);if(ms.length)for(const m of ms)out.push({...m,sessionId:s.id,dateKey:s.dateKey,type:s.type});else if((+s.w||0)+(+s.l||0)>0){for(let i=0;i<+s.w||0;i++)out.push({id:`${s.id}-lw${i}`,sessionId:s.id,dateKey:s.dateKey,type:s.type,opponent:s.opponent||"",opponentRating:+s.opponentRating||0,result:"W",score:s.score||"",legacy:true});for(let i=0;i<+s.l||0;i++)out.push({id:`${s.id}-ll${i}`,sessionId:s.id,dateKey:s.dateKey,type:s.type,opponent:s.opponent||"",opponentRating:+s.opponentRating||0,result:"L",score:s.score||"",legacy:true})}}return out}

function computeTennisElo(){let r=Math.max(0,finiteNumberOr(S.settings.tennisBaseElo,1000)),history=[],ratedMatches=0;const rows=tennisSessionsDesc().slice().reverse();for(const x of rows){const before=r,ms=sessionMatches(x);if(ms.length){for(const m of ms){const opp=+m.opponentRating||0;if(opp<=0||!["W","L"].includes(m.result))continue;r=eloAfterSession(r,opp,m.result==="W"?1:0,m.result==="L"?1:0);ratedMatches++}}else{const opp=+x.opponentRating||0;if(opp>0){r=eloAfterSession(r,opp,Math.max(0,+x.w||0),Math.max(0,+x.l||0));ratedMatches+=(+x.w||0)+(+x.l||0)}}history.push({id:x.id,before,after:r})}return {rating:r,history,ratedMatches}}
function recomputeTennisElo(){const calc=computeTennisElo(),by=new Map(calc.history.map(x=>[x.id,x]));for(const x of S.tennis||[]){const h=by.get(x.id);if(h){x.eloBefore=h.before;x.eloAfter=h.after}}S.settings.tennisElo=calc.rating;return calc.rating}

function tennisXpFor(x){const wl=sessionWinLoss(x);return Math.min(60,Math.floor((+x.min||0)/30)*15)+(x.type==="Турнир"?50:0)+Math.min(25,wl.w*5)+((+x.serveMin||0)>=20?15:0)+((+x.footMin||0)>=15?10:0)}
async function addTennis(){const dateKey=$("ttDate")?.value||localDateKey();if(!validActivityDate(dateKey)){toast("Тренировку можно добавить только за сегодня или прошедшую дату");return}const min=Math.max(0,+$("ttMinutes").value||0),load=clamp(+$("ttLoad").value||0,1,10),serveMin=Math.max(0,+$("ttServe").value||0),footMin=Math.max(0,+$("ttFoot").value||0);if(min<=0){toast("Укажи длительность");return}if(serveMin+footMin>min){toast("Подача/приём + ноги не могут быть дольше всей сессии");return}const editId=$("ttEditId")?.value||"",old=editId?S.tennis.find(x=>x.id===editId):null;if(old){S.tennis=S.tennis.filter(x=>x.id!==editId);removeXp(old.xpAward||0,"Теннис","Редактирование тренировки",`tennis:${editId}`,old.dateKey)}const matches=parseTennisMatches($("ttMatches")?.value||""),legacyW=Math.max(0,Math.round(+$("ttW").value||0)),legacyL=Math.max(0,Math.round(+$("ttL").value||0)),wl=matches.length?{w:matches.filter(m=>m.result==="W").length,l:matches.filter(m=>m.result==="L").length}:{w:legacyW,l:legacyL};const x={id:old?.id||uid(),dateKey,date:parseLocal(dateKey).toLocaleDateString("ru-RU"),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),type:$("ttType").value,min,focus:$("ttFocus").value,load,w:wl.w,l:wl.l,serveMin,footMin,matches,opponent:matches[0]?.opponent||$("ttOpponent").value.trim(),opponentRating:matches[0]?.opponentRating||Math.max(0,+$("ttOpponentRating")?.value||0),score:matches[0]?.score||$("ttScore").value.trim(),note:$("ttNote").value.trim()};x.xpAward=tennisXpFor(x);S.tennis.unshift(x);recomputeTennisElo();const sx=S.tennis.find(z=>z.id===x.id);addXp(x.xpAward,"Теннис",old?"Теннисная сессия обновлена":"Теннисная сессия",`tennis:${x.id}`,"process",dateKey);audit(old?"Теннис изменён":"Теннис","sport",`${x.type} • Elo ${sx?.eloBefore??"—"}→${sx?.eloAfter??"—"}`);cancelTennisEdit();await save(`${old?"Сессия обновлена":"Сессия сохранена"} • текущий внутренний Elo ${S.settings.tennisElo}`)}
async function deleteTennis(id){const i=S.tennis.findIndex(x=>x.id===id);if(i<0)return;const x=S.tennis[i];if(!confirm("Удалить эту тренировку? Её можно будет восстановить из корзины."))return;await createPreActionSnapshot("Перед удалением теннисной сессии");trashPush("tennis",x);S.tennis.splice(i,1);removeXp(x.xpAward||0,"Теннис","Удалена тренировка",`tennis:${id}`,x.dateKey);recomputeTennisElo();await save("Тренировка удалена • Elo пересчитан, восстановление доступно")}
function editTennis(id){const x=S.tennis.find(z=>z.id===id);if(!x)return;const vals={ttEditId:x.id,ttDate:x.dateKey,ttMinutes:x.min,ttLoad:x.load,ttServe:x.serveMin||0,ttFoot:x.footMin||0,ttW:x.w||0,ttL:x.l||0,ttOpponent:x.opponent||"",ttOpponentRating:x.opponentRating||"",ttScore:x.score||"",ttNote:x.note||"",ttMatches:tennisMatchText(x)};for(const [id,v] of Object.entries(vals))if($(id))$(id).value=v??"";if($("ttType"))$("ttType").value=x.type||"Тренировка";if($("ttFocus"))$("ttFocus").value=x.focus||"Смешанная";if($("ttSaveBtn"))$("ttSaveBtn").textContent="Обновить сессию";if($("ttCancelEdit"))$("ttCancelEdit").hidden=false;$("ttDate")?.scrollIntoView({behavior:"smooth",block:"center"})}
function cancelTennisEdit(){for(const id of ["ttW","ttL","ttServe","ttFoot"])if($(id))$(id).value=0;if($("ttMinutes"))$("ttMinutes").value=90;if($("ttLoad"))$("ttLoad").value=7;for(const id of ["ttOpponent","ttOpponentRating","ttScore","ttNote","ttMatches","ttEditId"])if($(id))$(id).value="";if($("ttDate"))$("ttDate").value=localDateKey();if($("ttSaveBtn"))$("ttSaveBtn").textContent="Сохранить сессию";if($("ttCancelEdit"))$("ttCancelEdit").hidden=true}

function tennisLoad7(){const start=addDays(new Date(),-6);return S.tennis.filter(x=>parseLocal(x.dateKey)>=new Date(start.getFullYear(),start.getMonth(),start.getDate())).reduce((a,x)=>a+(+x.min||0)*(+x.load||0),0)}
function tennisExposure(days=14){const start=localDateKey(addDays(new Date(),-(days-1))),exp={FH:0,BH:0,"Подача":0,"Приём":0,"Ноги":0,"Тактика":0};for(const x of S.tennis.filter(s=>s.dateKey>=start)){const min=Math.max(0,+x.min||0);if(x.focus==="Смешанная")for(const k of Object.keys(exp))exp[k]+=min/6;else if(exp[x.focus]!=null)exp[x.focus]+=min;exp["Подача"]+=Math.max(0,+x.serveMin||0);exp["Ноги"]+=Math.max(0,+x.footMin||0)}return exp}
function tennisFocusRecommendation(){const exp=tennisExposure(14),total=Object.values(exp).reduce((a,b)=>a+b,0);if(!total)return"нет данных";return Object.entries(exp).sort((a,b)=>a[1]-b[1]||a[0].localeCompare(b[0],"ru"))[0][0]}
function tennisRecommendation(){const focus=tennisFocusRecommendation(),week=tennisWeek(),load=tennisLoad7();if(week.sessions<3)return `Сначала добери регулярность: ${week.sessions}/3 сессий на неделе. Фокус следующей тренировки — ${focus}.`;if(load>4500)return `Нагрузка за 7 дней высокая (${Math.round(load)} мин×RPE). Следующую сессию сделай легче, с техникой ${focus}.`;return `Следующий технический приоритет — ${focus}: за последние 14 дней на него пришлось меньше всего целевой работы.`}

function renderTennisAnalytics(){const box=$("tennisAnalytics");if(!box)return;const calc=computeTennisElo(),load=tennisLoad7(),focus=tennisFocusRecommendation(),matches=tennisAllMatches(),rated=matches.filter(m=>(+m.opponentRating||0)>0&&["W","L"].includes(m.result)).length,official=Math.max(0,+S.settings.tennisOfficialRating||0);box.innerHTML=`<div class="report-grid"><div class="report-item"><div class="smallcaps">Внутренний Elo</div><b>${calc.rating}</b><div class="sub">только матчи с рейтингом соперника</div></div><div class="report-item"><div class="smallcaps">Официальный рейтинг</div><b>${official||"—"}</b></div><div class="report-item"><div class="smallcaps">Рейтинговых матчей</div><b>${rated}</b></div><div class="report-item"><div class="smallcaps">Нагрузка 7 дней</div><b>${Math.round(load)}</b><div class="sub">минуты × RPE</div></div><div class="report-item"><div class="smallcaps">Технический приоритет</div><b>${escapeHtml(focus)}</b></div><div class="report-item"><div class="smallcaps">Цель месяца</div><b>${S.tennis.filter(x=>x.dateKey?.startsWith(localMonthKey())).length}/${S.settings.tennisMonthlyTarget||12}</b></div></div><div class="notice" style="margin-top:10px">${escapeHtml(tennisRecommendation())}</div>`}

function renderTennis(){const ss=tennisSessionsDesc(),mins=ss.reduce((a,x)=>a+(+x.min||0),0),all=tennisAllMatches(),w=all.filter(m=>m.result==="W").length,l=all.filter(m=>m.result==="L").length,month=ss.filter(x=>x.dateKey?.startsWith(localMonthKey())),last10=all.slice().sort((a,b)=>String(b.dateKey).localeCompare(String(a.dateKey))).slice(0,10),lw=last10.filter(m=>m.result==="W").length,ll=last10.filter(m=>m.result==="L").length;$("ttSessions").textContent=ss.length;$("ttHours").textContent=(mins/60).toFixed(1);$("ttWinRate").textContent=pct(w+l?w/(w+l)*100:0,0);$("ttMonthSessions").textContent=month.length;$("ttLast10").textContent=pct(lw+ll?lw/(lw+ll)*100:0,0);if($("ttElo"))$("ttElo").textContent=String(computeTennisElo().rating);const sk=tennisExposure(30),max=Math.max(1,...Object.values(sk));$("tennisSkills").innerHTML=Object.entries(sk).map(([k,v])=>`<div class="stat-row"><div class="stat-name">${k}</div><div class="statbar"><i style="width:${clamp(v/max*100,0,100)}%"></i></div><div class="stat-xp">${Math.round(v)}м</div></div>`).join("");$("tennisQuests").innerHTML=renderQuestGroup(TENNIS_WEEKLY,"tennis");renderOpponents();renderTennisMonthly();renderTennisAnalytics();$("tennisLog").innerHTML=ss.length?ss.slice(0,12).map(x=>{const wl=sessionWinLoss(x),ms=sessionMatches(x);return `<div class="log-item"><div class="qtitle">${fmtDate(parseLocal(x.dateKey))} • ${escapeHtml(x.type)} • ${x.min} мин</div><div class="score">${escapeHtml(x.focus)} • матчи ${wl.w}:${wl.l} • нагрузка ${x.load}/10 • подача/приём ${x.serveMin||0} мин • ноги ${x.footMin||0} мин</div>${ms.length?`<div class="qmeta">${ms.map(m=>`${escapeHtml(m.opponent||"соперник")} ${m.opponentRating?`(${m.opponentRating}) `:""}${m.result||"?"}${m.score?` ${escapeHtml(m.score)}`:""}`).join(" • ")}</div>`:x.opponent?`<div class="qmeta">Legacy: ${escapeHtml(x.opponent)}${x.opponentRating?` • ${x.opponentRating}`:""}</div>`:""}${x.note?`<div class="qmeta">${escapeHtml(x.note)}</div>`:""}<div class="split" style="margin-top:7px"><button class="btn ghost small" onclick="editTennis('${x.id}')">Изменить</button><button class="btn ghost small" onclick="deleteTennis('${x.id}')">Удалить</button></div></div>`}).join(""):`<div class="empty">Пока нет сессий.</div>`}

function renderOpponents(){const map={};for(const x of tennisAllMatches()){if(!String(x.opponent||"").trim())continue;const display=x.opponent.trim(),k=display.toLowerCase().replace(/\s+/g," ");map[k]=map[k]||{name:display,w:0,l:0,s:0,rating:0};if(x.result==="W")map[k].w++;if(x.result==="L")map[k].l++;map[k].s++;if(+x.opponentRating>0)map[k].rating=+x.opponentRating}const arr=Object.values(map).sort((a,b)=>b.s-a.s||a.name.localeCompare(b.name,"ru")).slice(0,12);$("opponentJournal").innerHTML=arr.length?arr.map(v=>`<div class="log-item"><div class="qtitle">${escapeHtml(v.name)}${v.rating?` • ${v.rating}`:""}</div><div class="score">${v.s} матч. • ${v.w}:${v.l} • win rate ${pct(v.w+v.l?v.w/(v.w+v.l)*100:0,0)}</div></div>`).join(""):`<div class="empty">Добавляй матчи — здесь появится история соперников.</div>`}
function renderTennisMonthly(){const arr=S.tennis.filter(x=>x.dateKey?.startsWith(localMonthKey())),mins=arr.reduce((a,x)=>a+(+x.min||0),0),matches=tennisAllMatches().filter(x=>x.dateKey?.startsWith(localMonthKey())),w=matches.filter(x=>x.result==="W").length,l=matches.filter(x=>x.result==="L").length,tour=arr.filter(x=>x.type==="Турнир").length,serve=arr.reduce((a,x)=>a+(+x.serveMin||0),0),foot=arr.reduce((a,x)=>a+(+x.footMin||0),0);$("tennisMonthlyReport").innerHTML=`<div class="report-grid"><div class="report-item"><div class="smallcaps">Сессии</div><b>${arr.length}</b></div><div class="report-item"><div class="smallcaps">Часы</div><b>${(mins/60).toFixed(1)}</b></div><div class="report-item"><div class="smallcaps">Турниры</div><b>${tour}</b></div><div class="report-item"><div class="smallcaps">Матчи</div><b>${matches.length}</b></div><div class="report-item"><div class="smallcaps">Win rate</div><b>${pct(w+l?w/(w+l)*100:0,0)}</b></div><div class="report-item"><div class="smallcaps">Подача/приём</div><b>${serve} мин</b></div><div class="report-item"><div class="smallcaps">Ноги</div><b>${foot} мин</b></div></div>`}
