"use strict";

/* Life RPG 8.0 — Table tennis */

const TENNIS_WEEKLY=[
  {id:"sessions3",title:"3 тренировки за неделю",stat:"Теннис",xp:180,condition:()=>tennisWeek().sessions>=3},
  {id:"sessions4",title:"4 тренировки за неделю",stat:"Теннис",xp:250,condition:()=>tennisWeek().sessions>=4},
  {id:"tourney",title:"Турнир / рейтинговые игры",stat:"Теннис",xp:250,condition:()=>tennisWeek().tournaments>=1},
  {id:"serve60",title:"60 минут подачи / приёма",stat:"Теннис",xp:100,condition:()=>tennisWeek().serve>=60},
  {id:"foot45",title:"45 минут работы ног",stat:"Теннис",xp:100,condition:()=>tennisWeek().foot>=45}
];

function tennisWeek(){const [a,b]=weekBounds(),arr=S.tennis.filter(x=>inRange(x.dateKey,a,b));return {sessions:arr.length,tournaments:arr.filter(x=>x.type==="Турнир").length,serve:arr.reduce((n,x)=>n+(+x.serveMin||0),0),foot:arr.reduce((n,x)=>n+(+x.footMin||0),0)}}

function tennisSessionsDesc(){return (S.tennis||[]).slice().sort((a,b)=>String(b.dateKey||"").localeCompare(String(a.dateKey||""))||String(b.createdAt||"").localeCompare(String(a.createdAt||"")))}

function computeTennisElo(){let r=Math.max(0,+S.settings.tennisBaseElo||1000),history=[];const rows=tennisSessionsDesc().slice().reverse();for(const x of rows){const before=r,opp=+x.opponentRating||before;r=eloAfterSession(before,opp,Math.max(0,+x.w||0),Math.max(0,+x.l||0));history.push({id:x.id,before,after:r})}return {rating:r,history}}

async function addTennis(){const dateKey=$("ttDate")?.value||localDateKey(),min=Math.max(0,+$("ttMinutes").value||0),load=clamp(+$("ttLoad").value||0,1,10),w=Math.max(0,Math.round(+$(("ttW")).value||0)),l=Math.max(0,Math.round(+$(("ttL")).value||0)),serveMin=Math.max(0,+$("ttServe").value||0),footMin=Math.max(0,+$("ttFoot").value||0);if(min<=0){toast("Укажи длительность");return}if(serveMin+footMin>min){toast("Подача/приём + ноги не могут быть дольше всей сессии");return}const x={id:uid(),dateKey,date:parseLocal(dateKey).toLocaleDateString("ru-RU"),createdAt:new Date().toISOString(),type:$("ttType").value,min,focus:$("ttFocus").value,load,w,l,serveMin,footMin,opponent:$("ttOpponent").value.trim(),opponentRating:Math.max(0,+$("ttOpponentRating")?.value||0),score:$("ttScore").value.trim(),note:$("ttNote").value.trim()};x.xpAward=Math.min(60,Math.floor(min/30)*15)+(x.type==="Турнир"?50:0)+Math.min(25,x.w*5)+(x.serveMin>=20?15:0)+(x.footMin>=15?10:0);S.tennis.unshift(x);recomputeTennisElo();const sx=S.tennis.find(z=>z.id===x.id);addXp(x.xpAward,"Теннис","Теннисная сессия",`tennis:${x.id}`,"process",dateKey);$("ttNote").value=$("ttOpponent").value=$("ttScore").value="";if($("ttOpponentRating"))$("ttOpponentRating").value="";if($("ttDate"))$("ttDate").value=localDateKey();audit("Теннис","sport",`${x.type} • Elo ${sx?.eloBefore??"—"}→${sx?.eloAfter??"—"}`);await save(`Сессия сохранена • текущий Elo ${S.settings.tennisElo}`)}

async function deleteTennis(id){const i=S.tennis.findIndex(x=>x.id===id);if(i<0)return;const x=S.tennis[i];S.tennis.splice(i,1);removeXp(x.xpAward||0,"Теннис","Удалена тренировка",`tennis:${id}`,x.dateKey);recomputeTennisElo();await save("Тренировка удалена") }

function eloExpected(r,opp){return 1/(1+Math.pow(10,(opp-r)/400))}

function eloAfterSession(r,opp,w,l,k=24){let cur=r;for(let i=0;i<w;i++)cur+=k*(1-eloExpected(cur,opp));for(let i=0;i<l;i++)cur+=k*(0-eloExpected(cur,opp));return Math.round(cur)}

function recomputeTennisElo(){const calc=computeTennisElo(),by=new Map(calc.history.map(x=>[x.id,x]));for(const x of S.tennis||[]){const h=by.get(x.id);if(h){x.eloBefore=h.before;x.eloAfter=h.after}}S.settings.tennisElo=calc.rating;return calc.rating}

function tennisLoad7(){const start=addDays(new Date(),-6);return S.tennis.filter(x=>parseLocal(x.dateKey)>=new Date(start.getFullYear(),start.getMonth(),start.getDate())).reduce((a,x)=>a+(+x.min||0)*(+x.load||0),0)}

function tennisFocusRecommendation(){const arr=tennisSessionsDesc().slice(0,5);if(!arr.length)return"нет данных";const counts={FH:0,BH:0,"Подача":0,"Приём":0,"Ноги":0,"Тактика":0};for(const x of arr)if(counts[x.focus]!=null)counts[x.focus]++;return Object.entries(counts).sort((a,b)=>a[1]-b[1]||a[0].localeCompare(b[0],"ru"))[0][0]}

function renderTennisAnalytics(){const box=$("tennisAnalytics");if(!box)return;const elo=computeTennisElo().rating,load=tennisLoad7(),focus=tennisFocusRecommendation();box.innerHTML=`<div class="report-grid"><div class="report-item"><div class="smallcaps">Внутренний Elo</div><b>${elo}</b></div><div class="report-item"><div class="smallcaps">Нагрузка 7 дней</div><b>${Math.round(load)}</b><div class="sub">минуты × RPE</div></div><div class="report-item"><div class="smallcaps">Меньше всего в последних 5</div><b>${escapeHtml(focus)}</b></div><div class="report-item"><div class="smallcaps">Цель месяца</div><b>${S.tennis.filter(x=>x.dateKey?.startsWith(localMonthKey())).length}/${S.settings.tennisMonthlyTarget||12}</b></div></div>`}

function renderTennis(){const ss=tennisSessionsDesc(),mins=ss.reduce((a,x)=>a+(+x.min||0),0),w=ss.reduce((a,x)=>a+(+x.w||0),0),l=ss.reduce((a,x)=>a+(+x.l||0),0),month=ss.filter(x=>x.dateKey?.startsWith(localMonthKey())),last10=ss.slice(0,10),lw=last10.reduce((a,x)=>a+(+x.w||0),0),ll=last10.reduce((a,x)=>a+(+x.l||0),0);$("ttSessions").textContent=ss.length;$("ttHours").textContent=(mins/60).toFixed(1);$("ttWinRate").textContent=pct(w+l?w/(w+l)*100:0,0);$("ttMonthSessions").textContent=month.length;$("ttLast10").textContent=pct(lw+ll?lw/(lw+ll)*100:0,0);if($("ttElo"))$("ttElo").textContent=String(computeTennisElo().rating);const sk={FH:0,BH:0,Подача:0,Приём:0,Ноги:0,Тактика:0};ss.forEach(x=>{if(sk[x.focus]!=null)sk[x.focus]+=Math.max(10,x.min/2);if(x.focus==="Смешанная")Object.keys(sk).forEach(k=>sk[k]+=x.min/12);sk.Подача+=x.serveMin/2;sk.Ноги+=x.footMin/2});$("tennisSkills").innerHTML=Object.entries(sk).map(([k,v])=>`<div class="stat-row"><div class="stat-name">${k}</div><div class="statbar"><i style="width:${clamp(v/5,0,100)}%"></i></div><div class="stat-xp">${Math.round(v)}</div></div>`).join("");$("tennisQuests").innerHTML=renderQuestGroup(TENNIS_WEEKLY,"tennis");renderOpponents();renderTennisMonthly();renderTennisAnalytics();$("tennisLog").innerHTML=ss.length?ss.slice(0,12).map(x=>`<div class="log-item"><div class="qtitle">${fmtDate(parseLocal(x.dateKey))} • ${escapeHtml(x.type)} • ${x.min} мин${x.opponent?` • ${escapeHtml(x.opponent)}`:""}</div><div class="score">${escapeHtml(x.focus)} • ${x.w}:${x.l}${x.score?` • счёт ${escapeHtml(x.score)}`:""} • нагрузка ${x.load}/10 • подача/приём ${x.serveMin||0} мин • ноги ${x.footMin||0} мин</div>${x.note?`<div class="qmeta">${escapeHtml(x.note)}</div>`:""}<button class="btn ghost small" style="margin-top:7px" onclick="deleteTennis('${x.id}')">Удалить</button></div>`).join(""):`<div class="empty">Пока нет сессий.</div>`}

function renderOpponents(){const map={};S.tennis.filter(x=>String(x.opponent||"").trim()).forEach(x=>{const display=x.opponent.trim(),k=display.toLowerCase().replace(/\s+/g," ");map[k]=map[k]||{name:display,w:0,l:0,s:0};map[k].w+=+x.w||0;map[k].l+=+x.l||0;map[k].s++});const arr=Object.values(map).sort((a,b)=>b.s-a.s||a.name.localeCompare(b.name,"ru")).slice(0,10);$("opponentJournal").innerHTML=arr.length?arr.map(v=>`<div class="log-item"><div class="qtitle">${escapeHtml(v.name)}</div><div class="score">${v.s} сесс. • ${v.w}:${v.l} • win rate ${pct(v.w+v.l?v.w/(v.w+v.l)*100:0,0)}</div></div>`).join(""):`<div class="empty">Указывай соперника в сессии — здесь появится история.</div>`}

function renderTennisMonthly(){const arr=S.tennis.filter(x=>x.dateKey?.startsWith(localMonthKey())),mins=arr.reduce((a,x)=>a+(+x.min||0),0),w=arr.reduce((a,x)=>a+(+x.w||0),0),l=arr.reduce((a,x)=>a+(+x.l||0),0),tour=arr.filter(x=>x.type==="Турнир").length,serve=arr.reduce((a,x)=>a+(+x.serveMin||0),0),foot=arr.reduce((a,x)=>a+(+x.footMin||0),0);$("tennisMonthlyReport").innerHTML=`<div class="report-grid"><div class="report-item"><div class="smallcaps">Сессии</div><b>${arr.length}</b></div><div class="report-item"><div class="smallcaps">Часы</div><b>${(mins/60).toFixed(1)}</b></div><div class="report-item"><div class="smallcaps">Турниры</div><b>${tour}</b></div><div class="report-item"><div class="smallcaps">Win rate</div><b>${pct(w+l?w/(w+l)*100:0,0)}</b></div><div class="report-item"><div class="smallcaps">Подача/приём</div><b>${serve} мин</b></div><div class="report-item"><div class="smallcaps">Ноги</div><b>${foot} мин</b></div></div>`}
