"use strict";

/* Life RPG Growth OS — universal tracking + habit strength. */
function growthData(){
  S.settings=S.settings||{};
  const g=S.settings.growthOS&&typeof S.settings.growthOS==="object"?S.settings.growthOS:(S.settings.growthOS={});
  if(!Array.isArray(g.trackers))g.trackers=[];if(!Array.isArray(g.events))g.events=[];if(!Array.isArray(g.knowledgeNotes))g.knowledgeNotes=[];if(!Array.isArray(g.tennisTemplates))g.tennisTemplates=[];if(!Array.isArray(g.tennisDetails))g.tennisDetails=[];
  if(!g.activeTimers||typeof g.activeTimers!=="object"||Array.isArray(g.activeTimers))g.activeTimers={};
  if(!g.initializedAt){
    g.trackers.push(
      {id:"tracker-focus",name:"Фокус",area:"Система",type:"timer",unit:"мин",active:true,createdAt:new Date().toISOString()},
      {id:"tracker-mood",name:"Настроение",area:"Личное",type:"range",unit:"/10",min:1,max:10,active:true,createdAt:new Date().toISOString()},
      {id:"tracker-energy",name:"Энергия",area:"Личное",type:"range",unit:"/10",min:1,max:10,active:true,createdAt:new Date().toISOString()},
      {id:"tracker-sleep",name:"Сон",area:"Личное",type:"value",unit:"ч",active:true,createdAt:new Date().toISOString()}
    );g.initializedAt=new Date().toISOString()
  }
  return g
}
function growthTrackers(){return growthData().trackers.filter(x=>x&&x.active!==false)}
function growthTracker(id){return growthData().trackers.find(x=>String(x.id)===String(id))||null}
function growthEventDate(x){const k=String(x?.dateKey||"");return validDateKey(k)?k:String(x?.occurredAt||x?.createdAt||"").slice(0,10)}
function growthExplicitEvents(){return growthData().events.filter(x=>x&&validDateKey(growthEventDate(x)))}
function lifeTimelineEvents(days=60){
  const start=localDateKey(addDays(new Date(),-(Math.max(1,days)-1))),out=[];
  for(const x of growthExplicitEvents()){const k=growthEventDate(x);if(k<start)continue;const t=growthTracker(x.trackerId);out.push({id:"growth:"+x.id,dateKey:k,occurredAt:x.occurredAt||x.createdAt||`${k}T12:00:00`,area:x.area||t?.area||"Личное",kind:"tracker",title:t?.name||x.title||"Трекер",durationMin:Math.max(0,+x.durationMin||0),value:x.value,note:x.note||"",source:"tracking",raw:x})}
  for(const x of S.readingLogs||[]){const k=String(x.dateKey||"");if(k<start)continue;const b=(S.books||[]).find(q=>q.id===x.bookId);out.push({id:"read:"+x.id,dateKey:k,occurredAt:x.createdAt||`${k}T12:00:00`,area:"Знания",kind:"reading",title:b?.title||"Чтение",durationMin:Math.max(0,+x.minutes||0),value:Math.max(0,+x.pages||0),unit:"стр.",note:x.application||x.note||"",source:"reading",raw:x})}
  for(const x of S.tennis||[]){const k=String(x.dateKey||"");if(k<start)continue;out.push({id:"tennis:"+x.id,dateKey:k,occurredAt:x.createdAt||`${k}T12:00:00`,area:"Теннис",kind:"tennis",title:x.type||"Теннис",durationMin:Math.max(0,+x.min||0),value:clamp(+x.load||0,0,10),unit:"RPE",note:x.note||"",source:"tennis",raw:x})}
  if(typeof routineLogStore==="function"){const rs=typeof routineAll==="function"?routineAll():[];for(const x of routineLogStore()){const k=String(x.dateKey||"");if(k<start)continue;const r=rs.find(q=>q.id===x.routineId);out.push({id:"routine:"+x.id,dateKey:k,occurredAt:x.completedAt||`${k}T12:00:00`,area:r?.area||"Система",kind:"routine",title:r?.title||"Рутина",durationMin:Math.max(0,+r?.minutes||0),value:1,unit:"✓",note:"",source:"routine",raw:x})}}
  for(const x of S.entities?.tasks||[]){if(x.status!=="done"&&!x.completedAt)continue;const k=String(x.completedAt||x.updatedAt||"").slice(0,10);if(!validDateKey(k)||k<start)continue;out.push({id:"task:"+x.id,dateKey:k,occurredAt:x.completedAt||x.updatedAt,area:x.area||"Система",kind:"task",title:x.title||"Задача",durationMin:0,value:1,unit:"✓",note:"",source:"task",raw:x})}
  return out.sort((a,b)=>String(b.occurredAt||b.dateKey).localeCompare(String(a.occurredAt||a.dateKey)))
}
function growthLogEvent(trackerId,data={}){const t=growthTracker(trackerId);if(!t)return null;const dateKey=validDateKey(data.dateKey)?data.dateKey:localDateKey(),value=data.value==null?null:Number(data.value),durationMin=Math.max(0,Number(data.durationMin)||0),x={id:uid(),trackerId:t.id,area:t.area||"Личное",dateKey,occurredAt:data.occurredAt||new Date().toISOString(),value:Number.isFinite(value)?value:null,durationMin,note:String(data.note||"").trim(),createdAt:new Date().toISOString()};growthData().events.unshift(x);return x}
async function growthQuickLog(id){const t=growthTracker(id);if(!t)return;const input=document.getElementById(`growth-value-${id}`);let value=t.type==="tick"?1:Number(input?.value);if(t.type!=="tick"&&!Number.isFinite(value)){toast("Укажи значение");return}if(t.type==="range")value=clamp(value,Number(t.min??1),Number(t.max??10));growthLogEvent(id,{value});if(input&&t.type!=="range")input.value="";audit("Трекер","system",`${t.name}: ${value}`);await save("Запись добавлена")}
async function growthToggleTimer(id){const g=growthData(),t=growthTracker(id);if(!t||t.type!=="timer")return;const started=g.activeTimers[id];if(!started){g.activeTimers[id]=new Date().toISOString();await save(`${t.name}: таймер запущен`);return}const minutes=Math.max(1,Math.round((Date.now()-Date.parse(started))/60000));delete g.activeTimers[id];growthLogEvent(id,{durationMin:minutes,value:minutes,note:"Таймер"});audit("Таймер завершён","system",`${t.name}: ${minutes} мин`);await save(`${t.name}: ${minutes} мин`)}
function growthTrackerTypeLabel(t){return t==="habit"?"Гибкая привычка":t==="tick"?"Отметка":t==="range"?"Шкала":t==="timer"?"Таймер":"Число"}
async function growthSaveTracker(){const name=String(document.getElementById("growthTrackerName")?.value||"").trim();if(!name){toast("Укажи название трекера");return}const type=String(document.getElementById("growthTrackerType")?.value||"tick"),area=String(document.getElementById("growthTrackerArea")?.value||"Личное"),unit=String(document.getElementById("growthTrackerUnit")?.value||"").trim(),weeklyTarget=clamp(Math.round(+document.getElementById("growthTrackerWeekly")?.value||3),1,14);growthData().trackers.push({id:uid(),name,area,type,unit,min:type==="range"?1:null,max:type==="range"?10:null,weeklyTarget:type==="habit"?weeklyTarget:null,active:true,createdAt:new Date().toISOString()});document.getElementById("growthTrackerName").value="";document.getElementById("growthTrackerUnit").value="";document.getElementById("growthTrackerEditor").hidden=true;audit("Трекер создан","system",name);await save("Трекер создан")}
async function growthArchiveTracker(id){const t=growthTracker(id);if(!t)return;t.active=false;delete growthData().activeTimers[id];await save("Трекер скрыт")}
function routineStrengthAt(r,anchor=new Date(),days=90){if(!r)return {strength:0,done:0,scheduled:0,rate30:0,trend:0};const end=anchor instanceof Date?anchor:parseLocal(anchor),start=addDays(end,-(days-1));let weighted=0,weightTotal=0,done=0,scheduled=0,done30=0,scheduled30=0;for(let d=new Date(start.getFullYear(),start.getMonth(),start.getDate(),12);d<=end;d=addDays(d,1)){const k=localDateKey(d);if(typeof routineExistsOn==="function"&&!routineExistsOn(r,k))continue;if(typeof routineScheduledOn==="function"&&!routineScheduledOn(r,d))continue;scheduled++;const age=Math.max(0,Math.round((end-d)/86400000)),w=Math.exp(-age/42),yes=typeof routineDoneOn==="function"&&routineDoneOn(r,k);weightTotal+=w;if(yes){weighted+=w;done++}if(age<30){scheduled30++;if(yes)done30++}}const prevEnd=addDays(end,-30),prevStart=addDays(prevEnd,-29);let pd=0,ps=0;for(let d=prevStart;d<=prevEnd;d=addDays(d,1)){const k=localDateKey(d);if(typeof routineExistsOn==="function"&&!routineExistsOn(r,k))continue;if(typeof routineScheduledOn==="function"&&!routineScheduledOn(r,d))continue;ps++;if(typeof routineDoneOn==="function"&&routineDoneOn(r,k))pd++}const rate30=scheduled30?done30/scheduled30*100:0,prevRate=ps?pd/ps*100:rate30;return {strength:weightTotal?weighted/weightTotal*100:0,done,scheduled,rate30,trend:rate30-prevRate}}
function routineStrength(r){return routineStrengthAt(r,new Date(),90)}
function growthHabitTrackerStrength(t){const target=Math.max(1,+t.weeklyTarget||3),events=growthExplicitEvents().filter(x=>x.trackerId===t.id),weeks=[];for(let w=0;w<12;w++){const end=addDays(new Date(),-w*7),start=addDays(end,-6),a=localDateKey(start),b=localDateKey(end),done=events.filter(x=>{const k=growthEventDate(x);return k>=a&&k<=b}).length,rate=Math.min(1,done/target),weight=Math.exp(-w/5);weeks.push({rate,weight,done})}const ws=weeks.reduce((s,x)=>s+x.weight,0),strength=ws?weeks.reduce((s,x)=>s+x.rate*x.weight,0)/ws*100:0,current=weeks[0]?.rate*100||0,prev=weeks.slice(1,5),prevRate=prev.length?prev.reduce((s,x)=>s+x.rate,0)/prev.length*100:current;return {strength,rate30:current,trend:current-prevRate}}
function habitStrengthRows(){const routines=(typeof routineActive==="function"?routineActive():[]).map(r=>({kind:"routine",title:r.title,area:r.area,...routineStrength(r)})),flex=growthTrackers().filter(t=>t.type==="habit").map(t=>({kind:"tracker",title:t.name,area:t.area,...growthHabitTrackerStrength(t)}));return [...routines,...flex].sort((a,b)=>a.strength-b.strength||a.title.localeCompare(b.title,"ru"))}
function growthTodayPlanFact(){const today=localDateKey(),tasks=(S.entities?.tasks||[]).filter(x=>x.status!=="done"&&x.plannedDate===today).reduce((a,x)=>a+Math.max(0,+x.minutes||0),0),routines=(typeof routineActive==="function"?routineActive():[]).filter(r=>typeof routineScheduledOn==="function"&&routineScheduledOn(r,new Date())&&!(typeof routineDoneOn==="function"&&routineDoneOn(r,today))).reduce((a,r)=>a+Math.max(0,+r.minutes||0),0),calendar=(S.entities?.calendarEvents||[]).filter(x=>x.dateKey===today).reduce((a,x)=>a+Math.max(0,+x.minutes||0),0),planned=tasks+routines+calendar,fact=lifeTimelineEvents(1).filter(x=>x.dateKey===today).reduce((a,x)=>a+Math.max(0,+x.durationMin||0),0);return {planned,fact}}
function growthHeatmap(days=35){const rows=lifeTimelineEvents(days),counts={};for(const x of rows)counts[x.dateKey]=(counts[x.dateKey]||0)+1;let d=addDays(new Date(),-(days-1)),html="";for(let i=0;i<days;i++){const k=localDateKey(d),n=counts[k]||0,level=n>=5?4:n>=3?3:n>=2?2:n>=1?1:0;html+=`<span class="growth-day g${level}" title="${k}: ${n} событий"></span>`;d=addDays(d,1)}return html}
function ensureGrowthStyles(){if(document.getElementById("growth-os-style"))return;const s=document.createElement("style");s.id="growth-os-style";s.textContent=`.growth-heat{display:grid;grid-template-columns:repeat(7,1fr);gap:5px;max-width:330px}.growth-day{aspect-ratio:1;border-radius:4px;background:var(--line,#2a3040)}.growth-day.g1{opacity:.45;background:currentColor}.growth-day.g2{opacity:.6;background:currentColor}.growth-day.g3{opacity:.78;background:currentColor}.growth-day.g4{opacity:1;background:currentColor}.growth-trackers{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.growth-tracker{border:1px solid var(--line,#2a3040);border-radius:12px;padding:10px;min-width:0}.growth-tracker input{width:100%;min-width:0}.growth-strength{display:grid;grid-template-columns:minmax(90px,1fr) minmax(80px,2fr) max-content;gap:8px;align-items:center}.growth-strength .statbar{min-width:0}@media(max-width:600px){.growth-trackers{grid-template-columns:1fr}.growth-strength{grid-template-columns:minmax(0,1fr) max-content}.growth-strength .statbar{grid-column:1/-1;grid-row:2}}`;document.head.appendChild(s)}
function ensureTrackingOsUi(){if(document.getElementById("trackingOsCommand"))return;ensureGrowthStyles();const grid=document.querySelector("#today .grid");if(!grid)return;const anchor=document.getElementById("routinesOsCommand")?.closest(".card")||document.getElementById("lifeOsCommand")?.closest(".card")||grid.lastElementChild;if(!anchor)return;anchor.insertAdjacentHTML("afterend",`<div data-ux7-view="focus" class="card ux7-card span-12"><div class="split"><div><div class="eyebrow">Tracking / Habit Strength</div><div class="section-title">Факт жизни, а не только планы</div></div><button class="btn secondary small" onclick="document.getElementById('growthTrackerEditor').hidden=false">+ Трекер</button></div><div class="muted" style="margin-top:6px">Единая временная шкала собирает чтение, теннис, рутины, выполненные задачи и произвольные измерения. Один пропуск не обнуляет привычку.</div><div id="trackingOsCommand" style="margin-top:10px"></div><div class="title" style="margin-top:14px">Быстрый трекинг</div><div id="growthTrackerList" class="growth-trackers" style="margin-top:8px"></div><div class="title" style="margin-top:14px">Сила привычек</div><div id="habitStrengthList" style="margin-top:8px"></div><div class="title" style="margin-top:14px">Активность 35 дней</div><div id="growthHeatmap" class="growth-heat" style="margin-top:8px"></div><div class="title" style="margin-top:14px">Последние события</div><div id="growthRecent" style="margin-top:8px"></div></div><div data-ux7-view="focus" class="card ux7-card span-12" id="growthTrackerEditor" hidden><div class="title">Новый универсальный трекер</div><div class="formgrid" style="margin-top:10px"><div class="field"><label>Название</label><input id="growthTrackerName"></div><div class="field"><label>Область</label><select id="growthTrackerArea"><option>Личное</option><option>Система</option><option>Финансы</option><option>Теннис</option><option>Знания</option><option>Тело</option><option>Отношения</option></select></div><div class="field"><label>Тип</label><select id="growthTrackerType"><option value="tick">Отметка</option><option value="habit">Гибкая привычка</option><option value="value">Число</option><option value="range">Шкала 1–10</option><option value="timer">Таймер</option></select></div><div class="field"><label>Единица</label><input id="growthTrackerUnit" placeholder="кг, чашки, км..."></div><div class="field"><label>Цель в неделю (для привычки)</label><input id="growthTrackerWeekly" type="number" min="1" max="14" value="3"></div></div><div class="split" style="margin-top:10px"><button class="btn" onclick="growthSaveTracker()">Сохранить</button><button class="btn ghost" onclick="document.getElementById('growthTrackerEditor').hidden=true">Отмена</button></div></div>`)}
function growthTrackerControl(t){const active=!!growthData().activeTimers[t.id];if(t.type==="timer")return `<button class="btn ${active?"secondary":""} small" onclick="growthToggleTimer('${t.id}')">${active?"■ Завершить":"▶ Старт"}</button>`;if(t.type==="tick"||t.type==="habit")return `<button class="btn secondary small" onclick="growthQuickLog('${t.id}')">+1</button>`;const attrs=t.type==="range"?`min="${t.min??1}" max="${t.max??10}" value="5"`:'step="any"';return `<input id="growth-value-${t.id}" type="number" ${attrs} placeholder="${escapeHtml(t.unit||"значение")}"><button class="btn secondary small" onclick="growthQuickLog('${t.id}')">Записать</button>`}
function renderTrackingOs(){const box=document.getElementById("trackingOsCommand"),list=document.getElementById("growthTrackerList"),habits=document.getElementById("habitStrengthList"),recent=document.getElementById("growthRecent"),heat=document.getElementById("growthHeatmap");if(!box||!list||!habits||!recent||!heat)return;const events=lifeTimelineEvents(35),week=events.filter(x=>x.dateKey>=localDateKey(addDays(new Date(),-6))),minutes=week.reduce((s,x)=>s+(+x.durationMin||0),0),days=new Set(week.map(x=>x.dateKey)).size,hrs=habitStrengthRows(),avg=hrs.length?hrs.reduce((s,x)=>s+x.strength,0)/hrs.length:0,pf=growthTodayPlanFact();box.innerHTML=`<div class="report-grid"><div class="report-item"><div class="smallcaps">Событий 7 дней</div><b>${week.length}</b></div><div class="report-item"><div class="smallcaps">Зафиксировано времени</div><b>${Math.round(minutes/6)/10} ч</b></div><div class="report-item"><div class="smallcaps">Активных дней</div><b>${days}/7</b></div><div class="report-item"><div class="smallcaps">Средняя сила привычек</div><b>${Math.round(avg)}%</b></div><div class="report-item"><div class="smallcaps">Сегодня план / факт</div><b>${pf.planned} / ${pf.fact} мин</b></div></div>`;list.innerHTML=growthTrackers().map(t=>`<div class="growth-tracker"><div class="split"><div><div class="qtitle">${escapeHtml(t.name)}</div><div class="qmeta">${escapeHtml(t.area)} • ${growthTrackerTypeLabel(t.type)}${t.unit?` • ${escapeHtml(t.unit)}`:""}</div></div><button class="btn ghost small" onclick="growthArchiveTracker('${t.id}')">×</button></div><div class="split" style="margin-top:8px">${growthTrackerControl(t)}</div></div>`).join("")||'<div class="empty">Добавь трекер.</div>';habits.innerHTML=hrs.length?hrs.map(x=>`<div class="log-item"><div class="growth-strength"><div><div class="qtitle">${escapeHtml(x.title)}</div><div class="qmeta">30 дней: ${Math.round(x.rate30)}% • тренд ${x.trend>=0?"+":""}${Math.round(x.trend)} п.п.</div></div><div class="statbar"><i style="width:${clamp(x.strength,0,100)}%"></i></div><b>${Math.round(x.strength)}%</b></div></div>`).join(""):'<div class="empty">Создай рутины — здесь появится сила привычек.</div>';heat.innerHTML=growthHeatmap(35);recent.innerHTML=events.slice(0,8).map(x=>`<div class="log-item"><div class="qtitle">${escapeHtml(x.title)} • ${x.dateKey}</div><div class="qmeta">${escapeHtml(x.area)}${x.durationMin?` • ${x.durationMin} мин`:""}${x.value!=null?` • ${escapeHtml(String(x.value))}${x.unit||""}`:""}${x.note?` • ${escapeHtml(x.note)}`:""}</div></div>`).join("")||'<div class="empty">Событий пока нет.</div>'}
