"use strict";
const fs=require("fs"),assert=require("assert");
const js=fs.readFileSync("ux-12.8.js","utf8"),css=fs.readFileSync("ux-12.8.css","utf8"),boot=fs.readFileSync("bootstrap.js","utf8"),vite=fs.readFileSync("vite.config.mjs","utf8");
assert.ok(js.includes("Life RPG 12.8"));
assert.ok(js.includes("No state migration"));
assert.ok(js.includes('UX128_NAV_KEY="life-rpg-ux128-nav"'));
assert.ok(js.includes("function ux128RestoreNavigation"));
assert.ok(js.includes("function ux128EnsureSearch"));
assert.ok(js.includes("dashboardSearchRows"));
assert.ok(js.includes("function ux128EnsureRecent"));
assert.ok(js.includes("S.auditLog"));
assert.ok(js.includes('data.ux128Action')||js.includes("dataset.ux128Action"));
for(const action of ["task","inbox","recent","search","import"])assert.ok(js.includes(`"${action}"`),`missing quick action ${action}`);
assert.ok(js.includes('document.getElementById("weeklyReview")'));
assert.ok(js.includes('document.getElementById("calibrationOsCommand")'));
assert.ok(js.includes('calibration.dataset.ux7View="settings"'));
assert.ok(js.includes("ux128-sticky-actions"));
assert.ok(css.includes("min-height:44px"));
assert.ok(css.includes(":focus-visible"));
assert.ok(css.includes("prefers-reduced-motion"));
assert.ok(css.includes(".ux128-sticky-actions"));
assert.ok(css.includes(".ux128-search-row"));
assert.ok(boot.includes('"ux-12.8.js"'));
assert.ok(boot.includes('["ensureUx128Ui","renderUx128"]'));
assert.ok(vite.includes('"ux-12.8.js"')&&vite.includes('"ux-12.8.css"'));
console.log("OK — Mobile UX 12.8 navigation, search, Recent, consolidation, sticky actions and accessibility contracts passed");
