"use strict";
const fs=require("fs"),path=require("path"),assert=require("assert");
const root=__dirname,css=fs.readFileSync(path.join(root,"styles.css"),"utf8"),ui=fs.readFileSync(path.join(root,"ui.js"),"utf8"),boot=fs.readFileSync(path.join(root,"bootstrap.js"),"utf8"),html=fs.readFileSync(path.join(root,"index.html"),"utf8");
assert.ok(css.includes("Life RPG 12.0.2 — Full Visual Redesign"),"8.2 visual system missing");
assert.ok(ui.includes('classList.add("ux7","ui82")'),"ui82 body class missing");
assert.ok(ui.includes("function ui82SyncChrome"),"ui82 chrome sync missing");
assert.ok(boot.includes("ui82SyncChrome"),"main navigation does not sync ui82 chrome");
assert.ok(html.includes('name="theme-color" content="#08090c"'),"8.2 theme color missing");
assert.ok(html.includes('class="card span-12 quick-card"'),"quick-card semantic class missing");
assert.ok(/quickAction\('tennis'\)[\s\S]*?<svg/.test(html),"quick actions are not using consistent SVG icons");
assert.ok(css.includes(".ui82 .quick{grid-template-columns:repeat(6"),"desktop shortcut grid missing");
assert.ok(css.includes(".ui82 .quick{grid-template-columns:repeat(3,1fr)"),"mobile 3-column shortcut grid missing");
assert.ok(css.includes(".ui82 .life-score{grid-template-columns:90px 1fr"),"Life Score redesign missing");
assert.ok(css.includes(".ui82 .financial-command-card,.ui82 .bank-sync-card,.ui82 .money-engine-card,.ui82 .autopilot-hero"),"finance legacy hero overrides missing");
assert.ok(css.includes(".ui82 .crm-deal"),"CRM redesign missing");
assert.ok(css.includes(".ui82 .ocr-row"),"OCR redesign missing");
assert.ok(css.includes(".ui82 .book"),"reading-card redesign missing");
assert.ok(css.includes(".ui82 .ach"),"achievement redesign missing");
assert.ok(css.includes(".ui82 .day.l4"),"activity-calendar redesign missing");
assert.ok(css.includes(".ui82 .account-row"),"account-row redesign missing");
assert.ok(css.includes(".ui82 .autopilot-step"),"autopilot redesign missing");
assert.ok(css.includes(".ui82 .bank-sync-summary>div"),"bank sync summary redesign missing");
assert.ok(css.includes(".ui82 .ux7-action-grid"),"quick sheet redesign missing");
assert.ok(css.includes(".ui82 .ux7-fab.ui82-fab-hidden"),"contextual FAB style missing");
assert.ok(ui.includes('(sectionId==="today")'),"FAB must be hidden on Today where shortcuts already exist");
assert.ok(css.includes("background:#08090c;background-image:none"),"opaque sticky header redesign missing");
console.log("OK — Life RPG 12.0.2 full visual-layout tests passed");
