"use strict";

/* Life RPG 8.0.1 — Work and CRM */

const WORK_WEEKLY=[
  {id:"contacts20",title:()=>`${workTarget("contacts",20)} новых целевых контактов`,stat:"Карьера",xp:120,condition:()=>workWeek().contacts>=workTarget("contacts",20)},
  {id:"follow10",title:()=>`${workTarget("followups",10)} follow-up`,stat:"Карьера",xp:100,condition:()=>workWeek().followups>=workTarget("followups",10)},
  {id:"lpr3",title:()=>`${workTarget("lpr",3)} разговора с ЛПР`,stat:"Карьера",xp:150,condition:()=>workWeek().lpr>=workTarget("lpr",3)},
  {id:"meetings3",title:()=>`${workTarget("meetings",3)} встречи / созвона`,stat:"Карьера",xp:120,condition:()=>workWeek().meetings>=workTarget("meetings",3)},
  {id:"proposals3",title:()=>`${workTarget("proposals",3)} качественных КП / расчёта`,stat:"Карьера",xp:120,condition:()=>workWeek().proposals>=workTarget("proposals",3)},
  {id:"crm",title:"CRM без просроченных следующих шагов",stat:"Дисциплина",xp:150,condition:()=>S.crmDeals.some(d=>!["Выиграно","Проиграно"].includes(d.stage))&&crmOverdue().length===0}
];

function workingDaysLeft(d=new Date()){let n=0,x=new Date(d.getFullYear(),d.getMonth(),d.getDate(),12),end=new Date(d.getFullYear(),d.getMonth()+1,0,12);while(x<=end){const wd=x.getDay();if(wd!==0&&wd!==6)n++;x=addDays(x,1)}return n}

function workTarget(key,fallback=0){const v=Number(S.workTargets?.[key]);return Number.isFinite(v)&&v>=0?v:fallback}

function workWeek(){const [a,b]=weekBounds();return aggregateWork(S.workLogs.filter(x=>inRange(x.date,a,b)))}

function workMonth(){return aggregateWork(S.workLogs.filter(x=>x.date.startsWith(localMonthKey())))}

function aggregateWork(arr){return arr.reduce((o,x)=>({sales:o.sales+(+x.sales||0),contacts:o.contacts+(+x.contacts||0),followups:o.followups+(+x.followups||0),lpr:o.lpr+(+x.lpr||0),meetings:o.meetings+(+x.meetings||0),proposals:o.proposals+(+x.proposals||0),wins:o.wins+(+x.wins||0),pipeline:o.pipeline+(+x.pipeline||0)}),{sales:0,contacts:0,followups:0,lpr:0,meetings:0,proposals:0,wins:0,pipeline:0})}

function workXpOnDate(dateKey){return (S.workLogs||[]).filter(x=>x.date===dateKey).reduce((s,x)=>s+(+x.xpAward||0),0)}

async function addWorkLog(){const date=$("workDate")?.value||localDateKey();if(!validActivityDate(date)){toast("Рабочую запись можно добавить только за сегодня или прошедшую дату");return}const x={id:uid(),date,createdAt:new Date().toISOString(),sales:Math.max(0,+$("workSales").value||0),contacts:Math.max(0,+$("workContacts").value||0),followups:Math.max(0,+$("workFollowups").value||0),lpr:Math.max(0,+$("workLpr").value||0),meetings:Math.max(0,+$("workMeetings").value||0),proposals:Math.max(0,+$("workProposals").value||0),wins:Math.max(0,+$("workWins").value||0),pipeline:Math.max(0,+$("workPipeline").value||0),note:$("workNote").value.trim()};const raw=Math.min(120,Math.min(15,x.contacts*3)+Math.min(20,x.followups*2)+Math.min(30,x.lpr*10)+Math.min(20,x.meetings*10)+Math.min(24,x.proposals*8)+Math.min(20,x.wins*10)+(x.sales>0?10:0));x.xpAward=Math.min(raw,Math.max(0,120-workXpOnDate(date)));S.workLogs.unshift(x);S.workLogs.sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(b.createdAt||"").localeCompare(String(a.createdAt||"")));addXp(x.xpAward,"Карьера","Рабочая запись",`work:${x.id}`,"process",date);["workSales","workContacts","workFollowups","workLpr","workMeetings","workProposals","workWins","workPipeline"].forEach(id=>$(id).value=0);$("workNote").value="";if($("workDate"))$("workDate").value=localDateKey();await save(`Рабочая запись сохранена${x.xpAward?` • +${x.xpAward} XP`:" • дневной лимит XP достигнут"}`)}

async function deleteWork(id){const i=S.workLogs.findIndex(x=>x.id===id);if(i<0)return;const x=S.workLogs[i];if(!confirm("Удалить эту рабочую запись? XP за неё будет снят."))return;S.workLogs.splice(i,1);removeXp(x.xpAward||0,"Карьера","Удалена рабочая запись",`work:${id}`,x.date);await save("Рабочая запись удалена")}

const CRM_STAGE_PROB={"Лид":10,"Контакт":20,"ЛПР":35,"Расчёт / КП":50,"Тендер":65,"Согласование":80,"Заказ":95,"Выиграно":100,"Проиграно":0};

function crmWeightedPipeline(){return (S.crmDeals||[]).filter(d=>!["Выиграно","Проиграно"].includes(d.stage)).reduce((a,d)=>a+(+d.potential||0)*(+d.probability||0)/100,0)}

function crmMonthlyWeightedPipeline(month=localMonthKey()){return (S.crmDeals||[]).filter(d=>!["Выиграно","Проиграно"].includes(d.stage)&&String(d.closeDate||"").startsWith(month)).reduce((a,d)=>a+(+d.potential||0)*(+d.probability||0)/100,0)}

function crmOpenPipeline(){return (S.crmDeals||[]).filter(d=>!["Выиграно","Проиграно"].includes(d.stage)).reduce((a,d)=>a+(+d.potential||0),0)}

function crmOverdue(){const today=localDateKey();return (S.crmDeals||[]).filter(d=>!["Выиграно","Проиграно"].includes(d.stage)&&d.nextDate&&d.nextDate<today).sort((a,b)=>String(a.nextDate).localeCompare(String(b.nextDate))||(+b.potential||0)-(+a.potential||0))}

function crmParticipantsCount(d){return [d.client,d.investor,d.developer,d.generalContractor,d.hvacContractor,d.installer,d.designer,d.equipmentCustomer].filter(x=>String(x||"").trim()).length}

function crmCompleteness(d){if((+d.potential||0)<500000)return null;const checks=[!!(d.name&&d.city&&+d.potential>0),crmParticipantsCount(d)>=2,!!(d.nextStep&&d.nextDate),!!(d.decisionDate||d.tenderDate||d.closeDate),!!d.manufacturers,!!d.competitor,!!d.projectDocs,!!(d.lpr||d.procurement)];const done=checks.filter(Boolean).length;return {done,total:checks.length,ok:done===checks.length}}

function crmStageChanged(){const p=CRM_STAGE_PROB[$("crmStage").value];if(p!=null)$("crmProbability").value=p}

async function saveCrmDeal(){const id=$("crmDealId").value||"",name=$("crmName").value.trim(),potential=Math.max(0,+$("crmPotential").value||0);if(!name||potential<=0){toast("Укажи объект и потенциал");return}const val=x=>$(x)?.value?.trim?.()||"",data={name,client:val("crmClient"),city:val("crmCity"),region:val("crmRegion"),link:val("crmLink"),potential,stage:$("crmStage").value,probability:clamp(+$(("crmProbability")).value||0,0,100),lpr:val("crmLpr"),competitor:val("crmCompetitor"),nextStep:val("crmNextStep"),nextDate:$("crmNextDate").value,closeDate:$("crmCloseDate").value,investor:val("crmInvestor"),developer:val("crmDeveloper"),generalContractor:val("crmGeneralContractor"),hvacContractor:val("crmHvacContractor"),installer:val("crmInstaller"),designer:val("crmDesigner"),equipmentCustomer:val("crmEquipmentCustomer"),procurement:val("crmProcurement"),projectDocs:val("crmProjectDocs"),manufacturers:val("crmManufacturers"),decisionDate:$("crmDecisionDate")?.value||"",tenderDate:$("crmTenderDate")?.value||"",realizationDate:$("crmRealizationDate")?.value||"",updatedAt:new Date().toISOString()};let deal;if(id){deal=S.crmDeals.find(x=>x.id===id);if(deal)Object.assign(deal,data);audit("CRM сделка изменена","work",name)}else{deal={id:uid(),createdAt:new Date().toISOString(),...data};S.crmDeals.unshift(deal);audit("CRM сделка добавлена","work",name)}const q=crmCompleteness(deal);clearCrmForm();await save(q&&!q.ok?`Сделка сохранена • карточка ≥500k заполнена ${q.done}/${q.total}`:"Сделка сохранена")}

function editCrmDeal(id){const d=S.crmDeals.find(x=>x.id===id);if(!d)return;const map={crmDealId:"id",crmName:"name",crmClient:"client",crmCity:"city",crmRegion:"region",crmLink:"link",crmPotential:"potential",crmStage:"stage",crmProbability:"probability",crmLpr:"lpr",crmCompetitor:"competitor",crmNextStep:"nextStep",crmNextDate:"nextDate",crmCloseDate:"closeDate",crmInvestor:"investor",crmDeveloper:"developer",crmGeneralContractor:"generalContractor",crmHvacContractor:"hvacContractor",crmInstaller:"installer",crmDesigner:"designer",crmEquipmentCustomer:"equipmentCustomer",crmProcurement:"procurement",crmProjectDocs:"projectDocs",crmManufacturers:"manufacturers",crmDecisionDate:"decisionDate",crmTenderDate:"tenderDate",crmRealizationDate:"realizationDate"};for(const [el,k] of Object.entries(map))if($(el))$(el).value=d[k]??"";document.getElementById("crmEditorCard")?.scrollIntoView({behavior:"smooth",block:"center"})}

function clearCrmForm(){for(const id of ["crmDealId","crmName","crmClient","crmCity","crmRegion","crmLink","crmPotential","crmLpr","crmCompetitor","crmNextStep","crmNextDate","crmCloseDate","crmInvestor","crmDeveloper","crmGeneralContractor","crmHvacContractor","crmInstaller","crmDesigner","crmEquipmentCustomer","crmProcurement","crmProjectDocs","crmManufacturers","crmDecisionDate","crmTenderDate","crmRealizationDate"])if($(id))$(id).value="";if($("crmStage"))$("crmStage").value="Лид";if($("crmProbability"))$("crmProbability").value=10}

function deleteCrmDeal(id){const d=S.crmDeals.find(x=>x.id===id);if(!d)return;if(!confirm(`Удалить сделку «${d.name}»?`))return;S.crmDeals=S.crmDeals.filter(x=>x.id!==id);audit("CRM сделка удалена","work",d.name);save("Сделка удалена")}

function renderCrm(){const open=crmOpenPipeline(),weightedMonth=crmMonthlyWeightedPipeline(),sales=workMonth().sales,plan=+S.settings.workMonthlyPlan||0,forecast=sales+weightedMonth,gap=plan>0?Math.max(0,plan-forecast):null,over=crmOverdue(),undated=(S.crmDeals||[]).filter(d=>!["Выиграно","Проиграно"].includes(d.stage)&&!d.closeDate).length;$("crmSummary").innerHTML=`<div class="report-grid"><div class="report-item"><div class="smallcaps">Открытая воронка</div><b>${rub(open)}</b></div><div class="report-item"><div class="smallcaps">Взвешено на этот месяц</div><b>${rub(weightedMonth)}</b></div><div class="report-item"><div class="smallcaps">Факт + прогноз месяца</div><b>${rub(forecast)}</b></div><div class="report-item"><div class="smallcaps">Дефицит до плана</div><b class="${gap?"income-bad":"income-good"}">${gap==null?"—":rub(gap)}</b></div></div>${undated?`<div class="status" style="margin-top:10px">Без даты закрытия: <b>${undated}</b> сделок — они не включены в прогноз месяца.</div>`:""}${over.length?`<div class="notice" style="margin-top:10px"><b>Просрочено следующих шагов: ${over.length}</b></div>`:""}`;const deals=(S.crmDeals||[]).slice().sort((a,b)=>(a.nextDate||"9999").localeCompare(b.nextDate||"9999"));$("crmDealList").innerHTML=deals.length?deals.map(d=>{const q=crmCompleteness(d),due=d.nextDate===localDateKey(),openDeal=!["Выиграно","Проиграно"].includes(d.stage);return `<div class="crm-deal ${openDeal&&d.nextDate&&d.nextDate<localDateKey()?"crm-overdue":""}"><div class="crm-head"><div><b>${escapeHtml(d.name)}</b><div class="sub">${escapeHtml(d.client||"")} ${d.city?`• ${escapeHtml(d.city)}`:""}${d.region?` • ${escapeHtml(d.region)}`:""}</div></div><b>${rub(d.potential)}</b></div><div class="qmeta">${escapeHtml(d.stage)} • ${d.probability}% • weighted ${rub(d.potential*d.probability/100)}${d.lpr?` • ЛПР: ${escapeHtml(d.lpr)}`:""}${d.competitor?` • конкурент: ${escapeHtml(d.competitor)}`:""}</div>${q?`<div class="qmeta"><span class="tag ${q.ok?"good":"warn"}">карточка ≥500k ${q.done}/${q.total}</span> • участников ${crmParticipantsCount(d)}</div>`:""}<div class="goal"><div class="goal-top"><span>${escapeHtml(d.nextStep||"Следующий шаг не указан")}</span><b>${d.nextDate?fmtDate(parseLocal(d.nextDate)):"—"}${due?" • сегодня":""}</b></div></div><div class="split"><button class="btn ghost small" onclick="editCrmDeal('${d.id}')">Изменить</button><button class="btn ghost small" onclick="deleteCrmDeal('${d.id}')">Удалить</button></div></div>`}).join(""):`<div class="empty">Добавь первый объект / сделку.</div>`}

function renderWork(){const m=workMonth(),plan=S.settings.workMonthlyPlan||0,p=plan?clamp(m.sales/plan*100,0,100):0;$("workPlanKpi").textContent=rub(plan);$("workSalesKpi").textContent=rub(m.sales);$("workPctKpi").textContent=pct(p,0);$("workProgress").style.width=p+"%";$("workProgressText").textContent=`${rub(m.sales)} / ${rub(plan)}`;$("workActivitySummary").innerHTML=[["Контакты",m.contacts],["Follow-up",m.followups],["ЛПР",m.lpr],["Встречи",m.meetings],["КП / расчёты",m.proposals],["Победы",m.wins],["Воронка",compactRub(m.pipeline)],["Продажи",compactRub(m.sales)]].map(x=>`<div class="report-item"><div class="smallcaps">${x[0]}</div><div style="font-weight:900;margin-top:4px">${x[1]}</div></div>`).join("");$("workQuests").innerHTML=renderQuestGroup(WORK_WEEKLY,"work")+renderMonthlyWorkQuest();renderWorkPace();renderWorkFunnel();renderCrm();$("workLogList").innerHTML=S.workLogs.length?S.workLogs.slice(0,8).map(x=>`<div class="log-item"><div class="qtitle">${fmtDate(parseLocal(x.date))} • ${rub(x.sales)}</div><div class="score">контакты ${x.contacts} • follow-up ${x.followups} • ЛПР ${x.lpr} • КП ${x.proposals} • победы ${x.wins||0} • воронка ${compactRub(x.pipeline||0)}</div>${x.note?`<div class="qmeta">${escapeHtml(x.note)}</div>`:""}<button class="btn ghost small" style="margin-top:7px" onclick="deleteWork('${x.id}')">Удалить</button></div>`).join(""):'<div class="empty">Добавь первый рабочий день.</div>'}

function renderWorkPace(){const m=workMonth(),remain=Math.max(0,S.settings.workMonthlyPlan-m.sales),days=Math.max(1,workingDaysLeft()),need=remain/days,logged=new Set(S.workLogs.filter(x=>x.date.startsWith(localMonthKey())).map(x=>x.date)).size,avg=logged?m.sales/logged:0;$("workPace").innerHTML=`<div class="goal"><div class="goal-top"><span>Осталось до плана</span><b>${rub(remain)}</b></div><div class="goal-top" style="margin-top:7px"><span>Рабочих дней осталось</span><b>${days}</b></div><div class="goal-top" style="margin-top:7px"><span>Нужно в среднем / рабочий день</span><b>${rub(need)}</b></div><div class="goal-top" style="margin-top:7px"><span>Текущий средний факт / записанный день</span><b>${rub(avg)}</b></div></div>`}

function renderWorkFunnel(){const m=workMonth(),rows=[["Контакты",m.contacts,m.contacts],["ЛПР",m.lpr,m.contacts?m.lpr/m.contacts*100:0],["КП",m.proposals,m.lpr?m.proposals/m.lpr*100:0],["Победы",m.wins,m.proposals?m.wins/m.proposals*100:0]];$("workFunnel").innerHTML=`<div class="funnel">${rows.map((x,i)=>`<div class="funnel-row"><span>${x[0]}</span><div class="funnel-bar"><i style="width:${i===0?100:clamp(x[2],0,100)}%"></i></div><b>${i===0?x[1]:`${x[1]} • ${pct(x[2],0)}`}</b></div>`).join("")}</div><div class="status" style="margin-top:10px">Добавлено в воронку за месяц: <b>${rub(m.pipeline)}</b></div>`}

function renderMonthlyWorkQuest(){const key=`work:monthly:${localMonthKey()}:salesplan`,done=!!S.questDone[key],plan=+S.settings.workMonthlyPlan||0,ready=plan>0&&workMonth().sales>=plan,p=plan>0?clamp(workMonth().sales/plan*100,0,100):0;return `<div class="quest"><button class="check ${done?"done":""} ${!ready&&!done?"locked":""}" onclick="claimMonthlyWork()">${done?"✓":ready?"":"·"}</button><div class="qbody"><div class="qtitle">Выполнить месячный план продаж</div><div class="qmeta">Карьера • ${plan<=0?"сначала задай план":ready&&!done?"готово к получению":pct(p,0)}</div></div><div class="xp">+600 XP</div></div>`}

async function claimMonthlyWork(){const key=`work:monthly:${localMonthKey()}:salesplan`,plan=+S.settings.workMonthlyPlan||0;if(S.questDone[key])return;if(plan<=0){toast("Сначала задай месячный план продаж");return}if(workMonth().sales<plan){toast("План ещё не выполнен");return}S.questDone[key]=true;addXp(600,"Карьера","Выполнен месячный план",key);await save("План продаж закрыт • +600 XP")}
